"""The porter's own drift check, run by the suite rather than by hand.

Every file under api/ is generated: its header says "REGENERATED by the
mirror's port_app.py -- edit the mirror script, not this file". A fix made in
the generated file instead works perfectly, passes review, and is then deleted
without a word by whoever next runs the porter.

The mirror ships `scripts/check_ported.py`, which ports into a temporary tree
and compares. It caught exactly this -- a settings-driven task-worker test
added to api/actuals.py and not to the mirror -- but only because somebody
thought to run it. Nothing in this suite did, so the drift sat on master
through a full green run. It runs here now, so the next one fails a test on
the way in.

A missing mirror checkout is a skip, never a failure: see tests/mirror.py.

On a branch that has declared api/ to be source -- `altura`, which deploys the
packaged app and runs no porter downstream of it -- this check has nothing to
prove and skips deliberately, gated on docs/ALTURA_FORK.md rather than on the
mirror's absence. It is kept, not deleted: reconciling the fork back into the
mirror deletes that file and re-arms this.
"""

import os
import subprocess
import sys
import unittest

from work_management.tests import mirror

CHECKER = os.path.join(mirror.ROOT, "scripts", "check_ported.py")


class TestTheGeneratedFilesAreNotHandEdited(unittest.TestCase):
	def test_a_fresh_port_reproduces_every_api_module(self):
		if mirror.forked():
			raise unittest.SkipTest(mirror.FORK_SKIP)
		if not mirror.present() or not os.path.exists(CHECKER):
			raise unittest.SkipTest("mirror not checked out at " + mirror.ROOT)
		done = subprocess.run([sys.executable, CHECKER], capture_output=True,
			text=True, cwd=mirror.ROOT)
		# stdout carries the per-file line and the first differing line number,
		# which is the whole value of the failure -- so put it in the message.
		self.assertEqual(done.returncode, 0,
			"a fresh port does not reproduce the app's api/ modules, so the next "
			"port_app.py run would revert whatever was hand-edited into them.\n\n"
			+ (done.stdout or "") + (done.stderr or ""))


if __name__ == "__main__":
	unittest.main()
