"""The fork is declared out loud, and the tests it disarms say so.

`altura` deploys the packaged app, so `work_management/api/*.py` and the four
screens under `public/js/` are hand-maintained source here. Three tests exist to
forbid exactly that -- the porter's drift check and two byte-compares against
the mirror's copies of the screens -- and on this branch they have nothing to
prove.

Silently deleting them would lose the ability to fold this work back into the
mirror later. Leaving them skipping *because the mirror happens to be absent
from this machine* would be worse: they would fail the moment somebody ran the
suite on the author's box, where the mirror lives, and the divergence would read
as an accident instead of a decision.

So they skip on the presence of docs/ALTURA_FORK.md, and this checks that the
switch, the reason string and the document are all really there -- because a
skip that stops skipping is discovered by a red suite on somebody else's
machine.
"""

import os
import unittest

from work_management.tests import mirror

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
API = os.path.join(APP, "api")


def read(path):
	with open(path) as handle:
		return handle.read()


class TestTheDeclarationExists(unittest.TestCase):
	def test_the_document_is_there(self):
		self.assertTrue(os.path.exists(mirror.FORK_NOTE),
			"docs/ALTURA_FORK.md is the switch as well as the declaration; without "
			"it the mirror-contract tests re-arm and this branch fails them")

	def test_the_switch_agrees_with_it(self):
		self.assertTrue(mirror.forked())

	def test_it_names_what_diverges(self):
		"""A future reconciliation needs the checklist, not just the news."""
		text = read(mirror.FORK_NOTE)
		for item in ("port_app.py", "check_ported.py", "MIRROR_HANDOFF.md",
				"wm_masterplan.py", "wm_planner.py", "wm_actuals.py",
				"wm_payroll.py", "wm_payment.py"):
			with self.subTest(item=item):
				self.assertIn(item, text)


class TestTheDisarmedTestsSkipForTheStatedReason(unittest.TestCase):
	"""Each is loaded and run for real: an assertion that the source contains a
	skipTest call would pass just as happily on a test that never reaches it."""

	CASES = (
		("work_management.tests.test_the_generated_files_are_not_hand_edited",
			"TestTheGeneratedFilesAreNotHandEdited",
			"test_a_fresh_port_reproduces_every_api_module"),
		("work_management.tests.test_no_capability_is_stranded",
			"TestTheAppAndMirrorScreensAgree",
			"test_every_screen_matches_the_mirror_byte_for_byte"),
		("work_management.tests.test_master_plan_resolution",
			"TestTheScreenSendsTheChoice",
			"test_the_app_and_mirror_copies_agree"),
	)

	def run_one(self, module, klass, method):
		import importlib

		case = getattr(importlib.import_module(module), klass)(method)
		result = unittest.TestResult()
		case.run(result)
		return result

	def test_all_three_skip(self):
		for module, klass, method in self.CASES:
			with self.subTest(test=method):
				result = self.run_one(module, klass, method)
				self.assertEqual(result.errors, [])
				self.assertEqual(result.failures, [])
				self.assertEqual(len(result.skipped), 1,
					method + " did not skip on a forked branch")

	def test_the_reason_is_the_one_a_reader_can_follow(self):
		"""'mirror not checked out' would send the next reader looking for a
		checkout. The reason has to name the branch and the document."""
		for module, klass, method in self.CASES:
			with self.subTest(test=method):
				result = self.run_one(module, klass, method)
				self.assertEqual(result.skipped[0][1], mirror.FORK_SKIP)

	def test_the_reason_points_at_a_file_that_exists(self):
		self.assertIn("docs/ALTURA_FORK.md", mirror.FORK_SKIP)
		self.assertTrue(os.path.exists(os.path.join(APP, os.pardir, "docs",
			"ALTURA_FORK.md")))


class TestTheApiModulesNoLongerSendReadersToTheMirror(unittest.TestCase):
	"""The header said "edit the mirror script, not this file". Following it
	here means editing a file that does not exist on this branch's deployment
	path, and losing the change."""

	MODULES = ("masterplan.py", "planner.py", "actuals.py", "payment.py",
		"payroll.py", "assigner.py", "dashboard.py", "rates.py",
		"payroll_drift.py", "payroll_recompute.py")

	def test_no_module_still_claims_to_be_regenerated(self):
		stale = [m for m in self.MODULES
			if "REGENERATED by the mirror" in read(os.path.join(API, m))]
		self.assertEqual(stale, [],
			"these still tell the reader to edit a mirror script: " + ", ".join(stale))

	def test_every_module_points_at_the_declaration_instead(self):
		absent = [m for m in self.MODULES
			if "docs/ALTURA_FORK.md" not in read(os.path.join(API, m))]
		self.assertEqual(absent, [],
			"these say nothing about the fork: " + ", ".join(absent))


if __name__ == "__main__":
	unittest.main()
