# Ported from Kaitet live Server Script "wm_masterplan" (API) — logic unchanged.
# Farms / projects / company / approver roles now come from Work Management Settings
# (falls back to the original Kaitet defaults) — see upande_work_management/api/config.py.
# REGENERATED by kaitet-work-management/port_app.py — edit the mirror script, not this file.

import json

import frappe

from upande_work_management.api.config import get_config


@frappe.whitelist()
def wm_masterplan(**kwargs):
    _cfg = get_config()
    FARM_PROJECT = _cfg["farm_project"]
    DEFAULT_COMPANY = _cfg["default_company"]
    FARMS = _cfg["farms"]
    BLOCK_EXCLUDE = _cfg["block_exclude"]
    FARM_APPROVER_ROLE = _cfg["farm_approver_role"]

    # ==================================================================
    # SERVER SCRIPT — "WM Master Plan" (API, api_method=wm_masterplan)
    #
    # The budget layer above the planner: which activities a farm may plan in a
    # period, how much work each may cover and what it may cost.
    #
    # These are CUSTOM doctypes on live and therefore carry no Python controller,
    # so every invariant -- no overlapping approved plans for a farm, one line per
    # task, totals, and who may do what -- is enforced here.
    #
    # The cap arithmetic mirrors upande_work_management/master_plan.py, which is
    # unit-tested. Keep the two in step.
    #
    # No def/return allowed in the sandbox, so everything is inline.
    # ==================================================================
    MP_EDIT_ROLES = ["Farm Manager", "HOD HR", "General Manager", "System Manager"]
    MP_GM_ROLES = ["General Manager", "System Manager"]
    TOLERANCE = 0.005

    mp_roles = frappe.db.get_all("Has Role", filters={"parent": frappe.session.user}, pluck="role")
    CAN_EDIT = 0
    for mr in MP_EDIT_ROLES:
        if mr in mp_roles or mr == "Farm Manager":
            # farm-manager roles are per farm ("Farm Manager Saboti"), so match the prefix
            for hr in mp_roles:
                if hr == mr or hr.startswith("Farm Manager"):
                    CAN_EDIT = 1
    CAN_GM = 0
    for mr in MP_GM_ROLES:
        if mr in mp_roles:
            CAN_GM = 1

    # consultants are named in Work Management Settings, same list the weekly
    # review already uses
    mp_cons_raw = frappe.db.get_single_value("Work Management Settings", "consultant_users") or ""
    mp_cons = []
    for cu in str(mp_cons_raw).split(","):
        cv = cu.strip().lower()
        if cv:
            mp_cons.append(cv)
    IS_CONSULTANT = 1 if (frappe.session.user.lower() in mp_cons or "System Manager" in mp_roles) else 0

    action = frappe.form_dict.get("action") or "meta"
    out = {}

    if action == "meta":
        out["user"] = frappe.session.user
        out["can_edit"] = CAN_EDIT
        out["can_gm_approve"] = CAN_GM
        out["is_consultant"] = IS_CONSULTANT
        out["farms"] = [f.name for f in frappe.db.get_all("Farm", fields=["name"], order_by="name")]
        out["counts"] = frappe.db.sql("""
            SELECT workflow_state st, COUNT(*) n
            FROM `tabWork Management Master Plan` GROUP BY workflow_state
        """, as_dict=True)

    elif action == "list":
        mp_farm = frappe.form_dict.get("farm")
        mp_state = frappe.form_dict.get("state")
        mp_filters = {}
        if mp_farm:
            mp_filters["farm"] = mp_farm
        if mp_state:
            mp_filters["workflow_state"] = mp_state
        out["plans"] = frappe.db.get_all("Work Management Master Plan",
            filters=mp_filters,
            fields=["name", "farm", "period_from", "period_to", "workflow_state",
                    "total_activities", "total_man_days", "total_cost",
                    "raised_by", "raised_on", "gm_approved_by", "gm_approved_on"],
            order_by="period_from desc", limit=200)

    elif action == "get":
        mp_name = frappe.form_dict.get("name")
        if not mp_name:
            out["error"] = "name is required"
        else:
            mp = frappe.db.get_value("Work Management Master Plan", mp_name,
                ["name", "farm", "period_from", "period_to", "workflow_state", "company",
                 "total_activities", "total_man_days", "total_cost",
                 "raised_by", "raised_on", "gm_approved_by", "gm_approved_on"], as_dict=True)
            if not mp:
                out["error"] = "no such master plan: " + str(mp_name)
            else:
                out["plan"] = mp
                out["activities"] = frappe.db.get_all("Work Management Master Plan Activity",
                    filters={"parent": mp_name},
                    fields=["name", "idx", "task", "man_days", "days", "work_qty", "uom", "rate", "cost",
                            "consultant_state", "consultant_by", "consultant_on",
                            "original_qty", "original_cost",
                            "planned_qty", "planned_cost", "remaining_qty", "remaining_cost", "remarks"],
                    order_by="idx")
                out["can_edit"] = 1 if (CAN_EDIT and mp.workflow_state in ("Draft", "Rejected")) else 0
                out["can_decide"] = 1 if (IS_CONSULTANT and mp.workflow_state == "Pending Consultant") else 0
                out["can_gm_approve"] = 1 if (CAN_GM and mp.workflow_state == "Pending GM") else 0

    elif action == "save":
        if not CAN_EDIT:
            out["error"] = ("Only a farm manager, the HR head or the general manager can "
                            "raise or edit a master plan.")
        else:
            sv_name = frappe.form_dict.get("name")
            sv_farm = frappe.form_dict.get("farm")
            sv_from = frappe.form_dict.get("period_from")
            sv_to = frappe.form_dict.get("period_to")
            sv_rows = json.loads(frappe.form_dict.get("activities") or "[]")
            sv_err = None
            if not sv_farm:
                sv_err = "Farm is required"
            elif not sv_from or not sv_to:
                sv_err = "The period is required"
            elif str(sv_to) < str(sv_from):
                sv_err = "Period To cannot be before Period From"
            elif not sv_rows:
                sv_err = "A master plan needs at least one activity"
            if not sv_err and sv_name:
                sv_state = frappe.db.get_value("Work Management Master Plan", sv_name, "workflow_state")
                if sv_state not in ("Draft", "Rejected"):
                    sv_err = "Only a Draft or Rejected master plan can be edited (state: " + str(sv_state) + ")"
            # one budget in force per farm per day, or the ceiling is ambiguous
            if not sv_err:
                sv_clash = frappe.db.sql("""
                    SELECT name, period_from, period_to FROM `tabWork Management Master Plan`
                    WHERE farm = %(f)s AND name != %(me)s
                      AND workflow_state = 'Approved'
                      AND period_from <= %(to)s AND period_to >= %(from)s
                    LIMIT 1
                """, {"f": sv_farm, "me": sv_name or "", "to": sv_to, "from": sv_from}, as_dict=True)
                if sv_clash:
                    sv_err = ("An approved master plan already covers those dates for " + str(sv_farm) +
                              ": " + sv_clash[0].name + " (" + str(sv_clash[0].period_from) +
                              " to " + str(sv_clash[0].period_to) + ")")
            # one line per activity
            if not sv_err:
                sv_seen = {}
                for sr in sv_rows:
                    st = sr.get("task")
                    if not st:
                        sv_err = "Every activity line needs a task"
                    elif sv_seen.get(st):
                        sv_err = str(st) + " appears twice. One line per activity."
                    sv_seen[st] = 1
            if sv_err:
                out["error"] = sv_err
            else:
                sv_snap = {}
                if sv_name:
                    # a consultant's Edit-work history (original_qty/original_cost/remarks)
                    # must survive the raiser's next save, even though every line is
                    # rebuilt from scratch below
                    for sx in frappe.db.get_all("Work Management Master Plan Activity",
                            filters={"parent": sv_name},
                            fields=["task", "original_qty", "original_cost", "remarks"]):
                        sv_snap[sx.task] = sx
                if sv_name:
                    d = frappe.get_doc("Work Management Master Plan", sv_name)
                    d.set("activities", [])
                else:
                    d = frappe.new_doc("Work Management Master Plan")
                    d.raised_by = frappe.session.user
                    d.raised_on = frappe.utils.now()
                    d.workflow_state = "Draft"
                d.farm = sv_farm
                d.period_from = sv_from
                d.period_to = sv_to
                if not d.company:
                    d.company = frappe.db.get_single_value("Work Management Settings", "default_company") \
                                or frappe.defaults.get_user_default("Company")
                sv_md = 0
                sv_cost = 0
                for sr in sv_rows:
                    ti = frappe.db.get_value("Task", sr.get("task"), ["custom_uom"], as_dict=True)
                    # the rate in force when the budget starts, then frozen on the line
                    rp = frappe.db.sql("""
                        SELECT rate FROM `tabWork Task Rate`
                        WHERE task = %(t)s AND valid_from <= %(d)s
                          AND (valid_to IS NULL OR valid_to >= %(d)s)
                        ORDER BY valid_from DESC LIMIT 1
                    """, {"t": sr.get("task"), "d": sv_from}, as_dict=True)
                    sv_rate = frappe.utils.flt(rp[0].rate, 6) if rp else frappe.utils.flt(
                        frappe.db.get_value("Task", sr.get("task"), "custom_rate"), 6)
                    sv_qty = frappe.utils.flt(sr.get("work_qty"))
                    row = d.append("activities", {})
                    row.task = sr.get("task")
                    row.man_days = frappe.utils.flt(sr.get("man_days"))
                    row.days = frappe.utils.cint(sr.get("days"))
                    row.work_qty = sv_qty
                    row.uom = ti.custom_uom if ti else None
                    row.rate = sv_rate
                    row.cost = frappe.utils.flt(sv_qty * sv_rate, 2)
                    row.consultant_state = "Pending"
                    sv_prev = sv_snap.get(sr.get("task"))
                    if sv_prev and frappe.utils.flt(sv_prev.original_qty):
                        # the ORIGINAL values, so never overwritten once set -- this
                        # composes with decide_line's own "if not flt(original_qty)" guard
                        row.original_qty = frappe.utils.flt(sv_prev.original_qty)
                        row.original_cost = frappe.utils.flt(sv_prev.original_cost)
                    row.remarks = sr.get("remarks") or (sv_prev.remarks if sv_prev else None)
                    sv_md = sv_md + frappe.utils.flt(sr.get("man_days"))
                    sv_cost = sv_cost + frappe.utils.flt(sv_qty * sv_rate, 2)
                d.total_activities = len(d.activities)
                d.total_man_days = sv_md
                d.total_cost = sv_cost
                d.flags.ignore_permissions = True
                d.save(ignore_permissions=True)
                frappe.db.commit()
                out["name"] = d.name
                out["totals"] = {"activities": d.total_activities,
                                 "man_days": d.total_man_days, "cost": d.total_cost}

    elif action == "submit_for_review":
        sr_name = frappe.form_dict.get("name")
        sr_state = frappe.db.get_value("Work Management Master Plan", sr_name, "workflow_state")
        if not CAN_EDIT:
            out["error"] = "Only a farm manager, the HR head or the general manager can submit a master plan."
        elif not sr_state:
            out["error"] = "no such master plan: " + str(sr_name)
        elif sr_state not in ("Draft", "Rejected"):
            out["error"] = "Only a Draft or Rejected master plan can be submitted (state: " + str(sr_state) + ")"
        else:
            frappe.db.set_value("Work Management Master Plan", sr_name,
                                "workflow_state", "Pending Consultant")
            frappe.db.commit()
            out["name"] = sr_name
            out["workflow_state"] = "Pending Consultant"

    elif action == "decide_line":
        dl_row = frappe.form_dict.get("row")
        dl_state = frappe.form_dict.get("state")
        dl_remark = frappe.form_dict.get("remarks")
        dl_qty = frappe.form_dict.get("work_qty")
        if not IS_CONSULTANT:
            out["error"] = "Only a consultant named in Work Management Settings can decide these lines."
        elif dl_state not in ("OK", "Edit work", "Rejected"):
            out["error"] = "state must be OK, Edit work or Rejected"
        else:
            dl = frappe.db.get_value("Work Management Master Plan Activity", dl_row,
                ["name", "parent", "task", "work_qty", "cost", "rate",
                 "original_qty", "original_cost"], as_dict=True)
            if not dl:
                out["error"] = "no such activity line: " + str(dl_row)
            elif frappe.db.get_value("Work Management Master Plan", dl.parent, "workflow_state") != "Pending Consultant":
                out["error"] = "This master plan is not awaiting consultant review."
            else:
                dl_set = {"consultant_state": dl_state,
                          "consultant_by": frappe.session.user,
                          "consultant_on": frappe.utils.now()}
                if dl_remark:
                    dl_set["remarks"] = dl_remark
                if dl_state == "Edit work" and dl_qty is not None and str(dl_qty) != "":
                    # keep what was originally asked for; the raiser must see the change
                    if not frappe.utils.flt(dl.original_qty):
                        dl_set["original_qty"] = frappe.utils.flt(dl.work_qty)
                        dl_set["original_cost"] = frappe.utils.flt(dl.cost)
                    dl_new = frappe.utils.flt(dl_qty)
                    dl_set["work_qty"] = dl_new
                    dl_set["cost"] = frappe.utils.flt(dl_new * frappe.utils.flt(dl.rate), 2)
                frappe.db.set_value("Work Management Master Plan Activity", dl_row, dl_set)
                # re-total the parent, then decide where the document goes
                dl_rows = frappe.db.sql("""
                    SELECT consultant_state, man_days, cost FROM `tabWork Management Master Plan Activity`
                    WHERE parent = %(p)s
                """, {"p": dl.parent}, as_dict=True)
                frappe.db.set_value("Work Management Master Plan", dl.parent, {
                    "total_activities": len(dl_rows),
                    "total_man_days": sum(frappe.utils.flt(x.man_days) for x in dl_rows),
                    "total_cost": sum(frappe.utils.flt(x.cost) for x in dl_rows),
                })
                dl_pending = len([x for x in dl_rows if x.consultant_state == "Pending"])
                dl_edit = len([x for x in dl_rows if x.consultant_state == "Edit work"])
                if dl_edit:
                    # an edited line goes back to the raiser with the whole document
                    frappe.db.set_value("Work Management Master Plan", dl.parent,
                                        "workflow_state", "Draft")
                    out["moved_to"] = "Draft"
                elif not dl_pending:
                    frappe.db.set_value("Work Management Master Plan", dl.parent,
                                        "workflow_state", "Pending GM")
                    out["moved_to"] = "Pending GM"
                frappe.db.commit()
                out["row"] = dl_row
                out["state"] = dl_state
                out["pending_lines"] = dl_pending
                out["edited_lines"] = dl_edit

    elif action == "gm_approve":
        ga_name = frappe.form_dict.get("name")
        ga_state = frappe.db.get_value("Work Management Master Plan", ga_name, "workflow_state")
        if not CAN_GM:
            out["error"] = "Only the general manager can approve a master plan."
        elif ga_state != "Pending GM":
            out["error"] = "This master plan is not awaiting GM approval (state: " + str(ga_state) + ")"
        else:
            ga_doc = frappe.db.get_value("Work Management Master Plan", ga_name,
                ["farm", "period_from", "period_to"], as_dict=True)
            # one budget in force per farm per day -- re-checked here because two
            # Drafts can both pass save's check (neither is Approved yet) and only
            # collide when the second one is approved
            ga_clash = frappe.db.sql("""
                SELECT name, period_from, period_to FROM `tabWork Management Master Plan`
                WHERE farm = %(f)s AND name != %(me)s
                  AND workflow_state = 'Approved'
                  AND period_from <= %(to)s AND period_to >= %(from)s
                LIMIT 1
            """, {"f": ga_doc.farm, "me": ga_name,
                  "to": ga_doc.period_to, "from": ga_doc.period_from}, as_dict=True)
            ga_ok = frappe.db.sql("""
                SELECT COUNT(*) n FROM `tabWork Management Master Plan Activity`
                WHERE parent = %(p)s AND consultant_state = 'OK'
            """, {"p": ga_name}, as_dict=True)[0].n
            if ga_clash:
                out["error"] = ("An approved master plan already covers those dates for " + str(ga_doc.farm) +
                                ": " + ga_clash[0].name + " (" + str(ga_clash[0].period_from) +
                                " to " + str(ga_clash[0].period_to) + ")")
            elif not ga_ok:
                out["error"] = "Every activity was rejected, so there is nothing to approve."
            else:
                frappe.db.set_value("Work Management Master Plan", ga_name, {
                    "workflow_state": "Approved",
                    "gm_approved_by": frappe.session.user,
                    "gm_approved_on": frappe.utils.now(),
                })
                frappe.db.commit()
                out["name"] = ga_name
                out["workflow_state"] = "Approved"
                out["plannable_activities"] = ga_ok

    elif action == "reject":
        rj_name = frappe.form_dict.get("name")
        rj_state = frappe.db.get_value("Work Management Master Plan", rj_name, "workflow_state")
        if not (CAN_GM or IS_CONSULTANT):
            out["error"] = "Only a consultant or the general manager can reject a master plan."
        elif rj_state not in ("Pending Consultant", "Pending GM"):
            out["error"] = "Only a master plan under review can be rejected (state: " + str(rj_state) + ")"
        else:
            frappe.db.set_value("Work Management Master Plan", rj_name, "workflow_state", "Rejected")
            frappe.db.commit()
            out["name"] = rj_name
            out["workflow_state"] = "Rejected"

    elif action == "headroom":
        # What may be planned for a farm on a date, and how much is left of each.
        # Mirrors line_headroom() in upande_work_management/master_plan.py.
        hd_farm = frappe.form_dict.get("farm")
        hd_from = frappe.form_dict.get("from_date") or frappe.utils.today()
        hd_to = frappe.form_dict.get("to_date") or hd_from
        if not hd_farm:
            out["error"] = "farm is required"
        else:
            hd_mp = frappe.db.sql("""
                SELECT name, period_from, period_to FROM `tabWork Management Master Plan`
                WHERE farm = %(f)s AND workflow_state = 'Approved'
                  AND period_from <= %(from)s AND period_to >= %(to)s
                ORDER BY period_from DESC LIMIT 1
            """, {"f": hd_farm, "from": hd_from, "to": hd_to}, as_dict=True)
            if not hd_mp:
                out["master_plan"] = None
                out["activities"] = []
                out["blocked_reason"] = ("No approved master plan covers " + str(hd_from) +
                                         " to " + str(hd_to) + " for " + str(hd_farm) +
                                         ". Planning is blocked until one is approved.")
            else:
                hd = hd_mp[0]
                out["master_plan"] = hd.name
                out["period"] = {"from": str(hd.period_from), "to": str(hd.period_to)}
                out["blocked_reason"] = None
                hd_acts = frappe.db.get_all("Work Management Master Plan Activity",
                    filters={"parent": hd.name, "consultant_state": "OK"},
                    fields=["name", "task", "uom", "rate", "work_qty", "cost"], order_by="idx")
                hd_out = []
                for ha in hd_acts:
                    hd_used = frappe.db.sql("""
                        SELECT COALESCE(SUM(quantity),0) q, COALESCE(SUM(total_cost),0) c
                        FROM `tabWork Management Planner`
                        WHERE task = %(t)s AND farm = %(f)s
                          AND IFNULL(workflow_state,'') != 'Rejected'
                          AND from_date <= %(pto)s AND to_date >= %(pfrom)s
                    """, {"t": ha.task, "f": hd_farm,
                          "pfrom": hd.period_from, "pto": hd.period_to}, as_dict=True)[0]
                    hd_pq = frappe.utils.flt(hd_used.q)
                    hd_pc = frappe.utils.flt(hd_used.c)
                    hd_rq = frappe.utils.flt(ha.work_qty) - hd_pq
                    hd_rc = frappe.utils.flt(ha.cost) - hd_pc
                    # report and persist the real figure, negative when over-consumed --
                    # clamping to 0 would make a genuine overrun look like an exact fit
                    # keep the stored figures current so the master plan screen and
                    # the planner never disagree
                    frappe.db.set_value("Work Management Master Plan Activity", ha.name, {
                        "planned_qty": hd_pq, "planned_cost": hd_pc,
                        "remaining_qty": hd_rq, "remaining_cost": hd_rc,
                    }, update_modified=False)
                    hd_out.append({"row": ha.name, "task": ha.task, "uom": ha.uom,
                                   "rate": frappe.utils.flt(ha.rate, 6),
                                   "work_qty": frappe.utils.flt(ha.work_qty),
                                   "cost": frappe.utils.flt(ha.cost),
                                   "planned_qty": hd_pq, "planned_cost": hd_pc,
                                   "remaining_qty": hd_rq, "remaining_cost": hd_rc,
                                   "exhausted": 1 if (hd_rq <= TOLERANCE or hd_rc <= TOLERANCE) else 0})
                frappe.db.commit()
                out["activities"] = hd_out

    elif action == "consumers":
        # Which plans are holding a line's budget. Without this, "why can't I plan
        # Handling?" has no answer and a forgotten Draft is invisible.
        cs_row = frappe.form_dict.get("row")
        cs = frappe.db.get_value("Work Management Master Plan Activity", cs_row,
            ["name", "parent", "task", "work_qty", "cost"], as_dict=True)
        if not cs:
            out["error"] = "no such activity line: " + str(cs_row)
        else:
            cs_mp = frappe.db.get_value("Work Management Master Plan", cs.parent,
                ["farm", "period_from", "period_to"], as_dict=True)
            out["line"] = cs
            out["plans"] = frappe.db.sql("""
                SELECT name, from_date, to_date, quantity, total_cost, workflow_state,
                       requested_by, block_section, creation
                FROM `tabWork Management Planner`
                WHERE task = %(t)s AND farm = %(f)s
                  AND IFNULL(workflow_state,'') != 'Rejected'
                  AND from_date <= %(pto)s AND to_date >= %(pfrom)s
                ORDER BY creation
            """, {"t": cs.task, "f": cs_mp.farm,
                  "pfrom": cs_mp.period_from, "pto": cs_mp.period_to}, as_dict=True)
            out["stale_drafts"] = [p.name for p in out["plans"] if p.workflow_state == "Draft"]

    else:
        out["error"] = "unknown action: " + str(action)

    return out
