# Ported from Kaitet live Server Script "wm_payroll" (API) — logic unchanged.
# Farms / projects / company / approver roles now come from Work Management Settings
# (falls back to the original Kaitet defaults) — see upande_work_management/api/config.py.
# REGENERATED by kaitet-work-management/port_app.py — edit the mirror script, not this file.

import frappe

from upande_work_management.api.config import get_config


@frappe.whitelist()
def wm_payroll(**kwargs):
    _cfg = get_config()
    FARM_PROJECT = _cfg["farm_project"]
    DEFAULT_COMPANY = _cfg["default_company"]
    FARMS = _cfg["farms"]
    BLOCK_EXCLUDE = _cfg["block_exclude"]
    FARM_APPROVER_ROLE = _cfg["farm_approver_role"]

    # ==================================================================
    # SERVER SCRIPT — "WM Payroll" (API, api_method=wm_payroll)
    #
    # Work Management Payment -> ERPNext payroll.
    #
    # A payment document is per worker, so "last working day" is resolved against
    # that worker's own Holiday List — Kaitet employees sit on different weekly
    # offs (w/ Sundays, w/ Thursdays, w/ Fridays ...), so there is no single
    # company-wide working day.
    #
    # Actions:
    #   meta               - configuration and coverage
    #   backfill_fields    - populate payroll_date / amount on existing documents
    #   as_preview         - what Additional Salary would be created for a document
    #
    # No def/return allowed in the sandbox, so everything is inline.
    # ==================================================================
    action = frappe.form_dict.get("action") or "meta"
    out = {}

    # how far back to walk looking for a working day before giving up
    MAX_LOOKBACK = 21

    if action == "meta":
        out["component"] = frappe.db.get_single_value(
            "Work Management Settings", "additional_salary_component")
        out["payments"] = frappe.db.count("Work Management Payment")
        out["with_payroll_date"] = frappe.db.count(
            "Work Management Payment", {"payroll_date": ["is", "set"]})
        out["with_amount"] = frappe.db.count(
            "Work Management Payment", {"amount": [">", 0]})
        out["states"] = frappe.db.sql("""
            SELECT workflow_state st, COUNT(*) n FROM `tabWork Management Payment`
            GROUP BY workflow_state ORDER BY n DESC
        """, as_dict=True)
        out["additional_salaries"] = frappe.db.count(
            "Additional Salary", {"ref_doctype": "Work Management Payment"})

    elif action == "backfill_fields":
        # payroll_date = last working day of the work period for THIS worker.
        # Kept for re-running after a bulk import; amount is set at creation time.
        bf_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        bf_limit = frappe.utils.cint(frappe.form_dict.get("limit") or 1000)
        rows = frappe.db.sql("""
            SELECT name, employee, period_from, period_to, payroll_date, amount
            FROM `tabWork Management Payment`
            WHERE IFNULL(payroll_date,'') = ''
            ORDER BY creation
            LIMIT %(lim)s
        """, {"lim": bf_limit}, as_dict=True)

        # holiday lists for every employee involved, fetched once
        emps = []
        for r in rows:
            if r.employee and r.employee not in emps:
                emps.append(r.employee)
        hl_by_emp = {}
        if emps:
            for e in frappe.db.sql("""
                SELECT name, holiday_list FROM `tabEmployee` WHERE name IN %(e)s
            """, {"e": tuple(emps)}, as_dict=True):
                hl_by_emp[e.name] = e.holiday_list
        hol_cache = {}

        done = []
        no_period = 0
        for r in rows:
            anchor = r.period_to
            if not anchor:
                no_period = no_period + 1
                continue
            hl = hl_by_emp.get(r.employee)
            payroll = anchor
            if hl:
                key = str(hl)
                if key not in hol_cache:
                    hset = {}
                    for h in frappe.db.sql("""
                        SELECT holiday_date d FROM `tabHoliday` WHERE parent = %(p)s
                    """, {"p": hl}, as_dict=True):
                        hset[str(h.d)] = 1
                    hol_cache[key] = hset
                hset = hol_cache[key]
                step = 0
                while step < MAX_LOOKBACK:
                    cand = frappe.utils.add_days(anchor, -step)
                    if not hset.get(str(cand)):
                        payroll = cand
                        break
                    step = step + 1
            entry = {"name": r.name, "employee": r.employee,
                     "period_to": str(anchor), "payroll_date": str(payroll),
                     "amount": frappe.utils.flt(r.amount)}
            done.append(entry)
            if not bf_dry:
                frappe.db.set_value("Work Management Payment", r.name,
                                    "payroll_date", payroll, update_modified=False)
        if not bf_dry:
            frappe.db.commit()
        out["dry_run"] = bf_dry
        out["considered"] = len(rows)
        out["updated"] = len(done)
        out["no_period_to"] = no_period
        out["moved_off_period_end"] = len([d for d in done if d["payroll_date"] != d["period_to"]])
        out["sample"] = done[:15]

    elif action == "migrate_state":
        # Workflow State masters cannot be renamed in Frappe, so the move from
        # "Pending Accounts" to "Unpaid" is a create-new + repoint.
        ms_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        ms_from = frappe.form_dict.get("old") or "Pending Accounts"
        ms_to = frappe.form_dict.get("new") or "Unpaid"
        ms_rows = frappe.db.sql("""
            SELECT name FROM `tabWork Management Payment` WHERE workflow_state = %(s)s
        """, {"s": ms_from}, as_dict=True)
        if not ms_dry:
            for m in ms_rows:
                frappe.db.set_value("Work Management Payment", m.name,
                                    "workflow_state", ms_to, update_modified=False)
            frappe.db.commit()
        out["dry_run"] = ms_dry
        out["from_state"] = ms_from
        out["to_state"] = ms_to
        out["documents"] = len(ms_rows)

    elif action == "as_preview":
        ap_name = frappe.form_dict.get("name")
        if not ap_name:
            out["error"] = "name is required"
        else:
            p = frappe.db.get_value("Work Management Payment", ap_name,
                ["name", "employee", "employee_name", "company", "amount",
                 "payroll_date", "period_from", "period_to",
                 "workflow_state"], as_dict=True)
            if not p:
                out["error"] = "no such payment: " + str(ap_name)
            else:
                out["payment"] = p
                out["component"] = frappe.db.get_single_value(
                    "Work Management Settings", "additional_salary_component")
                out["existing"] = frappe.db.get_all("Additional Salary",
                    filters={"ref_doctype": "Work Management Payment", "ref_docname": ap_name},
                    fields=["name", "docstatus", "amount", "payroll_date", "salary_component"])

    else:
        out["error"] = "unknown action: " + str(action)

    return out
