# Ported from Kaitet live Server Script "wm_payroll" (API) — logic unchanged.
# Farms / projects / company / approver roles now come from Work Management Settings
# (falls back to the original Kaitet defaults) — see upande_work_management/api/config.py.
# REGENERATED by kaitet-work-management/port_app.py — edit the mirror script, not this file.

import frappe

from upande_work_management.api.config import get_config


@frappe.whitelist()
def wm_payroll(**kwargs):
    _cfg = get_config()
    FARM_PROJECT = _cfg["farm_project"]
    DEFAULT_COMPANY = _cfg["default_company"]
    FARMS = _cfg["farms"]
    BLOCK_EXCLUDE = _cfg["block_exclude"]
    FARM_APPROVER_ROLE = _cfg["farm_approver_role"]

    # ==================================================================
    # SERVER SCRIPT — "WM Payroll" (API, api_method=wm_payroll)
    #
    # Work Management Payment -> ERPNext payroll.
    #
    # A payment document is per worker, so "last working day" is resolved against
    # that worker's own Holiday List — Kaitet employees sit on different weekly
    # offs (w/ Sundays, w/ Thursdays, w/ Fridays ...), so there is no single
    # company-wide working day.
    #
    # Actions:
    #   meta               - configuration and coverage
    #   backfill_fields    - populate payroll_date / amount on existing documents
    #   as_preview         - what Additional Salary would be created for a document
    #
    # No def/return allowed in the sandbox, so everything is inline.
    # ==================================================================
    action = frappe.form_dict.get("action") or "meta"
    out = {}

    # how far back to walk looking for a working day before giving up
    MAX_LOOKBACK = 21

    if action == "meta":
        out["component"] = frappe.db.get_single_value(
            "Work Management Settings", "salary_component")
        out["payments"] = frappe.db.count("Work Management Payment")
        out["with_payroll_date"] = frappe.db.count(
            "Work Management Payment", {"payroll_date": ["is", "set"]})
        out["with_amount"] = frappe.db.count(
            "Work Management Payment", {"amount": [">", 0]})
        out["states"] = frappe.db.sql("""
            SELECT workflow_state st, COUNT(*) n FROM `tabWork Management Payment`
            GROUP BY workflow_state ORDER BY n DESC
        """, as_dict=True)
        out["additional_salaries"] = frappe.db.count(
            "Additional Salary", {"ref_doctype": "Work Management Payment"})

    elif action == "backfill_fields":
        # payroll_date = the day the pay week closes, which IS the pay day. Periods
        # are pay weeks, so that is simply period_to. Kept as an action so a bulk
        # import or a change of pay day can be re-applied.
        bf_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        bf_force = frappe.utils.cint(frappe.form_dict.get("force"))
        bf_limit = frappe.utils.cint(frappe.form_dict.get("limit") or 5000)
        bf_cond = "" if bf_force else " AND IFNULL(p.payroll_date,'') = ''"
        rows = frappe.db.sql("""
            SELECT p.name, p.period_from, p.period_to, p.payroll_date
            FROM `tabWork Management Payment` p
            WHERE IFNULL(p.period_to,'') != ''""" + bf_cond + """
            ORDER BY p.creation
            LIMIT %(lim)s
        """, {"lim": bf_limit}, as_dict=True)
        done = []
        for r in rows:
            want = str(r.period_to)[:10]
            if str(r.payroll_date or "")[:10] == want:
                continue
            done.append({"name": r.name, "was": str(r.payroll_date or ""), "now": want})
            if not bf_dry:
                frappe.db.set_value("Work Management Payment", r.name,
                                    "payroll_date", want, update_modified=False)
        if not bf_dry:
            frappe.db.commit()
        out["dry_run"] = bf_dry
        out["considered"] = len(rows)
        out["changed"] = len(done)
        out["sample"] = done[:12]

    elif action == "migrate_state":
        # Workflow State masters cannot be renamed in Frappe, so the move from
        # "Pending Accounts" to "Unpaid" is a create-new + repoint.
        ms_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        ms_from = frappe.form_dict.get("old") or "Pending Accounts"
        ms_to = frappe.form_dict.get("new") or "Unpaid"
        ms_rows = frappe.db.sql("""
            SELECT name FROM `tabWork Management Payment` WHERE workflow_state = %(s)s
        """, {"s": ms_from}, as_dict=True)
        if not ms_dry:
            for m in ms_rows:
                frappe.db.set_value("Work Management Payment", m.name,
                                    "workflow_state", ms_to, update_modified=False)
            frappe.db.commit()
        out["dry_run"] = ms_dry
        out["from_state"] = ms_from
        out["to_state"] = ms_to
        out["documents"] = len(ms_rows)

    elif action == "as_preview":
        ap_name = frappe.form_dict.get("name")
        if not ap_name:
            out["error"] = "name is required"
        else:
            p = frappe.db.get_value("Work Management Payment", ap_name,
                ["name", "employee", "employee_name", "company", "amount",
                 "payroll_date", "period_from", "period_to",
                 "workflow_state"], as_dict=True)
            if not p:
                out["error"] = "no such payment: " + str(ap_name)
            else:
                out["payment"] = p
                out["component"] = frappe.db.get_single_value(
                    "Work Management Settings", "salary_component")
                out["existing"] = frappe.db.get_all("Additional Salary",
                    filters={"ref_doctype": "Work Management Payment", "ref_docname": ap_name},
                    fields=["name", "docstatus", "amount", "payroll_date", "salary_component"])

    else:
        out["error"] = "unknown action: " + str(action)

    return out
