# Ported from Kaitet live Server Script "wm_planner" (API) — logic unchanged.
# Farms / projects / company / approver roles now come from Work Management Settings
# (falls back to the original Kaitet defaults) — see upande_work_management/api/config.py.
# REGENERATED by kaitet-work-management/port_app.py — edit the mirror script, not this file.

import json

import frappe

from upande_work_management.api.config import get_config


@frappe.whitelist()
def wm_planner(**kwargs):
    _cfg = get_config()
    FARM_PROJECT = _cfg["farm_project"]
    DEFAULT_COMPANY = _cfg["default_company"]
    FARMS = _cfg["farms"]
    BLOCK_EXCLUDE = _cfg["block_exclude"]
    FARM_APPROVER_ROLE = _cfg["farm_approver_role"]

    # ==================================================================
    # SERVER SCRIPT — "WM Planner" (API, api_method=wm_planner)
    # Powers: Planner + Assigner (a_) + Actuals (act_) + Payment (pay_) + dash
    # Multi-block planner (Option A) + fast grouped-query dashboard.
    # ==================================================================

    # Hours model: Mon-Fri = 8h, Sat = 6h, Sun counts as a workday = 8h.
    # (No def/return allowed at module top-level in the sandbox, so hours are computed inline
    #  wherever needed using frappe.utils.getdate(d).weekday(): Mon=0 .. Sun=6.)
    WEEKDAY_HOURS = 8
    SATURDAY_HOURS = 6
    SUNDAY_HOURS = 8

    # WHO MAY DECIDE A PLAN. Approving and rejecting were gated only by the desk
    # workflow and by what the pending list chose to show -- the endpoint itself
    # checked nothing, so anyone who could reach it could approve any farm's plan.
    # This is the same signal `pending` scopes on, so what a person can DO now
    # matches what they can SEE: a farm-specific role decides that farm, while the
    # GM, the HR head and System Manager decide anywhere.
    ap_roles = frappe.db.get_all("Has Role", filters={"parent": frappe.session.user}, pluck="role")
    AP_BYPASS = 1 if (("System Manager" in ap_roles) or ("General Manager" in ap_roles)
                      or ("HOD HR" in ap_roles) or ("HR Manager Kaitet" in ap_roles)
                      or frappe.session.user == "Administrator") else 0
    AP_FARMS = []
    if "Farm Manager Saboti" in ap_roles:
        AP_FARMS.append("Saboti")
    if "Farm Manager Lokitela" in ap_roles:
        AP_FARMS.append("Lokitela")
    if "Farm Manager Endebess" in ap_roles:
        AP_FARMS.append("Endebess")
    if "Farm Manager Valle" in ap_roles:
        AP_FARMS.append("Vale")

    action = frappe.form_dict.get("action") or "meta"
    out = {}

    # ===== PLANNER =====
    if action == "meta":
        out["farms"] = FARMS
        out["company"] = DEFAULT_COMPANY

    elif action == "blocks":
        farm = frappe.form_dict.get("farm")
        # Every location on the farm. A keyword list used to hide anything whose name
        # contained Store, Mill, Tank, BIN, Warehouse, Cold Room, Parchment or Diesel,
        # on the assumption that only field blocks get planned. That hid 41 real places
        # across the four farms -- General Store Avocado Packhouse among them -- and the
        # tasks people actually plan there (Cleaners, Store Clerk, Security, Gardener)
        # exist in the task list. Nothing had ever been recorded at them because the
        # planner would not offer them, not because no work happens there.
        rows = frappe.db.get_all("Warehouse", filters={"custom_farm":farm,"is_group":0,"disabled":0},
            fields=["name","warehouse_name","custom_area_ha"], order_by="name", limit=500)
        blocks = []
        for r in rows:
            nm = r.warehouse_name or r.name
            blocks.append({"name":r.name,"label":nm.replace(" - KL",""),
                           "area":frappe.utils.flt(r.custom_area_ha)})
        out["blocks"] = blocks

    elif action == "tasks":
        # Only what the approved master plan allows. Before this, every non-group
        # Task on the farm's project was offered -- with no ceiling on quantity or cost.
        farm = frappe.form_dict.get("farm")
        tk_from = frappe.form_dict.get("from_date") or frappe.utils.today()
        tk_to = frappe.form_dict.get("to_date") or tk_from
        tk_mp = frappe.db.sql("""
            SELECT name, period_from, period_to FROM `tabWork Management Master Plan`
            WHERE farm = %(f)s AND workflow_state = 'Approved'
              AND period_from <= %(from)s AND period_to >= %(to)s
            ORDER BY period_from DESC LIMIT 1
        """, {"f": farm, "from": tk_from, "to": tk_to}, as_dict=True)
        tasks = []
        if not tk_mp:
            out["master_plan"] = None
            # "the planner has gone" is what this looks like from the outside, so say what
            # is actually holding it up: the farm's own plan and where it has got to,
            # rather than only that nothing is approved
            tk_any = frappe.db.sql("""
                SELECT name, workflow_state, period_from, period_to
                FROM `tabWork Management Master Plan`
                WHERE farm = %(f)s AND period_from <= %(to)s AND period_to >= %(from)s
                ORDER BY FIELD(workflow_state,'Approved','Pending GM','Pending Consultant','Draft','Rejected'),
                         period_from DESC
                LIMIT 1
            """, {"f": farm, "from": tk_from, "to": tk_to}, as_dict=True)
            # a plan the request only PARTLY sits inside is the commonest way to land
            # here -- a budget running Mon-Sat against a Mon-Sun week -- and saying
            # "no approved master plan" about a plan that is plainly approved reads as
            # the system losing it. Name the period and what to do instead.
            tk_a = tk_any[0] if tk_any else None
            if tk_a and tk_a.workflow_state == "Approved":
                tk_why = ("This request runs " + str(tk_from) + " to " + str(tk_to) + ", but " +
                          tk_a.name + " budgets " + str(farm) + " only from " +
                          str(tk_a.period_from) + " to " + str(tk_a.period_to) + ". Plan within "
                          "those dates, or widen the master plan's period to cover them.")
                out["partial_plan"] = tk_a.name
                out["partial_from"] = str(tk_a.period_from)
                out["partial_to"] = str(tk_a.period_to)
            elif tk_a and tk_a.workflow_state == "Rejected":
                tk_why = ("No approved master plan covers " + str(tk_from) + " to " + str(tk_to) +
                          " for " + str(farm) + ". " + tk_a.name + " was rejected. Edit it and "
                          "submit it again, or raise a new one, then have it approved.")
            elif tk_a:
                tk_why = ("No approved master plan covers " + str(tk_from) + " to " + str(tk_to) +
                          " for " + str(farm) + ". " + tk_a.name + " covers these dates but is "
                          "still at " + str(tk_a.workflow_state) + ". Planning opens once it is approved.")
            else:
                tk_why = ("No approved master plan covers " + str(tk_from) + " to " + str(tk_to) +
                          " for " + str(farm) + ". Raise a master plan for this period and have "
                          "it approved.")
            if tk_a:
                out["pending_plan"] = tk_a.name
                out["pending_plan_state"] = tk_a.workflow_state
            out["blocked_reason"] = tk_why
        else:
            tkm = tk_mp[0]
            out["master_plan"] = tkm.name
            # the period the budget actually covers, so the screen can offer to snap the
            # request's dates to it rather than letting someone plan past the ceiling
            out["period_from"] = str(tkm.period_from)
            out["period_to"] = str(tkm.period_to)
            out["blocked_reason"] = None
            for ta in frappe.db.get_all("Work Management Master Plan Activity",
                    filters={"parent": tkm.name, "consultant_state": "OK"},
                    fields=["name", "task", "uom", "rate", "work_qty", "cost"], order_by="idx"):
                tk_used = frappe.db.sql("""
                    SELECT COALESCE(SUM(quantity),0) q, COALESCE(SUM(total_cost),0) c
                    FROM `tabWork Management Planner`
                    WHERE task = %(t)s AND farm = %(f)s
                      AND IFNULL(workflow_state,'') != 'Rejected'
                      AND from_date <= %(pto)s AND to_date >= %(pfrom)s
                """, {"t": ta.task, "f": farm,
                      "pfrom": tkm.period_from, "pto": tkm.period_to}, as_dict=True)[0]
                tk_rq = frappe.utils.flt(ta.work_qty) - frappe.utils.flt(tk_used.q)
                tk_rc = frappe.utils.flt(ta.cost) - frappe.utils.flt(tk_used.c)
                ti = frappe.db.get_value("Task", ta.task,
                    ["subject", "custom_uom", "custom_daily_target", "custom_rate"], as_dict=True)
                tasks.append({"name": ta.task, "subject": (ti.subject if ti else ta.task),
                              "uom": ta.uom or (ti.custom_uom if ti else None),
                              "daily_target": frappe.utils.flt(ti.custom_daily_target) if ti else 0,
                              "rate": frappe.utils.flt(ti.custom_rate) if ti else 0,
                              "budget_rate": frappe.utils.flt(ta.rate, 6),
                              "work_qty": frappe.utils.flt(ta.work_qty),
                              "budget_cost": frappe.utils.flt(ta.cost),
                              "remaining_qty": tk_rq, "remaining_cost": tk_rc,
                              "exhausted": 1 if (tk_rq <= 0.005 or tk_rc <= 0.005) else 0})
        out["tasks"] = tasks

    elif action == "budgets":
        # Every approved master plan for a farm, so the planner can offer the periods
        # that may actually be planned instead of the person guessing a date range and
        # discovering afterwards that no budget covers it.
        bg_farm = frappe.form_dict.get("farm")
        if not bg_farm:
            out["budgets"] = []
        else:
            out["budgets"] = frappe.db.sql("""
                SELECT mp.name, mp.period_from, mp.period_to, mp.total_cost,
                       (SELECT COUNT(*) FROM `tabWork Management Master Plan Activity` a
                         WHERE a.parent = mp.name AND a.consultant_state = 'OK') activities
                FROM `tabWork Management Master Plan` mp
                WHERE mp.farm = %(f)s AND mp.workflow_state = 'Approved'
                ORDER BY mp.period_from DESC
            """, {"f": bg_farm}, as_dict=True)
            for bg in out["budgets"]:
                bg["period_from"] = str(bg["period_from"])
                bg["period_to"] = str(bg["period_to"])

    elif action == "compare":
        rows = frappe.db.get_all("Work Management Planner",
            filters={"farm":frappe.form_dict.get("farm"),"block_section":frappe.form_dict.get("block"),
                     "task":frappe.form_dict.get("task"),"workflow_state":"Approved"},
            fields=["name","quantity","people_per_day","person_days","total_cost","from_date","to_date","approval_date"],
            order_by="approval_date desc", limit=1)
        out["last"] = rows[0] if rows else None

    elif action == "pending":
        # FARM SCOPING: a farm manager only sees plans awaiting approval for their own farm(s).
        # GM / System Manager / HR see all. Uses farm-specific roles (same signal as Assigner/Actuals).
        pflt = {"workflow_state": "Pending Approval"}
        prl = frappe.db.get_all("Has Role", filters={"parent": frappe.session.user}, pluck="role")
        pbypass = ("System Manager" in prl) or ("General Manager" in prl) or ("HOD HR" in prl) or ("HR Manager Kaitet" in prl) or (frappe.session.user == "Administrator")
        if not pbypass:
            pallowed = []
            for _farm_, _role_ in FARM_APPROVER_ROLE.items():
                if _role_ in prl: pallowed.append(_farm_)
            pflt["farm"] = ["in", pallowed] if pallowed else ["in", ["__none__"]]
        out["pending"] = frappe.db.get_all("Work Management Planner",
            filters=pflt,
            fields=["name","farm","block_section","task","quantity","people_per_day","person_days",
                    "total_hours","total_cost","from_date","to_date","requested_by","request_date",
                    "workflow_state","uom","daily_target","rate","working_days"],
            order_by="request_date desc", limit=200)

        # WHAT APPROVING THIS LEAVES. An approver could see the request but not the
        # ceiling it draws on, so "is there room for this?" was unanswerable without
        # opening the master plan in another tab. Remaining here already counts this
        # request -- Pending Approval holds budget the same way Approved does -- so
        # these figures read as "with this request counted", and rejecting returns them.
        pb_plan = {}   # farm|from|to -> the approved plan covering it, or None
        pb_act = {}    # plan -> task -> the budget line
        pb_use = {}    # plan -> task -> what every live request has drawn
        for pr in out["pending"]:
            pb_key = str(pr.get("farm")) + "|" + str(pr.get("from_date")) + "|" + str(pr.get("to_date"))
            if pb_key not in pb_plan:
                pb_hit = frappe.db.sql("""
                    SELECT name, period_from, period_to FROM `tabWork Management Master Plan`
                    WHERE farm = %(f)s AND workflow_state = 'Approved'
                      AND period_from <= %(a)s AND period_to >= %(b)s
                    ORDER BY period_from DESC LIMIT 1
                """, {"f": pr.get("farm"), "a": pr.get("from_date"), "b": pr.get("to_date")},
                    as_dict=True)
                pb_plan[pb_key] = pb_hit[0] if pb_hit else None
            pb_mp = pb_plan[pb_key]
            pr["budget_plan"] = pb_mp.name if pb_mp else None
            if not pb_mp:
                continue
            if pb_mp.name not in pb_act:
                pb_rows = {}
                for pb_a in frappe.db.get_all("Work Management Master Plan Activity",
                        filters={"parent": pb_mp.name, "consultant_state": "OK"},
                        fields=["task", "uom", "work_qty", "cost"]):
                    pb_rows[pb_a.task] = pb_a
                pb_act[pb_mp.name] = pb_rows
                pb_seen = {}
                for pb_u in frappe.db.sql("""
                    SELECT task, COALESCE(SUM(quantity),0) q, COALESCE(SUM(total_cost),0) c
                    FROM `tabWork Management Planner`
                    WHERE farm = %(f)s AND IFNULL(workflow_state,'') != 'Rejected'
                      AND from_date <= %(pto)s AND to_date >= %(pfrom)s
                    GROUP BY task
                """, {"f": pr.get("farm"), "pfrom": pb_mp.period_from, "pto": pb_mp.period_to},
                    as_dict=True):
                    pb_seen[pb_u.task] = pb_u
                pb_use[pb_mp.name] = pb_seen
            pb_line = pb_act[pb_mp.name].get(pr.get("task"))
            if not pb_line:
                continue
            pb_drawn = pb_use[pb_mp.name].get(pr.get("task"))
            pb_dq = frappe.utils.flt(pb_drawn.q) if pb_drawn else 0
            pb_dc = frappe.utils.flt(pb_drawn.c) if pb_drawn else 0
            pr["budget_uom"] = pb_line.uom
            pr["budget_qty"] = frappe.utils.flt(pb_line.work_qty)
            pr["budget_cost"] = frappe.utils.flt(pb_line.cost, 2)
            pr["budget_remaining_qty"] = frappe.utils.flt(pb_line.work_qty) - pb_dq
            pr["budget_remaining_cost"] = frappe.utils.flt(frappe.utils.flt(pb_line.cost) - pb_dc, 2)

    elif action == "my_requests":
        out["requests"] = frappe.db.get_all("Work Management Planner",
            filters={"requested_by":frappe.session.user},
            fields=["name","farm","block_section","task","quantity","people_per_day","person_days",
                    "total_hours","total_cost","from_date","to_date","workflow_state","request_date",
                    "approved_by","approval_date","uom","daily_target","rate","working_days"],
            order_by="creation desc", limit=200)

    elif action == "planner_blocks":
        # full block list for one planner (primary + extras)
        nm = frappe.form_dict.get("planner")
        primary = frappe.db.get_value("Work Management Planner", nm, "block_section")
        blist = []
        if primary:
            blist.append(primary)
        for r in frappe.db.get_all("Work Planner Block", filters={"parent":nm},
                fields=["block"], order_by="idx"):
            if r.block:
                blist.append(r.block)
        out["blocks"] = blist

    elif action == "decide_scope":
        out["can_decide_any"] = AP_BYPASS
        out["farms"] = AP_FARMS

    elif action == "roles":
        roles = frappe.db.get_all("Has Role", filters={"parent":frappe.session.user}, fields=["role"])
        rl = []
        for r in roles:
            rl.append(r.role)
        is_fm = False
        for r in rl:
            if r.startswith("Farm Manager"):
                is_fm = True
        out["user"] = frappe.session.user
        out["is_section_head"] = ("Production Section Head" in rl) or is_fm
        out["is_approver"] = is_fm

    elif action == "submit":
        farm = frappe.form_dict.get("farm")
        block = frappe.form_dict.get("block")
        blocks_raw = frappe.form_dict.get("blocks")
        task = frappe.form_dict.get("task"); qty = frappe.utils.flt(frappe.form_dict.get("quantity"))
        from_date = frappe.form_dict.get("from_date"); to_date = frappe.form_dict.get("to_date")
        submit_now = frappe.form_dict.get("submit_now")
        plan_name = frappe.form_dict.get("plan")  # if editing an existing draft
        block_list = []
        if blocks_raw:
            for b in blocks_raw.split(","):
                bv = b.strip()
                if bv and bv not in block_list:
                    block_list.append(bv)
        elif block:
            block_list.append(block)
        primary = block_list[0] if block_list else None
        err = None
        if farm not in FARMS: err = "Invalid farm"
        if not primary: err = "At least one block is required"
        if not task: err = "Task is required"
        if qty <= 0: err = "Quantity must be greater than zero"
        if not from_date or not to_date: err = "Date range is required"
        if err:
            out["error"] = err
        else:
            wd = frappe.utils.date_diff(to_date, from_date) + 1
            if wd < 1: wd = 0
            # Resolve once, before the cap runs, whether this submit will edit plan_name
            # in place or clone it -- the same state test the write path applies further
            # down. Both the cap's committed-sum exclusion and the write path use this
            # one resolved value, so they can never disagree about which document this is.
            plan_editing = 0
            if plan_name and frappe.db.exists("Work Management Planner", plan_name):
                plan_state = frappe.db.get_value("Work Management Planner", plan_name, "workflow_state")
                if plan_state in ("Draft", "Rejected", "Pending Approval"):
                    plan_editing = 1
            cap_me = plan_name if plan_editing else ""
            # ---- MASTER PLAN CAP ------------------------------------------------
            # A plan may only be raised for an activity the approved master plan
            # allows, and only up to its budgeted quantity and cost. Mirrors
            # check_plan_allowed() in upande_work_management/master_plan.py.
            cap_mp = frappe.db.sql("""
                SELECT name, period_from, period_to FROM `tabWork Management Master Plan`
                WHERE farm = %(f)s AND workflow_state = 'Approved'
                  AND period_from <= %(from)s AND period_to >= %(to)s
                ORDER BY period_from DESC LIMIT 1
            """, {"f": farm, "from": from_date, "to": to_date}, as_dict=True)
            cap_err = None
            cap_line = None
            if not cap_mp:
                cap_err = ("No approved master plan covers " + str(from_date) + " to " +
                           str(to_date) + " for " + str(farm) +
                           ". A master plan must be approved before work can be planned.")
            else:
                cm = cap_mp[0]
                cap_rows = frappe.db.sql("""
                    SELECT name, work_qty, cost FROM `tabWork Management Master Plan Activity`
                    WHERE parent = %(p)s AND task = %(t)s AND consultant_state = 'OK'
                    LIMIT 1
                """, {"p": cm.name, "t": task}, as_dict=True)
                if not cap_rows:
                    cap_err = (str(task) + " is not an approved activity on master plan " +
                               cm.name + " (" + str(cm.period_from) + " to " + str(cm.period_to) + ").")
                else:
                    cap_line = cap_rows[0]
                    cap_used = frappe.db.sql("""
                        SELECT COALESCE(SUM(quantity),0) q, COALESCE(SUM(total_cost),0) c
                        FROM `tabWork Management Planner`
                        WHERE task = %(t)s AND farm = %(f)s
                          AND IFNULL(workflow_state,'') != 'Rejected'
                          AND name != %(me)s
                          AND from_date <= %(pto)s AND to_date >= %(pfrom)s
                    """, {"t": task, "f": farm, "me": cap_me,
                          "pfrom": cm.period_from, "pto": cm.period_to}, as_dict=True)[0]
                    cap_rq = frappe.utils.flt(cap_line.work_qty) - frappe.utils.flt(cap_used.q)
                    cap_rc = frappe.utils.flt(cap_line.cost) - frappe.utils.flt(cap_used.c)
                    # report (and compare against) the true remaining figure, negative
                    # when the line is already over-consumed -- clamping to 0 would make
                    # a genuine overrun look like an exact fit, and would disagree with
                    # what headroom() reports for the same line at the same moment.
                    cap_tinfo = frappe.db.get_value("Task", task,
                        ["custom_daily_target", "custom_rate"], as_dict=True)
                    cap_rate = frappe.utils.flt(cap_tinfo.custom_rate) if cap_tinfo else 0
                    # identical arithmetic to d.total_cost = qty * rate below -- the cap
                    # must check the same figure the document is saved with, unrounded.
                    cap_cost = qty * cap_rate
                    if qty > cap_rq + 0.005:
                        cap_err = ("Over the budgeted quantity for " + str(task) + ": " +
                                   str(round(cap_rq, 2)) + " left of " +
                                   str(frappe.utils.flt(cap_line.work_qty)) +
                                   ", this plan asks for " + str(qty) + ".")
                    elif cap_cost > cap_rc + 0.005:
                        cap_err = ("Over the budgeted cost for " + str(task) + ": KES " +
                                   str(round(cap_rc, 2)) + " left of " +
                                   str(frappe.utils.flt(cap_line.cost)) +
                                   ", this plan costs " + str(round(cap_cost, 2)) + ".")
            if cap_err:
                out["error"] = cap_err
            else:
                out["master_plan"] = cap_mp[0].name
                tinfo = frappe.db.get_value("Task", task, ["custom_daily_target","custom_rate","custom_uom"], as_dict=True)
                tgt = frappe.utils.flt(tinfo.custom_daily_target) if tinfo else 0
                rate = frappe.utils.flt(tinfo.custom_rate) if tinfo else 0
                uom = tinfo.custom_uom if tinfo else None
                ppd = 0
                if tgt > 0 and wd > 0:
                    raw = qty / tgt / wd
                    ppd = int(raw)
                    if ppd < raw: ppd = ppd + 1
                editing = plan_editing
                if editing:
                    d = frappe.get_doc("Work Management Planner", plan_name)
                    d.set("extra_blocks", [])   # rebuild blocks from the new selection
                else:
                    d = frappe.new_doc("Work Management Planner")
                d.farm = farm; d.company = DEFAULT_COMPANY; d.block_section = primary
                i = 0
                for b in block_list:
                    if i > 0:
                        row = d.append("extra_blocks", {}); row.block = b
                    i = i + 1
                d.task = task; d.uom = uom; d.daily_target = tgt; d.rate = rate
                d.task_kpi = str(tgt) + " " + (uom or "") + "/day @ KES " + str(rate)
                d.from_date = from_date; d.to_date = to_date; d.working_days = wd
                # total hours across the period: Mon-Fri=8, Sat=6, Sun=8
                th = 0
                cursor = frappe.utils.getdate(from_date)
                endd = frappe.utils.getdate(to_date)
                guard = 0
                while cursor <= endd and guard < 400:
                    wdi = cursor.weekday()  # Mon=0 .. Sun=6
                    if wdi == 5:
                        th = th + SATURDAY_HOURS
                    else:
                        th = th + WEEKDAY_HOURS
                    cursor = frappe.utils.add_days(cursor, 1)
                    guard = guard + 1
                # man-days are the labour the QUANTITY represents: quantity / daily target.
                # Deriving them from the rounded crew instead (ppd * wd) inflated them --
                # 1000 units at 100/day over 3 days is 10 man-days, not the 12 a crew of
                # 4 implies. The crew still rounds up, because people come whole.
                d.quantity = qty
                d.people_per_day = ppd
                d.person_days = frappe.utils.flt(qty / tgt, 2) if tgt > 0 else (ppd * wd)
                d.total_hours = th
                d.total_cost = qty * rate
                if not editing:
                    d.requested_by = frappe.session.user; d.request_date = frappe.utils.today()
                if editing:
                    # keep it a draft unless they explicitly submit; reset a Rejected back to Draft on save
                    if not submit_now:
                        d.workflow_state = "Draft"
                    d.save(ignore_permissions=True)
                else:
                    d.insert(ignore_permissions=True)
                if submit_now:
                    d.workflow_state = "Pending Approval"; d.save(ignore_permissions=True)
                out["name"] = d.name; out["workflow_state"] = d.workflow_state
                out["total_cost"] = d.total_cost; out["people_per_day"] = d.people_per_day
                out["blocks"] = block_list
                out["editing"] = editing

    elif action == "approve":
        nm = frappe.form_dict.get("name")
        ap_doc = frappe.db.get_value("Work Management Planner", nm,
            ["workflow_state", "farm"], as_dict=True)
        cur_ws = ap_doc.workflow_state if ap_doc else None
        if not ap_doc:
            out["error"] = "no such plan: " + str(nm)
        elif not AP_BYPASS and ap_doc.farm not in AP_FARMS:
            out["error"] = ("You cannot approve plans for " + str(ap_doc.farm) +
                            ". A farm manager decides their own farm; the general manager "
                            "and the HR head decide any farm.")
        elif cur_ws != "Pending Approval":
            out["error"] = "Not awaiting approval (state: " + str(cur_ws) + ")"
        else:
            frappe.db.set_value("Work Management Planner", nm, "workflow_state", "Approved", update_modified=False)
            frappe.db.set_value("Work Management Planner", nm, "docstatus", 1, update_modified=False)
            frappe.db.set_value("Work Management Planner", nm, "approved_by", frappe.session.user, update_modified=False)
            frappe.db.set_value("Work Management Planner", nm, "approval_date", frappe.utils.today(), update_modified=False)
            out["name"] = nm; out["workflow_state"] = "Approved"

    elif action == "reject":
        nm = frappe.form_dict.get("name")
        rj_doc = frappe.db.get_value("Work Management Planner", nm,
            ["workflow_state", "farm"], as_dict=True)
        cur_ws = rj_doc.workflow_state if rj_doc else None
        if not rj_doc:
            out["error"] = "no such plan: " + str(nm)
        elif not AP_BYPASS and rj_doc.farm not in AP_FARMS:
            out["error"] = ("You cannot reject plans for " + str(rj_doc.farm) +
                            ". A farm manager decides their own farm; the general manager "
                            "and the HR head decide any farm.")
        elif cur_ws != "Pending Approval":
            out["error"] = "Not awaiting approval (state: " + str(cur_ws) + ")"
        else:
            frappe.db.set_value("Work Management Planner", nm, "workflow_state", "Rejected", update_modified=False)
            frappe.db.set_value("Work Management Planner", nm, "approved_by", None, update_modified=False)
            frappe.db.set_value("Work Management Planner", nm, "approval_date", None, update_modified=False)
            out["name"] = nm; out["workflow_state"] = "Rejected"

    # ===== ASSIGNER (a_) =====
    elif action == "plan_detail":
        nm = frappe.form_dict.get("plan")
        p = frappe.db.get_value("Work Management Planner", nm,
            ["name","farm","block_section","task","quantity","total_cost","from_date","to_date",
             "workflow_state","uom","daily_target","rate"], as_dict=True)
        blist = []
        if p and p.block_section:
            blist.append(p.block_section)
        for r in frappe.db.get_all("Work Planner Block", filters={"parent": nm}, fields=["block"], order_by="idx"):
            if r.block:
                blist.append(r.block)
        if p:
            p["blocks"] = blist
            p["editable"] = 1 if p.workflow_state in ("Draft","Rejected","Pending Approval") else 0
        out["plan"] = p

    elif action == "plan_trace":
        # ONE PLAN, END TO END: who asked for it, who approved it, the crews it was
        # staffed with, the people actually on those crews, what they recorded and
        # what it cost. The weekly board could only show a plan's own row, so there
        # was no way to answer "who approved this and who worked it".
        tr = frappe.form_dict.get("plan")
        pl = frappe.db.get_value("Work Management Planner", tr,
            ["name","farm","block_section","task","quantity","from_date","to_date",
             "workflow_state","uom","daily_target","rate","total_cost","people_per_day",
             "person_days","requested_by","request_date","approved_by","approval_date",
             "fulfilled_qty","remaining_qty","fulfilment_pct","custom_close_state"], as_dict=True)
        if not pl:
            out["error"] = "no such plan: " + str(tr)
        else:
            blist = []
            if pl.block_section:
                blist.append(pl.block_section)
            for b in frappe.db.get_all("Work Planner Block", filters={"parent": tr},
                                       fields=["block"], order_by="idx"):
                if b.block:
                    blist.append(b.block)
            pl["blocks"] = blist
            out["plan"] = pl

            # the approval chain, in the order it actually happens
            chain = []
            chain.append({"step": "Requested", "who": pl.requested_by, "when": str(pl.request_date or "")})
            chain.append({"step": "Farm Manager approved" if pl.approved_by else "Farm Manager approval",
                          "who": pl.approved_by, "when": str(pl.approval_date or "")})
            out["chain"] = chain

            asgs = frappe.db.get_all("Work Management Assigner",
                filters={"planner_request": tr},
                fields=["name","workflow_state","assigned_by","assign_date","approved_by",
                        "approval_date","from_date","to_date","planned_people","assigned_count",
                        "variance","planned_cost"],
                order_by="creation")
            out["assignments"] = asgs
            anames = [a.name for a in asgs]

            # the people put on those crews
            crew = []
            if anames:
                crew = frappe.db.sql("""
                    SELECT we.parent assignment, we.employee, we.employee_name,
                           we.status, we.left_date
                    FROM `tabWork Assignment Employee` we
                    WHERE we.parent IN %(a)s
                    ORDER BY we.employee_name
                """, {"a": tuple(anames)}, as_dict=True)
            out["crew"] = crew

            # what was recorded against those assignments
            acts = []
            worked = []
            if anames:
                acts = frappe.db.sql("""
                    SELECT ac.name, ac.assignment, ac.workflow_state, ac.entered_by,
                           ac.hr_approved_by, ac.gm_approved_by, ac.entry_date,
                           ac.total_actual_qty, ac.total_payment, ac.rate,
                           ac.payroll_people
                    FROM `tabWork Management Actuals` ac
                    WHERE ac.assignment IN %(a)s
                    ORDER BY ac.entry_date
                """, {"a": tuple(anames)}, as_dict=True)
                worked = frappe.db.sql("""
                    SELECT we.employee, we.employee_name,
                           COUNT(DISTINCT we.work_date) days,
                           COALESCE(SUM(we.actual_quantity),0) qty,
                           COALESCE(SUM(we.amount),0) amount,
                           MAX(IFNULL(we.paid,0)) paid,
                           MIN(we.work_date) first_day, MAX(we.work_date) last_day
                    FROM `tabWork Actuals Employee` we
                    INNER JOIN `tabWork Management Actuals` ac ON we.parent = ac.name
                    WHERE ac.assignment IN %(a)s
                    GROUP BY we.employee, we.employee_name
                    ORDER BY COALESCE(SUM(we.amount),0) DESC
                """, {"a": tuple(anames)}, as_dict=True)
            out["actuals"] = acts
            out["workers"] = worked

            act_qty = 0
            act_pay = 0
            for a in acts:
                if a.workflow_state == "CONFIRMED":
                    act_qty = act_qty + frappe.utils.flt(a.total_actual_qty)
                    act_pay = act_pay + frappe.utils.flt(a.total_payment)
            tgt = frappe.utils.flt(pl.quantity)
            bud = frappe.utils.flt(pl.total_cost)
            out["delivery"] = {
                "target": tgt, "actual": act_qty,
                "achieved_pct": (act_qty / tgt * 100) if tgt else 0,
                "planned": bud, "spent": act_pay,
                "of_planned_pct": (act_pay / bud * 100) if bud else 0,
                "crew_planned": frappe.utils.cint(pl.people_per_day),
                "crew_assigned": len(crew),
                "workers_paid": len(worked),
            }

    else:
        out["error"] = "unknown action: " + str(action)

    return out
