# Ported from Kaitet live Server Script "wm_planner" (API) — logic unchanged.
# Farms / projects / company / approver roles now come from Work Management Settings
# (falls back to the original Kaitet defaults) — see upande_work_management/api/config.py.
# REGENERATED by kaitet-work-management/port_app.py — edit the mirror script, not this file.

import frappe

from upande_work_management.api.config import get_config


@frappe.whitelist()
def wm_planner(**kwargs):
    _cfg = get_config()
    FARM_PROJECT = _cfg["farm_project"]
    DEFAULT_COMPANY = _cfg["default_company"]
    FARMS = _cfg["farms"]
    BLOCK_EXCLUDE = _cfg["block_exclude"]
    FARM_APPROVER_ROLE = _cfg["farm_approver_role"]

    # ==================================================================
    # SERVER SCRIPT — "WM Planner" (API, api_method=wm_planner)
    # Powers: Planner + Assigner (a_) + Actuals (act_) + Payment (pay_) + dash
    # Multi-block planner (Option A) + fast grouped-query dashboard.
    # ==================================================================

    # Hours model: Mon-Fri = 8h, Sat = 6h, Sun counts as a workday = 8h.
    # (No def/return allowed at module top-level in the sandbox, so hours are computed inline
    #  wherever needed using frappe.utils.getdate(d).weekday(): Mon=0 .. Sun=6.)
    WEEKDAY_HOURS = 8
    SATURDAY_HOURS = 6
    SUNDAY_HOURS = 8

    action = frappe.form_dict.get("action") or "meta"
    out = {}

    # ===== PLANNER =====
    if action == "meta":
        out["farms"] = FARMS
        out["company"] = DEFAULT_COMPANY

    elif action == "blocks":
        farm = frappe.form_dict.get("farm")
        rows = frappe.db.get_all("Warehouse", filters={"custom_farm":farm,"is_group":0,"disabled":0},
            fields=["name","warehouse_name","custom_area_ha"], order_by="name", limit=500)
        blocks = []
        for r in rows:
            nm = r.warehouse_name or r.name
            skip = False
            for kw in BLOCK_EXCLUDE:
                if kw.lower() in nm.lower():
                    skip = True
            if not skip:
                blocks.append({"name":r.name,"label":nm.replace(" - KL",""),"area":frappe.utils.flt(r.custom_area_ha)})
        out["blocks"] = blocks

    elif action == "tasks":
        farm = frappe.form_dict.get("farm")
        proj = FARM_PROJECT.get(farm)
        rows = frappe.db.get_all("Task", filters={"project":proj,"is_group":0},
            fields=["name","subject","custom_uom","custom_daily_target","custom_rate"],
            order_by="subject", limit=500)
        tasks = []
        for r in rows:
            tasks.append({"name":r.name,"subject":r.subject,"uom":r.custom_uom,
                "daily_target":r.custom_daily_target or 0,"rate":r.custom_rate or 0})
        out["tasks"] = tasks

    elif action == "compare":
        rows = frappe.db.get_all("Work Management Planner",
            filters={"farm":frappe.form_dict.get("farm"),"block_section":frappe.form_dict.get("block"),
                     "task":frappe.form_dict.get("task"),"workflow_state":"Approved"},
            fields=["name","quantity","people_per_day","person_days","total_cost","from_date","to_date","approval_date"],
            order_by="approval_date desc", limit=1)
        out["last"] = rows[0] if rows else None

    elif action == "pending":
        # FARM SCOPING: a farm manager only sees plans awaiting approval for their own farm(s).
        # GM / System Manager / HR see all. Uses farm-specific roles (same signal as Assigner/Actuals).
        pflt = {"workflow_state": "Pending Approval"}
        prl = frappe.db.get_all("Has Role", filters={"parent": frappe.session.user}, pluck="role")
        pbypass = ("System Manager" in prl) or ("General Manager" in prl) or ("HOD HR" in prl) or ("HR Manager Kaitet" in prl) or (frappe.session.user == "Administrator")
        if not pbypass:
            pallowed = []
            for _farm_, _role_ in FARM_APPROVER_ROLE.items():
                if _role_ in prl: pallowed.append(_farm_)
            pflt["farm"] = ["in", pallowed] if pallowed else ["in", ["__none__"]]
        out["pending"] = frappe.db.get_all("Work Management Planner",
            filters=pflt,
            fields=["name","farm","block_section","task","quantity","people_per_day","person_days",
                    "total_hours","total_cost","from_date","to_date","requested_by","request_date",
                    "workflow_state","uom","daily_target","rate","working_days"],
            order_by="request_date desc", limit=200)

    elif action == "my_requests":
        out["requests"] = frappe.db.get_all("Work Management Planner",
            filters={"requested_by":frappe.session.user},
            fields=["name","farm","block_section","task","quantity","people_per_day","person_days",
                    "total_hours","total_cost","from_date","to_date","workflow_state","request_date",
                    "approved_by","approval_date","uom","daily_target","rate","working_days"],
            order_by="creation desc", limit=200)

    elif action == "planner_blocks":
        # full block list for one planner (primary + extras)
        nm = frappe.form_dict.get("planner")
        primary = frappe.db.get_value("Work Management Planner", nm, "block_section")
        blist = []
        if primary:
            blist.append(primary)
        for r in frappe.db.get_all("Work Planner Block", filters={"parent":nm},
                fields=["block"], order_by="idx"):
            if r.block:
                blist.append(r.block)
        out["blocks"] = blist

    elif action == "roles":
        roles = frappe.db.get_all("Has Role", filters={"parent":frappe.session.user}, fields=["role"])
        rl = []
        for r in roles:
            rl.append(r.role)
        is_fm = False
        for r in rl:
            if r.startswith("Farm Manager"):
                is_fm = True
        out["user"] = frappe.session.user
        out["is_section_head"] = ("Production Section Head" in rl) or is_fm
        out["is_approver"] = is_fm

    elif action == "submit":
        farm = frappe.form_dict.get("farm")
        block = frappe.form_dict.get("block")
        blocks_raw = frappe.form_dict.get("blocks")
        task = frappe.form_dict.get("task"); qty = frappe.utils.flt(frappe.form_dict.get("quantity"))
        from_date = frappe.form_dict.get("from_date"); to_date = frappe.form_dict.get("to_date")
        submit_now = frappe.form_dict.get("submit_now")
        plan_name = frappe.form_dict.get("plan")  # if editing an existing draft
        block_list = []
        if blocks_raw:
            for b in blocks_raw.split(","):
                bv = b.strip()
                if bv and bv not in block_list:
                    block_list.append(bv)
        elif block:
            block_list.append(block)
        primary = block_list[0] if block_list else None
        err = None
        if farm not in FARMS: err = "Invalid farm"
        if not primary: err = "At least one block is required"
        if not task: err = "Task is required"
        if qty <= 0: err = "Quantity must be greater than zero"
        if not from_date or not to_date: err = "Date range is required"
        if err:
            out["error"] = err
        else:
            wd = frappe.utils.date_diff(to_date, from_date) + 1
            if wd < 1: wd = 0
            tinfo = frappe.db.get_value("Task", task, ["custom_daily_target","custom_rate","custom_uom"], as_dict=True)
            tgt = frappe.utils.flt(tinfo.custom_daily_target) if tinfo else 0
            rate = frappe.utils.flt(tinfo.custom_rate) if tinfo else 0
            uom = tinfo.custom_uom if tinfo else None
            ppd = 0
            if tgt > 0 and wd > 0:
                raw = qty / tgt / wd
                ppd = int(raw)
                if ppd < raw: ppd = ppd + 1
            editing = 0
            if plan_name and frappe.db.exists("Work Management Planner", plan_name):
                state = frappe.db.get_value("Work Management Planner", plan_name, "workflow_state")
                if state in ("Draft", "Rejected", "Pending Approval"):
                    d = frappe.get_doc("Work Management Planner", plan_name)
                    d.set("extra_blocks", [])   # rebuild blocks from the new selection
                    editing = 1
                else:
                    d = frappe.new_doc("Work Management Planner")
            else:
                d = frappe.new_doc("Work Management Planner")
            d.farm = farm; d.company = DEFAULT_COMPANY; d.block_section = primary
            i = 0
            for b in block_list:
                if i > 0:
                    row = d.append("extra_blocks", {}); row.block = b
                i = i + 1
            d.task = task; d.uom = uom; d.daily_target = tgt; d.rate = rate
            d.task_kpi = str(tgt) + " " + (uom or "") + "/day @ KES " + str(rate)
            d.from_date = from_date; d.to_date = to_date; d.working_days = wd
            # total hours across the period: Mon-Fri=8, Sat=6, Sun=8
            th = 0
            cursor = frappe.utils.getdate(from_date)
            endd = frappe.utils.getdate(to_date)
            guard = 0
            while cursor <= endd and guard < 400:
                wdi = cursor.weekday()  # Mon=0 .. Sun=6
                if wdi == 5:
                    th = th + SATURDAY_HOURS
                else:
                    th = th + WEEKDAY_HOURS
                cursor = frappe.utils.add_days(cursor, 1)
                guard = guard + 1
            d.quantity = qty; d.people_per_day = ppd; d.person_days = ppd * wd
            d.total_hours = th
            d.total_cost = qty * rate
            if not editing:
                d.requested_by = frappe.session.user; d.request_date = frappe.utils.today()
            if editing:
                # keep it a draft unless they explicitly submit; reset a Rejected back to Draft on save
                if not submit_now:
                    d.workflow_state = "Draft"
                d.save(ignore_permissions=True)
            else:
                d.insert(ignore_permissions=True)
            if submit_now:
                d.workflow_state = "Pending Approval"; d.save(ignore_permissions=True)
            out["name"] = d.name; out["workflow_state"] = d.workflow_state
            out["total_cost"] = d.total_cost; out["people_per_day"] = d.people_per_day
            out["blocks"] = block_list
            out["editing"] = editing

    elif action == "approve":
        nm = frappe.form_dict.get("name")
        cur_ws = frappe.db.get_value("Work Management Planner", nm, "workflow_state")
        # CONSULTANT GATE: future-week plans need the week's consultant sign-off
        gate_ok = 1
        try:
            if frappe.utils.cint(frappe.db.get_single_value("Work Management Settings", "require_consultant_approval")):
                pfd = frappe.db.get_value("Work Management Planner", nm, "from_date")
                if pfd:
                    today_g = frappe.utils.getdate(frappe.utils.today())
                    next_monday = frappe.utils.add_days(today_g, 7 - today_g.weekday())
                    if frappe.utils.getdate(pfd) >= next_monday:
                        cst = frappe.db.get_value("Work Management Planner", nm, "custom_consultant_state")
                        if cst != "Approved":
                            gate_ok = 0
        except Exception:
            gate_ok = 1
        if not gate_ok:
            out["error"] = "This plan starts in an upcoming week and is awaiting the consultant's weekly sign-off (Weekly review tab)."
        elif cur_ws != "Pending Approval":
            out["error"] = "Not awaiting approval (state: " + str(cur_ws) + ")"
        else:
            frappe.db.set_value("Work Management Planner", nm, "workflow_state", "Approved", update_modified=False)
            frappe.db.set_value("Work Management Planner", nm, "docstatus", 1, update_modified=False)
            frappe.db.set_value("Work Management Planner", nm, "approved_by", frappe.session.user, update_modified=False)
            frappe.db.set_value("Work Management Planner", nm, "approval_date", frappe.utils.today(), update_modified=False)
            out["name"] = nm; out["workflow_state"] = "Approved"

    elif action == "reject":
        nm = frappe.form_dict.get("name")
        cur_ws = frappe.db.get_value("Work Management Planner", nm, "workflow_state")
        if cur_ws != "Pending Approval":
            out["error"] = "Not awaiting approval (state: " + str(cur_ws) + ")"
        else:
            frappe.db.set_value("Work Management Planner", nm, "workflow_state", "Rejected", update_modified=False)
            frappe.db.set_value("Work Management Planner", nm, "approved_by", None, update_modified=False)
            frappe.db.set_value("Work Management Planner", nm, "approval_date", None, update_modified=False)
            out["name"] = nm; out["workflow_state"] = "Rejected"

    # ===== ASSIGNER (a_) =====
    elif action == "plan_detail":
        nm = frappe.form_dict.get("plan")
        p = frappe.db.get_value("Work Management Planner", nm,
            ["name","farm","block_section","task","quantity","from_date","to_date",
             "workflow_state","uom","daily_target","rate"], as_dict=True)
        blist = []
        if p and p.block_section:
            blist.append(p.block_section)
        for r in frappe.db.get_all("Work Planner Block", filters={"parent": nm}, fields=["block"], order_by="idx"):
            if r.block:
                blist.append(r.block)
        if p:
            p["blocks"] = blist
            p["editable"] = 1 if p.workflow_state in ("Draft","Rejected","Pending Approval") else 0
        out["plan"] = p

    elif action == "plan_trace":
        # ONE PLAN, END TO END: who asked for it, who approved it, the crews it was
        # staffed with, the people actually on those crews, what they recorded and
        # what it cost. The weekly board could only show a plan's own row, so there
        # was no way to answer "who approved this and who worked it".
        tr = frappe.form_dict.get("plan")
        pl = frappe.db.get_value("Work Management Planner", tr,
            ["name","farm","block_section","task","quantity","from_date","to_date",
             "workflow_state","uom","daily_target","rate","total_cost","people_per_day",
             "person_days","requested_by","request_date","approved_by","approval_date",
             "custom_consultant_state","custom_consultant_by","custom_consultant_note",
             "fulfilled_qty","remaining_qty","fulfilment_pct","custom_close_state"], as_dict=True)
        if not pl:
            out["error"] = "no such plan: " + str(tr)
        else:
            blist = []
            if pl.block_section:
                blist.append(pl.block_section)
            for b in frappe.db.get_all("Work Planner Block", filters={"parent": tr},
                                       fields=["block"], order_by="idx"):
                if b.block:
                    blist.append(b.block)
            pl["blocks"] = blist
            out["plan"] = pl

            # the approval chain, in the order it actually happens
            chain = []
            chain.append({"step": "Requested", "who": pl.requested_by, "when": str(pl.request_date or "")})
            if pl.custom_consultant_state:
                chain.append({"step": "Consultant " + str(pl.custom_consultant_state),
                              "who": pl.custom_consultant_by, "when": "",
                              "note": pl.custom_consultant_note})
            chain.append({"step": "Farm Manager approved" if pl.approved_by else "Farm Manager approval",
                          "who": pl.approved_by, "when": str(pl.approval_date or "")})
            out["chain"] = chain

            asgs = frappe.db.get_all("Work Management Assigner",
                filters={"planner_request": tr},
                fields=["name","workflow_state","assigned_by","assign_date","approved_by",
                        "approval_date","from_date","to_date","planned_people","assigned_count",
                        "variance","planned_cost"],
                order_by="creation")
            out["assignments"] = asgs
            anames = [a.name for a in asgs]

            # the people put on those crews
            crew = []
            if anames:
                crew = frappe.db.sql("""
                    SELECT we.parent assignment, we.employee, we.employee_name,
                           we.status, we.left_date
                    FROM `tabWork Assignment Employee` we
                    WHERE we.parent IN %(a)s
                    ORDER BY we.employee_name
                """, {"a": tuple(anames)}, as_dict=True)
            out["crew"] = crew

            # what was recorded against those assignments
            acts = []
            worked = []
            if anames:
                acts = frappe.db.sql("""
                    SELECT ac.name, ac.assignment, ac.workflow_state, ac.entered_by,
                           ac.hr_approved_by, ac.gm_approved_by, ac.entry_date,
                           ac.total_actual_qty, ac.total_payment, ac.rate,
                           ac.payroll_people
                    FROM `tabWork Management Actuals` ac
                    WHERE ac.assignment IN %(a)s
                    ORDER BY ac.entry_date
                """, {"a": tuple(anames)}, as_dict=True)
                worked = frappe.db.sql("""
                    SELECT we.employee, we.employee_name,
                           COUNT(DISTINCT we.work_date) days,
                           COALESCE(SUM(we.actual_quantity),0) qty,
                           COALESCE(SUM(we.amount),0) amount,
                           MAX(IFNULL(we.paid,0)) paid,
                           MIN(we.work_date) first_day, MAX(we.work_date) last_day
                    FROM `tabWork Actuals Employee` we
                    INNER JOIN `tabWork Management Actuals` ac ON we.parent = ac.name
                    WHERE ac.assignment IN %(a)s
                    GROUP BY we.employee, we.employee_name
                    ORDER BY COALESCE(SUM(we.amount),0) DESC
                """, {"a": tuple(anames)}, as_dict=True)
            out["actuals"] = acts
            out["workers"] = worked

            act_qty = 0
            act_pay = 0
            for a in acts:
                if a.workflow_state == "CONFIRMED":
                    act_qty = act_qty + frappe.utils.flt(a.total_actual_qty)
                    act_pay = act_pay + frappe.utils.flt(a.total_payment)
            tgt = frappe.utils.flt(pl.quantity)
            bud = frappe.utils.flt(pl.total_cost)
            out["delivery"] = {
                "target": tgt, "actual": act_qty,
                "achieved_pct": (act_qty / tgt * 100) if tgt else 0,
                "planned": bud, "spent": act_pay,
                "of_planned_pct": (act_pay / bud * 100) if bud else 0,
                "crew_planned": frappe.utils.cint(pl.people_per_day),
                "crew_assigned": len(crew),
                "workers_paid": len(worked),
            }

    elif action == "week_board":
        # CONSULTANT WEEKLY BOARD: all of one farm's plans starting in a chosen
        # week, with crew-load per day vs the farm's active workforce, budgets
        # and consultant state. week_start should be a Monday.
        wfarm = frappe.form_dict.get("farm")
        wstart = frappe.form_dict.get("week_start")
        if not wstart:
            tdy = frappe.utils.getdate(frappe.utils.today())
            wstart = str(frappe.utils.add_days(tdy, 7 - tdy.weekday()))
        wend = str(frappe.utils.add_days(wstart, 6))
        if not wfarm:
            out["error"] = "farm is required"
        else:
            plans = frappe.db.sql("""
                SELECT name, task, block_section, from_date, to_date, people_per_day,
                       quantity, uom, rate, total_cost, workflow_state, requested_by,
                       custom_consultant_state, custom_consultant_by, custom_consultant_at,
                       custom_consultant_note, custom_close_state
                FROM `tabWork Management Planner`
                WHERE farm = %s AND from_date <= %s AND from_date >= %s
                  AND workflow_state != 'Rejected'
                ORDER BY from_date, task
            """, (wfarm, wend, wstart), as_dict=True)
            pnames = [r.name for r in plans]
            blocks_map = {}
            if pnames:
                for r in frappe.db.sql("""
                    SELECT parent, block FROM `tabWork Planner Block` WHERE parent IN %s
                """, (tuple(pnames),), as_dict=True):
                    bl = blocks_map.get(r.parent)
                    if bl is None:
                        bl = []
                        blocks_map[r.parent] = bl
                    if r.block:
                        bl.append(r.block)
            days = []
            cur_d = wstart
            g = 0
            while cur_d <= wend and g < 8:
                days.append(cur_d)
                cur_d = str(frappe.utils.add_days(cur_d, 1))
                g = g + 1
            load = {}
            for dd in days:
                load[dd] = 0
            tot_budget = 0
            tot_target_v = 0
            rows_b = []
            for r in plans:
                bl = []
                if r.block_section:
                    bl.append(r.block_section)
                for b in blocks_map.get(r.name, []):
                    if b not in bl:
                        bl.append(b)
                for dd in days:
                    if str(r.from_date) <= dd <= str(r.to_date):
                        load[dd] = load[dd] + frappe.utils.cint(r.people_per_day)
                tot_budget = tot_budget + frappe.utils.flt(r.total_cost)
                rows_b.append({"name": r.name, "task": r.task, "blocks": bl,
                               "period": str(r.from_date) + " → " + str(r.to_date),
                               "from_date": str(r.from_date), "to_date": str(r.to_date),
                               "crew": frappe.utils.cint(r.people_per_day),
                               "target": frappe.utils.flt(r.quantity), "uom": r.uom,
                               "rate": frappe.utils.flt(r.rate),
                               "budget": frappe.utils.flt(r.total_cost),
                               "state": r.workflow_state,
                               "requested_by": r.requested_by,
                               "consultant_state": r.custom_consultant_state,
                               "consultant_by": r.custom_consultant_by,
                               "consultant_note": r.custom_consultant_note})
            wf_row = frappe.db.sql("""
                SELECT COUNT(*) n FROM `tabEmployee`
                WHERE status = 'Active' AND TRIM(IFNULL(custom_farm,'')) = %s
            """, (wfarm,), as_dict=True)
            workforce = frappe.utils.cint(wf_row[0].n) if wf_row else 0
            clist = []
            gate_on = 0
            try:
                gate_on = frappe.utils.cint(frappe.db.get_single_value("Work Management Settings", "require_consultant_approval"))
                raw = frappe.db.get_single_value("Work Management Settings", "consultant_users") or ""
                for c in raw.replace("\n", ",").split(","):
                    cv = c.strip().lower()
                    if cv:
                        clist.append(cv)
            except Exception:
                pass
            roles_w = frappe.db.get_all("Has Role", filters={"parent": frappe.session.user}, pluck="role")
            is_consultant = (frappe.session.user.lower() in clist) or ("System Manager" in roles_w)
            out["week"] = {"start": wstart, "end": wend}
            out["farm"] = wfarm
            out["plans"] = rows_b
            out["load"] = [{"d": dd, "crew": load[dd]} for dd in days]
            out["workforce"] = workforce
            out["totals"] = {"plans": len(rows_b), "budget": tot_budget,
                             "peak_crew": max([load[dd] for dd in days]) if days else 0,
                             "approved": len([x for x in rows_b if x["consultant_state"] == "Approved"]),
                             "returned": len([x for x in rows_b if x["consultant_state"] == "Returned"])}
            out["is_consultant"] = 1 if is_consultant else 0
            out["gate_on"] = gate_on

    elif action == "week_approve" or action == "week_return":
        # consultant decision on a farm-week: stamp every plan in the package
        wfarm = frappe.form_dict.get("farm")
        wstart = frappe.form_dict.get("week_start")
        wnote = (frappe.form_dict.get("note") or "").strip()
        approving = (action == "week_approve")
        err = None
        if not wfarm or not wstart:
            err = "farm and week_start are required"
        if not err and not approving and not wnote:
            err = "A note is required when returning a week"
        clist = []
        try:
            raw = frappe.db.get_single_value("Work Management Settings", "consultant_users") or ""
            for c in raw.replace("\n", ",").split(","):
                cv = c.strip().lower()
                if cv:
                    clist.append(cv)
        except Exception:
            pass
        roles_w = frappe.db.get_all("Has Role", filters={"parent": frappe.session.user}, pluck="role")
        if not err and frappe.session.user.lower() not in clist and "System Manager" not in roles_w:
            err = "Only the consultants named in Work Management Settings can decide a weekly package"
        if err:
            out["error"] = err
        else:
            wend = str(frappe.utils.add_days(wstart, 6))
            plans = frappe.db.get_all("Work Management Planner",
                filters={"farm": wfarm, "from_date": ["between", [wstart, wend]],
                         "workflow_state": ["!=", "Rejected"]},
                pluck="name", limit=300)
            newstate = "Approved" if approving else "Returned"
            wnow = frappe.utils.now()
            for pn in plans:
                frappe.db.set_value("Work Management Planner", pn, "custom_consultant_state", newstate, update_modified=False)
                frappe.db.set_value("Work Management Planner", pn, "custom_consultant_by", frappe.session.user, update_modified=False)
                frappe.db.set_value("Work Management Planner", pn, "custom_consultant_at", wnow, update_modified=False)
                frappe.db.set_value("Work Management Planner", pn, "custom_consultant_note", wnote, update_modified=False)
            frappe.db.commit()
            for pn in plans:
                try:
                    frappe.get_doc("Work Management Planner", pn).add_comment("Comment",
                        ("Consultant approved" if approving else "Consultant returned") +
                        " (week " + wstart + ", " + wfarm + ") by " + frappe.session.user +
                        (": " + wnote if wnote else ""))
                except Exception:
                    pass
            out["decided"] = len(plans)
            out["state"] = newstate


    else:
        out["error"] = "unknown action: " + str(action)

    return out
