# Ported from Kaitet live Server Script "wm_rates" (API) — logic unchanged.
# Farms / projects / company / approver roles now come from Work Management Settings
# (falls back to the original Kaitet defaults) — see upande_work_management/api/config.py.
# REGENERATED by kaitet-work-management/port_app.py — edit the mirror script, not this file.

import json

import frappe

from upande_work_management.api.config import get_config


@frappe.whitelist()
def wm_rates(**kwargs):
    _cfg = get_config()
    FARM_PROJECT = _cfg["farm_project"]
    DEFAULT_COMPANY = _cfg["default_company"]
    FARMS = _cfg["farms"]
    BLOCK_EXCLUDE = _cfg["block_exclude"]
    FARM_APPROVER_ROLE = _cfg["farm_approver_role"]

    # ==================================================================
    # SERVER SCRIPT — "WM Rates" (API, api_method=wm_rates)
    # Effective-dated task rates + wage recalculation.
    #
    # Rate history lives in "Work Task Rate": one row per task per period,
    # never overlapping, at most one left open (valid_to empty = active today).
    # Task.custom_rate / custom_uom / custom_daily_target are MIRRORED from the
    # active period, so the planner (wm_planner) keeps reading Task exactly as
    # it always has.
    #
    # On the live site these are CUSTOM doctypes and therefore have no Python
    # controller, so every invariant (close-previous, no-overlap, mirror-to-Task)
    # is enforced here. The packaged app enforces the same rules in
    # work_task_rate.py — keep the two in step.
    #
    # No def/return allowed in the sandbox, so everything is inline.
    # ==================================================================

    # Daily wage tiers that legitimately existed before the 2026-07-21 rate card.
    # 340 is the general wage; 350 is a distinct tier covering packhouse, greenhouse,
    # QC and reliever work. Both rise to 387, so both count as wage-derived — a task
    # is measured against whichever tier it sits closest to.
    LEGACY_DAILY_WAGE = 340.0
    KNOWN_DAILY_WAGES = [340.0, 350.0]

    # Within 1% of the wage -> wage-derived outright.
    # Within 10% -> borderline, needs a human decision and is NEVER auto-applied.
    # The old 1% band silently excluded Planting grass (4.6 x 75 = 345/day) which
    # really is 340-derived: the true rate is 340/75 = 4.5333 and someone rounded up.
    # Bands are inclusive; the epsilon absorbs float error at the exact edge
    # (340 * 1.10 evaluates to 374.00000000000006).
    EXACT_BAND = 0.01
    REVIEW_BAND = 0.10
    BAND_EPSILON = 0.000001

    # Rows revalued per call. Repeat until "remaining" comes back 0.
    CHUNK = 800

    # Changing a rate reaches money that has already been approved, so it is held
    # tighter than raising a master plan: the general manager, the HR head and a
    # System Manager, and nobody else.
    RATE_ROLES = ["General Manager", "HOD HR", "System Manager"]
    rt_roles = frappe.db.get_all("Has Role", filters={"parent": frappe.session.user}, pluck="role")
    CAN_RATE = 0
    for rr in RATE_ROLES:
        if rr in rt_roles:
            CAN_RATE = 1

    action = frappe.form_dict.get("action") or "meta"
    out = {}

    # ==================================================================
    # META — what the Settings screen shows before you do anything
    # ==================================================================
    if action == "meta":
        today = frappe.utils.today()
        out["today"] = today
        out["legacy_daily_wage"] = LEGACY_DAILY_WAGE
        out["tasks_with_rate"] = frappe.db.count("Task", {"custom_rate": [">", 0]})
        out["periods"] = frappe.db.count("Work Task Rate")
        out["tasks_covered"] = len(frappe.db.sql(
            "SELECT DISTINCT task FROM `tabWork Task Rate`", as_dict=True))
        wages = frappe.db.sql("""
            SELECT daily_wage_basis wage, COUNT(*) n
            FROM `tabWork Task Rate`
            WHERE valid_from <= %s AND (valid_to IS NULL OR valid_to >= %s)
              AND IFNULL(daily_wage_basis,0) > 0
            GROUP BY daily_wage_basis ORDER BY n DESC
        """, (today, today), as_dict=True)
        out["active_wages"] = wages
        out["current_daily_wage"] = frappe.utils.flt(wages[0].wage) if wages else None
        out["borderline_pending"] = frappe.db.count(
            "Work Task Rate", {"derived": 0, "notes": ["like", "Borderline:%"]}
        )
        last = frappe.db.get_all("Work Rate Recalc Run",
            fields=["name", "status", "from_date", "dry_run", "rows_changed", "delta",
                    "executed_by", "executed_on"],
            order_by="creation desc", limit=1)
        out["last_run"] = last[0] if last else None

    # ==================================================================
    # BACKFILL — give every rated Task one open period holding today's values
    # ==================================================================
    elif action == "backfill":
        bf_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        bf_wage = frappe.utils.flt(frappe.form_dict.get("wage") or 0)
        bf_tiers = [bf_wage] if bf_wage else KNOWN_DAILY_WAGES
        bf_epoch = frappe.form_dict.get("epoch")
        if not bf_epoch:
            # history has to start no later than the earliest plan, or the recalc
            # would meet work it cannot price and refuse to run
            earliest = frappe.db.sql("""
                SELECT MIN(from_date) d FROM `tabWork Management Planner` WHERE from_date IS NOT NULL
            """, as_dict=True)
            bf_epoch = str(earliest[0].d) if earliest and earliest[0].d else frappe.utils.today()

        bf_tasks = frappe.db.sql("""
            SELECT name, custom_rate rate, custom_uom uom, custom_daily_target tgt
            FROM `tabTask` WHERE IFNULL(custom_rate,0) > 0
        """, as_dict=True)
        bf_have = {}
        for t in frappe.db.sql("SELECT DISTINCT task t FROM `tabWork Task Rate`", as_dict=True):
            bf_have[t.t] = 1

        bf_created = 0
        bf_skipped = 0
        bf_counts = {"derived": 0, "borderline": 0, "not_derived": 0, "unknown": 0}
        for t in bf_tasks:
            if bf_have.get(t.name):
                bf_skipped = bf_skipped + 1
                continue
            r = frappe.utils.flt(t.rate)
            g = frappe.utils.flt(t.tgt)
            if not r or not g:
                verdict = "unknown"
                implied = 0
            else:
                implied = r * g
                matched = bf_tiers[0]
                for w in bf_tiers:
                    if abs(implied - w) < abs(implied - matched):
                        matched = w
                drift = abs(implied - matched)
                if drift <= matched * EXACT_BAND + BAND_EPSILON:
                    verdict = "derived"
                elif drift <= matched * REVIEW_BAND + BAND_EPSILON:
                    verdict = "borderline"
                else:
                    verdict = "not_derived"
            bf_counts[verdict] = bf_counts[verdict] + 1
            bf_created = bf_created + 1
            if bf_dry:
                continue

            note = None
            if verdict == "borderline":
                note = ("Borderline: implied daily wage " + str(round(implied, 2)) +
                        " against nearest tier " + str(matched) + ". Confirm whether this "
                        "rate is wage-derived before recalculating.")
            elif verdict == "not_derived":
                note = ("Not wage-derived: implied daily wage " + str(round(implied, 2)) +
                        ". Excluded from wage recalculations.")
            elif verdict == "unknown":
                note = "No usable rate or daily target on the Task."

            d = frappe.new_doc("Work Task Rate")
            d.task = t.name
            d.valid_from = bf_epoch
            # legacy rate kept EXACTLY as stored, rounding and all — this is what
            # was actually used to pay people; rewriting it would falsify history
            d.rate = r
            d.uom = t.uom
            d.daily_target = g
            d.daily_wage_basis = matched if verdict == "derived" else None
            d.derived = 1 if verdict == "derived" else 0
            d.source = "backfill from Task master"
            d.notes = note
            d.flags.ignore_permissions = True
            d.insert(ignore_permissions=True)
            if bf_created % 200 == 0:
                frappe.db.commit()

        if not bf_dry:
            frappe.db.commit()
        out["epoch"] = str(bf_epoch)
        out["dry_run"] = bf_dry
        out["tasks_considered"] = len(bf_tasks)
        out["periods_created"] = bf_created
        out["already_covered"] = bf_skipped
        out["classification"] = bf_counts
        out["tiers"] = bf_tiers

    # ==================================================================
    # BORDERLINE — tasks whose classification a human has to settle
    # ==================================================================
    elif action == "borderline":
        bl = frappe.db.sql("""
            SELECT wtr.name, wtr.task, wtr.rate, wtr.daily_target, wtr.uom,
                   wtr.valid_from, wtr.valid_to, wtr.notes
            FROM `tabWork Task Rate` wtr
            WHERE IFNULL(wtr.derived,0) = 0 AND IFNULL(wtr.notes,'') LIKE 'Borderline:%'
            ORDER BY wtr.task
        """, as_dict=True)
        for b in bl:
            b["implied_daily_wage"] = frappe.utils.flt(
                frappe.utils.flt(b.rate) * frappe.utils.flt(b.daily_target), 2)
            b["rows_since_change"] = frappe.db.sql("""
                SELECT COUNT(*) n FROM `tabWork Actuals Employee` we
                INNER JOIN `tabWork Management Actuals` ac ON we.parent = ac.name
                WHERE ac.task = %s AND IFNULL(we.paid,0) = 0 AND IFNULL(we.amount,0) > 0
            """, (b.task,), as_dict=True)[0].n
        out["borderline"] = bl

    elif action == "classify":
        # Record a decision on borderline periods: derived 1/0, once and for all.
        # Accepts one name, or a CSV of names so a whole review round settles in a
        # single call. wage="implied" records each period's own rate x daily_target
        # as its basis, which is the honest answer for a task that sat on its own
        # odd wage (345, 360, 320) rather than a shared tier.
        c_raw = frappe.form_dict.get("names") or frappe.form_dict.get("name") or ""
        c_derived = frappe.utils.cint(frappe.form_dict.get("derived"))
        c_wage_in = frappe.form_dict.get("wage")
        c_names = []
        for c in str(c_raw).split(","):
            cv = c.strip()
            if cv and cv not in c_names:
                c_names.append(cv)
        if not c_names:
            out["error"] = "name or names is required"
        else:
            c_done = []
            c_missing = []
            for cn in c_names:
                row = frappe.db.get_value("Work Task Rate", cn,
                    ["name", "task", "rate", "daily_target"], as_dict=True)
                if not row:
                    c_missing.append(cn)
                    continue
                if not c_derived:
                    c_basis = None
                elif str(c_wage_in or "").lower() == "implied":
                    c_basis = frappe.utils.flt(
                        frappe.utils.flt(row.rate) * frappe.utils.flt(row.daily_target), 6)
                else:
                    c_basis = frappe.utils.flt(c_wage_in or LEGACY_DAILY_WAGE)
                frappe.db.set_value("Work Task Rate", cn, {
                    "derived": 1 if c_derived else 0,
                    "daily_wage_basis": c_basis,
                    "notes": ("Confirmed wage-derived (basis " + str(c_basis) + ") by "
                              if c_derived else "Confirmed NOT wage-derived by ") +
                             frappe.session.user + " on " + frappe.utils.today(),
                })
                c_done.append({"name": cn, "task": row.task, "basis": c_basis})
            frappe.db.commit()
            out["classified"] = c_done
            out["missing"] = c_missing
            out["derived"] = 1 if c_derived else 0

    # ==================================================================
    # APPLY WAGE — write the new wage's periods from an effective date
    # Pure uplift: rate = new_wage / existing daily_target, unit and target
    # carried over unchanged. Target/UOM revisions are a separate, forward-only
    # change and are deliberately NOT written here.
    # ==================================================================
    elif action == "apply_wage":
        aw_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        aw_wage = frappe.utils.flt(frappe.form_dict.get("wage") or 0)
        aw_from = frappe.form_dict.get("effective_from")
        aw_source = frappe.form_dict.get("source") or ("Rate card " + str(aw_from))
        if not aw_wage or not aw_from:
            out["error"] = "wage and effective_from are required"
        else:
            aw_day_before = frappe.utils.add_days(aw_from, -1)
            # every task whose period in force the day before is wage-derived
            # optional project scope: rates live on Task, and Task belongs to a
            # Project, so a rate card that only covers e.g. the avocado and coffee
            # task lists must not touch anything else.
            aw_projects = []
            for pj in str(frappe.form_dict.get("projects") or "").split(","):
                pv = pj.strip()
                if pv and pv not in aw_projects:
                    aw_projects.append(pv)
            aw_cond = ""
            aw_params = {"d": aw_day_before}
            if aw_projects:
                aw_cond = " AND t.project IN %(projects)s"
                aw_params["projects"] = tuple(aw_projects)
            aw_rows = frappe.db.sql("""
                SELECT wtr.name period, wtr.task, wtr.rate, wtr.uom, wtr.daily_target,
                       wtr.daily_wage_basis, wtr.valid_from, wtr.valid_to
                FROM `tabWork Task Rate` wtr
                INNER JOIN `tabTask` t ON t.name = wtr.task
                WHERE wtr.derived = 1
                  AND wtr.valid_from <= %(d)s
                  AND (wtr.valid_to IS NULL OR wtr.valid_to >= %(d)s)
            """ + aw_cond, aw_params, as_dict=True)

            aw_existing = {}
            for e in frappe.db.sql("""
                SELECT task FROM `tabWork Task Rate` WHERE valid_from = %s
            """, (aw_from,), as_dict=True):
                aw_existing[e.task] = 1

            aw_made = 0
            aw_skipped = []
            aw_preview = []
            for r in aw_rows:
                if aw_existing.get(r.task):
                    aw_skipped.append({"task": r.task, "why": "a period already starts on " + str(aw_from)})
                    continue
                tgt = frappe.utils.flt(r.daily_target)
                if not tgt:
                    aw_skipped.append({"task": r.task, "why": "no daily target"})
                    continue
                new_rate = aw_wage / tgt
                aw_preview.append({
                    "task": r.task, "uom": r.uom, "daily_target": tgt,
                    "old_rate": frappe.utils.flt(r.rate, 6),
                    "new_rate": frappe.utils.flt(new_rate, 6),
                })
                aw_made = aw_made + 1
                if aw_dry:
                    continue

                d = frappe.new_doc("Work Task Rate")
                d.task = r.task
                d.valid_from = aw_from
                d.rate = new_rate
                d.uom = r.uom
                d.daily_target = tgt
                d.daily_wage_basis = aw_wage
                d.derived = 1
                d.source = aw_source
                d.flags.ignore_permissions = True
                d.insert(ignore_permissions=True)
                # CUSTOM doctype on live = no controller, so close the superseded
                # period and mirror onto Task right here
                # the sandbox allows read-only SQL only, so close the superseded
                # period through the ORM rather than an UPDATE statement
                for pv in frappe.db.sql("""
                    SELECT name FROM `tabWork Task Rate`
                    WHERE task = %(task)s AND name != %(me)s AND valid_to IS NULL
                      AND valid_from < %(vfrom)s
                """, {"task": r.task, "me": d.name, "vfrom": aw_from}, as_dict=True):
                    frappe.db.set_value("Work Task Rate", pv.name, "valid_to", aw_day_before)
                if aw_made % 100 == 0:
                    frappe.db.commit()

            if not aw_dry:
                # mirror whichever period is active TODAY onto each Task
                for r in aw_rows:
                    act = frappe.db.sql("""
                        SELECT rate, uom, daily_target FROM `tabWork Task Rate`
                        WHERE task = %(t)s AND valid_from <= %(today)s
                          AND (valid_to IS NULL OR valid_to >= %(today)s)
                        ORDER BY valid_from DESC LIMIT 1
                    """, {"t": r.task, "today": frappe.utils.today()}, as_dict=True)
                    if act:
                        frappe.db.set_value("Task", r.task, {
                            "custom_rate": frappe.utils.flt(act[0].rate),
                            "custom_uom": act[0].uom,
                            "custom_daily_target": frappe.utils.flt(act[0].daily_target),
                        })
                frappe.db.commit()

            out["dry_run"] = aw_dry
            out["wage"] = aw_wage
            out["effective_from"] = aw_from
            out["periods_written"] = aw_made
            out["projects"] = aw_projects or "all"
            out["skipped"] = aw_skipped
            out["preview"] = aw_preview[:400]

    # ==================================================================
    # RECALC — revalue unpaid day-rows at their period's rate
    # dry_run=1 (default) reports and changes nothing.
    # ==================================================================
    elif action == "recalc":
        rc_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        rc_from = frappe.form_dict.get("from_date")
        rc_to = frappe.form_dict.get("to_date")
        rc_farm = frappe.form_dict.get("farm")
        rc_run = frappe.form_dict.get("run")
        if not rc_from:
            out["error"] = "from_date is required"
        else:
            rc_conds = "we.work_date >= %(from_date)s AND IFNULL(we.paid,0) = 0 AND IFNULL(we.amount,0) > 0"
            rc_params = {"from_date": rc_from}
            if rc_to:
                rc_conds = rc_conds + " AND we.work_date <= %(to_date)s"
                rc_params["to_date"] = rc_to
            if rc_farm:
                rc_conds = rc_conds + " AND ac.farm = %(farm)s"
                rc_params["farm"] = rc_farm

            # --- GUARD: a task whose unit or daily target changed at the boundary
            # cannot have old rows revalued. A quantity recorded as "1 day" is not
            # the same measurement as "1 hour"; Garderner (340/Day/1) re-specified
            # as 10 Hrs @ 38.70 would pay 38.70 instead of 387. Not overridable.
            rc_prev_day = frappe.utils.add_days(rc_from, -1)
            rc_blocked = {}
            for g in frappe.db.sql("""
                SELECT cur.task task, cur.uom cur_uom, cur.daily_target cur_tgt,
                       prv.uom prv_uom, prv.daily_target prv_tgt
                FROM `tabWork Task Rate` cur
                INNER JOIN `tabWork Task Rate` prv ON prv.task = cur.task
                WHERE cur.valid_from <= %(d)s AND (cur.valid_to IS NULL OR cur.valid_to >= %(d)s)
                  AND prv.valid_from <= %(p)s AND (prv.valid_to IS NULL OR prv.valid_to >= %(p)s)
            """, {"d": rc_from, "p": rc_prev_day}, as_dict=True):
                same_uom = (g.cur_uom or "") == (g.prv_uom or "")
                same_tgt = abs(frappe.utils.flt(g.cur_tgt) - frappe.utils.flt(g.prv_tgt)) < 0.000001
                if not same_uom or not same_tgt:
                    rc_blocked[g.task] = ("unit or daily target changed at " + str(rc_from) +
                                          " (" + str(g.prv_tgt) + " " + str(g.prv_uom or "") +
                                          " -> " + str(g.cur_tgt) + " " + str(g.cur_uom or "") +
                                          ") - recorded quantities are not comparable")

            rc_rows = frappe.db.sql("""
                SELECT we.name rowname, we.parent actuals, we.employee, we.employee_name,
                       we.work_date, we.actual_quantity qty, we.amount, we.payment_ref,
                       ac.task task, ac.farm farm,
                       wtr.name period, wtr.rate new_rate, wtr.derived derived
                FROM `tabWork Actuals Employee` we
                INNER JOIN `tabWork Management Actuals` ac ON we.parent = ac.name
                LEFT JOIN `tabWork Task Rate` wtr
                       ON wtr.task = ac.task
                      AND wtr.valid_from <= we.work_date
                      AND (wtr.valid_to IS NULL OR wtr.valid_to >= we.work_date)
                WHERE """ + rc_conds + """
                ORDER BY we.work_date, we.name
            """, rc_params, as_dict=True)

            rc_todo = []
            rc_skips = {}
            rc_by_task = {}
            rc_old_total = 0
            rc_new_total = 0
            for r in rc_rows:
                why = None
                if not r.period:
                    why = "no rate period covering " + str(r.work_date)
                elif not frappe.utils.cint(r.derived):
                    why = "not wage-derived"
                elif rc_blocked.get(r.task):
                    why = rc_blocked.get(r.task)
                if why:
                    key = str(r.task) + " :: " + why
                    if key not in rc_skips:
                        rc_skips[key] = {"task": r.task, "why": why, "rows": 0, "amount": 0}
                    rc_skips[key]["rows"] = rc_skips[key]["rows"] + 1
                    rc_skips[key]["amount"] = rc_skips[key]["amount"] + frappe.utils.flt(r.amount)
                    continue

                old_amt = frappe.utils.flt(r.amount)
                new_amt = frappe.utils.flt(frappe.utils.flt(r.qty) * frappe.utils.flt(r.new_rate), 2)
                if abs(new_amt - old_amt) <= 0.005:
                    continue
                rc_todo.append(r)
                rc_old_total = rc_old_total + old_amt
                rc_new_total = rc_new_total + new_amt
                if r.task not in rc_by_task:
                    rc_by_task[r.task] = {"task": r.task, "rows": 0, "old": 0, "new": 0}
                rc_by_task[r.task]["rows"] = rc_by_task[r.task]["rows"] + 1
                rc_by_task[r.task]["old"] = rc_by_task[r.task]["old"] + old_amt
                rc_by_task[r.task]["new"] = rc_by_task[r.task]["new"] + new_amt

            out["dry_run"] = rc_dry
            out["from_date"] = rc_from
            out["rows_examined"] = len(rc_rows)
            out["rows_to_change"] = len(rc_todo)
            out["old_total"] = frappe.utils.flt(rc_old_total, 2)
            out["new_total"] = frappe.utils.flt(rc_new_total, 2)
            out["delta"] = frappe.utils.flt(rc_new_total - rc_old_total, 2)
            out["by_task"] = sorted(rc_by_task.values(), key=lambda x: -x["new"])
            out["skipped"] = sorted(rc_skips.values(), key=lambda x: -x["rows"])
            out["pending_accounts_rows"] = len([r for r in rc_todo if r.payment_ref])

            if not rc_dry and rc_todo:
                # ---- run log: created once, appended to on every chunk
                if rc_run and frappe.db.exists("Work Rate Recalc Run", rc_run):
                    run = frappe.get_doc("Work Rate Recalc Run", rc_run)
                else:
                    run = frappe.new_doc("Work Rate Recalc Run")
                    run.from_date = rc_from
                    run.to_date = rc_to
                    run.farm = rc_farm
                    run.dry_run = 0
                    run.status = "Applied"
                    run.executed_by = frappe.session.user
                    run.executed_on = frappe.utils.now()
                    run.flags.ignore_permissions = True
                    run.insert(ignore_permissions=True)

                batch = rc_todo[:CHUNK]
                rc_parents = {}
                rc_payments = {}
                for r in batch:
                    new_amt = frappe.utils.flt(frappe.utils.flt(r.qty) * frappe.utils.flt(r.new_rate), 2)
                    old_amt = frappe.utils.flt(r.amount)
                    frappe.db.set_value("Work Actuals Employee", r.rowname, "amount",
                                        new_amt, update_modified=False)
                    rc_parents[r.actuals] = 1
                    if r.payment_ref:
                        rc_payments[r.payment_ref] = 1
                    ln = run.append("lines", {})
                    ln.ref_doctype = "Work Actuals Employee"
                    ln.ref_name = r.rowname
                    ln.ref_parent = r.actuals
                    ln.task = r.task
                    ln.employee = r.employee
                    ln.work_date = r.work_date
                    ln.old_amount = old_amt
                    ln.new_amount = new_amt
                    ln.new_rate = frappe.utils.flt(r.new_rate, 6)
                    ln.old_rate = frappe.utils.flt(old_amt / frappe.utils.flt(r.qty), 6) if frappe.utils.flt(r.qty) else 0

                # re-sum every touched actuals document
                for pname in rc_parents:
                    tot = frappe.db.sql("""
                        SELECT COALESCE(SUM(amount),0) p FROM `tabWork Actuals Employee` WHERE parent = %s
                    """, (pname,), as_dict=True)
                    if tot:
                        frappe.db.set_value("Work Management Actuals", pname, "total_payment",
                                            frappe.utils.flt(tot[0].p), update_modified=False)

                # ---- payment documents already sent to accounts: rewritten IN PLACE.
                # Each one gets a comment so an edit to a document already handed over
                # is auditable rather than silent.
                for pay in rc_payments:
                    pay_lines = frappe.db.sql("""
                        SELECT name, actuals, employee, amount, qty FROM `tabWork Payment Line`
                        WHERE parent = %s
                    """, (pay,), as_dict=True)
                    grand = 0
                    for pl in pay_lines:
                        s = frappe.db.sql("""
                            SELECT COALESCE(SUM(amount),0) a, COALESCE(SUM(actual_quantity),0) q
                            FROM `tabWork Actuals Employee`
                            WHERE parent = %s AND employee = %s AND payment_ref = %s
                        """, (pl.actuals, pl.employee, pay), as_dict=True)
                        new_line_amt = frappe.utils.flt(s[0].a, 2) if s else frappe.utils.flt(pl.amount)
                        new_line_qty = frappe.utils.flt(s[0].q) if s else frappe.utils.flt(pl.qty)
                        if abs(new_line_amt - frappe.utils.flt(pl.amount)) > 0.005:
                            frappe.db.set_value("Work Payment Line", pl.name, "amount",
                                                new_line_amt, update_modified=False)
                            if new_line_qty:
                                frappe.db.set_value("Work Payment Line", pl.name, "rate",
                                                    frappe.utils.flt(new_line_amt / new_line_qty, 6),
                                                    update_modified=False)
                            ln = run.append("lines", {})
                            ln.ref_doctype = "Work Payment Line"
                            ln.ref_name = pl.name
                            ln.ref_parent = pay
                            ln.employee = pl.employee
                            ln.old_amount = frappe.utils.flt(pl.amount)
                            ln.new_amount = new_line_amt
                        grand = grand + new_line_amt
                    old_grand = frappe.utils.flt(frappe.db.get_value("Work Management Payment", pay, "amount"))
                    if abs(grand - old_grand) > 0.005:
                        frappe.db.set_value("Work Management Payment", pay, "amount",
                                            frappe.utils.flt(grand, 2), update_modified=False)
                        frappe.get_doc({
                            "doctype": "Comment",
                            "comment_type": "Info",
                            "reference_doctype": "Work Management Payment",
                            "reference_name": pay,
                            "content": ("Revalued by rate recalculation " + run.name + ": " +
                                        str(frappe.utils.flt(old_grand, 2)) + " -> " +
                                        str(frappe.utils.flt(grand, 2)) + " (work from " +
                                        str(rc_from) + "). Still pending accounts."),
                        }).insert(ignore_permissions=True)

                run.rows_changed = frappe.utils.cint(run.rows_changed) + len(batch)
                run.old_total = frappe.utils.flt(run.old_total) + sum(
                    [frappe.utils.flt(x.amount) for x in batch])
                run.new_total = frappe.utils.flt(run.new_total) + sum(
                    [frappe.utils.flt(frappe.utils.flt(x.qty) * frappe.utils.flt(x.new_rate), 2) for x in batch])
                run.delta = frappe.utils.flt(run.new_total) - frappe.utils.flt(run.old_total)
                run.rows_skipped = sum([s["rows"] for s in rc_skips.values()])
                run.payments_updated = frappe.utils.cint(run.payments_updated) + len(rc_payments)
                run.summary = json.dumps({
                    "by_task": out["by_task"], "skipped": out["skipped"]}, default=str)
                run.flags.ignore_permissions = True
                run.save(ignore_permissions=True)
                frappe.db.commit()

                out["run"] = run.name
                out["applied_now"] = len(batch)
                out["parents_resummed"] = len(rc_parents)
                out["payments_updated"] = len(rc_payments)
                out["remaining"] = len(rc_todo) - len(batch)

    # ==================================================================
    # SYNC TASK RATES — re-mirror Task.custom_* from the active period
    #
    # Task.custom_rate was Float(2) until 2026-08-04, so the mirror stored 0.97
    # where the period holds 0.9675 — a full day paying 388 instead of 387, and
    # every NEW plan would have inherited it. Once the field precision is raised
    # the stored values still hold the rounded numbers, so they have to be
    # rewritten from the periods.
    # ==================================================================
    elif action == "sync_task_rates":
        st_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        st_today = frappe.utils.today()
        st_rows = frappe.db.sql("""
            SELECT wtr.task task, wtr.rate rate, wtr.uom uom, wtr.daily_target tgt,
                   t.custom_rate cur_rate, t.custom_uom cur_uom,
                   t.custom_daily_target cur_tgt
            FROM `tabWork Task Rate` wtr
            INNER JOIN `tabTask` t ON t.name = wtr.task
            WHERE wtr.valid_from <= %(d)s
              AND (wtr.valid_to IS NULL OR wtr.valid_to >= %(d)s)
        """, {"d": st_today}, as_dict=True)
        st_changed = []
        for r in st_rows:
            want_rate = frappe.utils.flt(r.rate, 6)
            same_rate = abs(want_rate - frappe.utils.flt(r.cur_rate, 6)) <= 0.0000005
            same_tgt = abs(frappe.utils.flt(r.tgt, 6) - frappe.utils.flt(r.cur_tgt, 6)) <= 0.0000005
            same_uom = (r.uom or "") == (r.cur_uom or "")
            if same_rate and same_tgt and same_uom:
                continue
            st_changed.append({"task": r.task,
                               "old_rate": frappe.utils.flt(r.cur_rate, 6),
                               "new_rate": want_rate,
                               "daily_target": frappe.utils.flt(r.tgt),
                               "day_before": frappe.utils.flt(frappe.utils.flt(r.cur_rate) * frappe.utils.flt(r.cur_tgt), 4),
                               "day_after": frappe.utils.flt(want_rate * frappe.utils.flt(r.tgt), 4)})
            if not st_dry:
                frappe.db.set_value("Task", r.task, {
                    "custom_rate": want_rate,
                    "custom_uom": r.uom,
                    "custom_daily_target": frappe.utils.flt(r.tgt),
                }, update_modified=False)
        if not st_dry:
            frappe.db.commit()
        out["dry_run"] = st_dry
        out["tasks_examined"] = len(st_rows)
        out["tasks_corrected"] = len(st_changed)
        out["sample"] = st_changed[:25]

    # ==================================================================
    # SYNC PLANNER RATES — realign plan rate + total_cost with the period
    #
    # A plan snapshots the rate at creation, so plans built while Task.custom_rate
    # was rounded carry the rounded value and would price their actuals wrong at
    # confirm time. Plans that STRADDLE the rate change are reported, never
    # forced onto one side: one plan document cannot hold two rates.
    # ==================================================================
    elif action == "sync_planner_rates":
        sp_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        sp_from = frappe.form_dict.get("from_date")
        if not sp_from:
            out["error"] = "from_date is required"
        else:
            sp_rows = frappe.db.sql("""
                SELECT p.name, p.task, p.rate, p.quantity, p.total_cost,
                       p.from_date, p.to_date, p.workflow_state
                FROM `tabWork Management Planner` p
                WHERE p.to_date >= %(d)s
                  AND IFNULL(p.workflow_state,'') != 'Rejected'
            """, {"d": sp_from}, as_dict=True)
            sp_changed = []
            sp_straddle = []
            for r in sp_rows:
                if r.from_date and str(r.from_date) < str(sp_from):
                    sp_straddle.append({"planner": r.name, "task": r.task,
                                        "from_date": str(r.from_date), "to_date": str(r.to_date)})
                    continue
                per = frappe.db.sql("""
                    SELECT rate, derived FROM `tabWork Task Rate`
                    WHERE task = %(t)s AND valid_from <= %(d)s
                      AND (valid_to IS NULL OR valid_to >= %(d)s)
                    ORDER BY valid_from DESC LIMIT 1
                """, {"t": r.task, "d": r.from_date}, as_dict=True)
                if not per or not frappe.utils.cint(per[0].derived):
                    continue
                want = frappe.utils.flt(per[0].rate, 6)
                if abs(want - frappe.utils.flt(r.rate, 6)) <= 0.0000005:
                    continue
                new_cost = frappe.utils.flt(frappe.utils.flt(r.quantity) * want, 2)
                sp_changed.append({"planner": r.name, "task": r.task,
                                   "old_rate": frappe.utils.flt(r.rate, 6), "new_rate": want,
                                   "old_cost": frappe.utils.flt(r.total_cost, 2), "new_cost": new_cost})
                if not sp_dry:
                    frappe.db.set_value("Work Management Planner", r.name, {
                        "rate": want, "total_cost": new_cost,
                    }, update_modified=False)
            if not sp_dry:
                frappe.db.commit()
            out["dry_run"] = sp_dry
            out["plans_examined"] = len(sp_rows)
            out["plans_corrected"] = len(sp_changed)
            out["straddling_the_change"] = len(sp_straddle)
            out["straddling_sample"] = sp_straddle[:10]
            out["cost_delta"] = frappe.utils.flt(
                sum([c["new_cost"] - c["old_cost"] for c in sp_changed]), 2)
            out["sample"] = sp_changed[:20]

    # ==================================================================
    # REVERT PERIODS — undo rate periods written out of scope
    #
    # Deletes the named periods, re-opens whichever period they superseded, and
    # mirrors the restored rate back onto the Task. Refuses any period that has
    # already priced work, so this can only ever undo an unused rate change.
    # ==================================================================
    elif action == "revert_periods":
        rp_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        rp_raw = frappe.form_dict.get("names") or ""
        rp_names = []
        for rp in str(rp_raw).split(","):
            rv = rp.strip()
            if rv and rv not in rp_names:
                rp_names.append(rv)
        if not rp_names:
            out["error"] = "names is required (CSV)"
        else:
            rp_done = []
            rp_refused = []
            for rn in rp_names:
                row = frappe.db.get_value("Work Task Rate", rn,
                    ["name", "task", "valid_from", "rate"], as_dict=True)
                if not row:
                    rp_refused.append({"name": rn, "why": "not found"})
                    continue
                used = frappe.db.sql("""
                    SELECT COUNT(*) n
                    FROM `tabWork Actuals Employee` we
                    INNER JOIN `tabWork Management Actuals` ac ON we.parent = ac.name
                    WHERE ac.task = %(t)s AND we.work_date >= %(d)s
                      AND IFNULL(we.amount,0) > 0
                """, {"t": row.task, "d": row.valid_from}, as_dict=True)
                if used and frappe.utils.cint(used[0].n):
                    rp_refused.append({"name": rn, "task": row.task,
                                       "why": "has " + str(used[0].n) + " valued rows on/after " +
                                              str(row.valid_from) + " - reverse the recalc first"})
                    continue
                prev = frappe.db.sql("""
                    SELECT name, rate, uom, daily_target FROM `tabWork Task Rate`
                    WHERE task = %(t)s AND name != %(me)s AND valid_to = %(yday)s
                    ORDER BY valid_from DESC LIMIT 1
                """, {"t": row.task, "me": rn,
                      "yday": frappe.utils.add_days(row.valid_from, -1)}, as_dict=True)
                entry = {"name": rn, "task": row.task, "removed_rate": frappe.utils.flt(row.rate, 6),
                         "restored_rate": frappe.utils.flt(prev[0].rate, 6) if prev else None}
                rp_done.append(entry)
                if rp_dry:
                    continue
                frappe.delete_doc("Work Task Rate", rn, ignore_permissions=True, force=True)
                if prev:
                    frappe.db.set_value("Work Task Rate", prev[0].name, "valid_to", None)
                    # db.set_value bypasses document events, so the Task hook cannot
                    # fire and re-create the period we just removed
                    frappe.db.set_value("Task", row.task, {
                        "custom_rate": frappe.utils.flt(prev[0].rate),
                        "custom_uom": prev[0].uom,
                        "custom_daily_target": frappe.utils.flt(prev[0].daily_target),
                    })
            if not rp_dry:
                frappe.db.commit()
            out["dry_run"] = rp_dry
            out["reverted"] = rp_done
            out["reverted_count"] = len(rp_done)
            out["refused"] = rp_refused

    # ==================================================================
    # SYNC DOC RATES — realign Work Management Actuals.rate after a recalc
    #
    # The recalc rewrites row amounts but the parent document keeps the rate it
    # was created with, and the "Amount doesn't match qty x rate" discrepancy
    # check compares amount against qty x ac.rate. Left alone, every revalued row
    # would show up as a false discrepancy. Docs whose rows straddle the change
    # are REPORTED, never silently forced onto one side.
    # ==================================================================
    elif action == "sync_doc_rates":
        sd_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        sd_from = frappe.form_dict.get("from_date")
        if not sd_from:
            out["error"] = "from_date is required"
        else:
            sd_rows = frappe.db.sql("""
                SELECT ac.name actuals, ac.task task, ac.rate cur_rate,
                       MAX(we.work_date) wto,
                       SUM(CASE WHEN we.work_date < %(d)s THEN 1 ELSE 0 END) before_n,
                       SUM(CASE WHEN we.work_date >= %(d)s THEN 1 ELSE 0 END) after_n
                FROM `tabWork Actuals Employee` we
                INNER JOIN `tabWork Management Actuals` ac ON we.parent = ac.name
                WHERE IFNULL(we.count_in_payroll,0) = 1 AND IFNULL(we.paid,0) = 0
                GROUP BY ac.name, ac.task, ac.rate
                HAVING after_n > 0
            """, {"d": sd_from}, as_dict=True)
            sd_changed = []
            sd_mixed = []
            for sr in sd_rows:
                per = frappe.db.sql("""
                    SELECT rate, derived FROM `tabWork Task Rate`
                    WHERE task = %(t)s AND valid_from <= %(d)s
                      AND (valid_to IS NULL OR valid_to >= %(d)s)
                    ORDER BY valid_from DESC LIMIT 1
                """, {"t": sr.task, "d": sr.wto}, as_dict=True)
                if not per or not frappe.utils.cint(per[0].derived):
                    continue
                # Work Management Actuals.rate now holds 6dp, matching the period,
                # so compare at that precision.
                new_rate = frappe.utils.flt(per[0].rate, 6)
                if abs(new_rate - frappe.utils.flt(sr.cur_rate, 6)) <= 0.0000005:
                    continue
                entry = {"actuals": sr.actuals, "task": sr.task,
                         "old_rate": frappe.utils.flt(sr.cur_rate, 6), "new_rate": new_rate}
                if frappe.utils.cint(sr.before_n):
                    entry["rows_before"] = frappe.utils.cint(sr.before_n)
                    entry["rows_after"] = frappe.utils.cint(sr.after_n)
                    sd_mixed.append(entry)
                sd_changed.append(entry)
                if not sd_dry:
                    frappe.db.set_value("Work Management Actuals", sr.actuals, "rate",
                                        new_rate, update_modified=False)
            if not sd_dry:
                frappe.db.commit()
            out["dry_run"] = sd_dry
            out["docs_examined"] = len(sd_rows)
            out["docs_realigned"] = len(sd_changed)
            out["straddling_the_change"] = sd_mixed
            out["sample"] = sd_changed[:20]

    # ==================================================================
    # REVERSE — put every row a run touched back to its old value
    # ==================================================================
    elif action == "reverse":
        if not CAN_RATE:
            out["error"] = ("Only the general manager, the HR head or a System Manager "
                            "can change a rate.")
        else:
            rv_run = frappe.form_dict.get("run")
            if not rv_run:
                out["error"] = "run is required"
            elif not frappe.db.exists("Work Rate Recalc Run", rv_run):
                out["error"] = "no such run: " + str(rv_run)
            else:
                rv = frappe.get_doc("Work Rate Recalc Run", rv_run)
                if rv.status == "Reversed":
                    out["error"] = "run " + rv_run + " has already been reversed"
                else:
                    rv_parents = {}
                    rv_pays = {}
                    rv_n = 0
                    rv_plans = 0
                    rv_planners = 0
                    rv_periods = 0
                    rv_skipped = 0
                    for ln in rv.lines:
                        # A row is only put back when it still holds the new_amount /
                        # new_rate THIS run recorded. If a later run has moved it on
                        # since, restoring old_amount here would drag it to a stale
                        # figure -- skip and count it instead of reversing silently.
                        if ln.ref_doctype == "Work Actuals Employee":
                            rv_cur = frappe.db.get_value("Work Actuals Employee", ln.ref_name, "amount")
                            if rv_cur is None:
                                continue
                            if frappe.utils.flt(rv_cur, 2) != frappe.utils.flt(ln.new_amount, 2):
                                rv_skipped = rv_skipped + 1
                                continue
                            frappe.db.set_value("Work Actuals Employee", ln.ref_name, "amount",
                                                frappe.utils.flt(ln.old_amount), update_modified=False)
                            rv_parents[ln.ref_parent] = 1
                            rv_n = rv_n + 1
                        elif ln.ref_doctype == "Work Payment Line":
                            rv_cur = frappe.db.get_value("Work Payment Line", ln.ref_name, "amount")
                            if rv_cur is None:
                                continue
                            if frappe.utils.flt(rv_cur, 2) != frappe.utils.flt(ln.new_amount, 2):
                                rv_skipped = rv_skipped + 1
                                continue
                            frappe.db.set_value("Work Payment Line", ln.ref_name, "amount",
                                                frappe.utils.flt(ln.old_amount), update_modified=False)
                            rv_pays[ln.ref_parent] = 1
                            rv_n = rv_n + 1
                        elif ln.ref_doctype == "Work Management Master Plan Activity":
                            rv_cur = frappe.db.get_value("Work Management Master Plan Activity", ln.ref_name,
                                ["rate", "cost"], as_dict=True)
                            if not rv_cur:
                                continue
                            if frappe.utils.flt(rv_cur.rate, 6) != frappe.utils.flt(ln.new_rate, 6) or \
                               frappe.utils.flt(rv_cur.cost, 2) != frappe.utils.flt(ln.new_amount, 2):
                                rv_skipped = rv_skipped + 1
                                continue
                            frappe.db.set_value("Work Management Master Plan Activity", ln.ref_name,
                                                {"rate": frappe.utils.flt(ln.old_rate, 6),
                                                 "cost": frappe.utils.flt(ln.old_amount)},
                                                update_modified=False)
                            rv_n = rv_n + 1
                            rv_plans = rv_plans + 1
                        elif ln.ref_doctype == "Work Management Planner":
                            rv_cur = frappe.db.get_value("Work Management Planner", ln.ref_name,
                                ["rate", "total_cost"], as_dict=True)
                            if not rv_cur:
                                continue
                            if frappe.utils.flt(rv_cur.rate, 6) != frappe.utils.flt(ln.new_rate, 6) or \
                               frappe.utils.flt(rv_cur.total_cost, 2) != frappe.utils.flt(ln.new_amount, 2):
                                rv_skipped = rv_skipped + 1
                                continue
                            frappe.db.set_value("Work Management Planner", ln.ref_name,
                                                {"rate": frappe.utils.flt(ln.old_rate, 6),
                                                 "total_cost": frappe.utils.flt(ln.old_amount)},
                                                update_modified=False)
                            rv_n = rv_n + 1
                            rv_planners = rv_planners + 1
                        elif ln.ref_doctype == "Work Task Rate":
                            rv_cur = frappe.db.get_value("Work Task Rate", ln.ref_name, "rate")
                            if rv_cur is None:
                                continue
                            if frappe.utils.flt(rv_cur, 6) != frappe.utils.flt(ln.new_rate, 6):
                                rv_skipped = rv_skipped + 1
                                continue
                            frappe.db.set_value("Work Task Rate", ln.ref_name, "rate",
                                                frappe.utils.flt(ln.old_rate, 6), update_modified=False)
                            rv_period = frappe.db.get_value("Work Task Rate", ln.ref_name,
                                ["valid_from", "valid_to"], as_dict=True)
                            # only drag Task.custom_rate back when this period is the one
                            # covering today -- a historical period's reversal must not
                            # move today's mirrored rate.
                            if rv_period and str(rv_period.valid_from) <= str(frappe.utils.today()) and \
                               (not rv_period.valid_to or str(rv_period.valid_to) >= str(frappe.utils.today())):
                                frappe.db.set_value("Task", ln.task, "custom_rate",
                                                    frappe.utils.flt(ln.old_rate, 6), update_modified=False)
                            rv_n = rv_n + 1
                            rv_periods = rv_periods + 1
                    for pname in rv_parents:
                        tot = frappe.db.sql("""
                            SELECT COALESCE(SUM(amount),0) p FROM `tabWork Actuals Employee` WHERE parent = %s
                        """, (pname,), as_dict=True)
                        if tot:
                            frappe.db.set_value("Work Management Actuals", pname, "total_payment",
                                                frappe.utils.flt(tot[0].p), update_modified=False)
                    for pay in rv_pays:
                        tot = frappe.db.sql("""
                            SELECT COALESCE(SUM(amount),0) a FROM `tabWork Payment Line` WHERE parent = %s
                        """, (pay,), as_dict=True)
                        if tot:
                            frappe.db.set_value("Work Management Payment", pay, "amount",
                                                frappe.utils.flt(tot[0].a, 2), update_modified=False)
                    frappe.db.set_value("Work Rate Recalc Run", rv_run, {
                        "status": "Reversed",
                        "reversed_by": frappe.session.user,
                        "reversed_on": frappe.utils.now(),
                    })
                    frappe.db.commit()
                    out["run"] = rv_run
                    out["rows_reverted"] = rv_n
                    out["parents_resummed"] = len(rv_parents)
                    out["payments_resummed"] = len(rv_pays)
                    out["master_plans_reverted"] = rv_plans
                    out["planners_reverted"] = rv_planners
                    out["periods_reverted"] = rv_periods
                    out["rows_skipped"] = rv_skipped

    # ==================================================================
    # PERIODS — rate history for one task
    # ==================================================================
    elif action == "periods":
        p_task = frappe.form_dict.get("task")
        if not p_task:
            out["error"] = "task is required"
        else:
            out["task"] = p_task
            out["periods"] = frappe.db.sql("""
                SELECT name, valid_from, valid_to, rate, uom, daily_target,
                       daily_wage_basis, derived, source, source_activity, notes
                FROM `tabWork Task Rate` WHERE task = %s ORDER BY valid_from DESC
            """, (p_task,), as_dict=True)
            out["task_master"] = frappe.db.get_value(
                "Task", p_task, ["custom_rate", "custom_uom", "custom_daily_target"], as_dict=True)

    # ==================================================================
    # RATE META — what the Rates tab shows before you do anything
    # ==================================================================
    elif action == "rate_meta":
        out["can_edit"] = CAN_RATE
        out["tasks"] = frappe.db.sql("""
            SELECT t.name, t.subject, t.custom_uom uom, t.custom_daily_target daily_target,
                   t.custom_rate rate
            FROM `tabTask` t
            WHERE t.is_group = 0 AND IFNULL(t.project,'') IN ('PROJ-0031','PROJ-0032')
            ORDER BY t.subject
        """, as_dict=True)

    # ==================================================================
    # NEW RATE — the one write that is always safe: a new rate from a date
    #
    # A rate card: the old figure stays true for the days it applied to. Close the
    # period the day before and open a new one. Nothing recalculates.
    # ==================================================================
    elif action == "new_rate":
        nr_task = frappe.form_dict.get("task")
        nr_rate = frappe.utils.flt(frappe.form_dict.get("rate"), 6)
        nr_from = frappe.form_dict.get("effective_from")
        if not CAN_RATE:
            out["error"] = ("Only the general manager, the HR head or a System Manager "
                            "can change a rate.")
        elif not (nr_task and nr_from):
            out["error"] = "task and effective_from are required"
        elif nr_rate <= 0:
            out["error"] = "rate must be greater than zero"
        else:
            nr_cur = frappe.db.sql("""
                SELECT name, valid_from, valid_to FROM `tabWork Task Rate`
                WHERE task = %(t)s AND valid_from <= %(d)s
                  AND (valid_to IS NULL OR valid_to >= %(d)s)
                ORDER BY valid_from DESC LIMIT 1
            """, {"t": nr_task, "d": nr_from}, as_dict=True)
            if nr_cur and str(nr_cur[0].valid_from) == str(nr_from):
                out["error"] = ("A rate period already starts on " + str(nr_from) +
                                " (" + nr_cur[0].name + "). Correct that period instead.")
            else:
                nr_next = None
                if not nr_cur:
                    # effective_from predates every period the task has (or the task
                    # has none at all yet) -- the new period must not run past
                    # whichever period starts next, or the two would overlap once
                    # that later start date arrives.
                    nr_next = frappe.db.sql("""
                        SELECT name, valid_from FROM `tabWork Task Rate`
                        WHERE task = %(t)s AND valid_from > %(d)s
                        ORDER BY valid_from ASC LIMIT 1
                    """, {"t": nr_task, "d": nr_from}, as_dict=True)
                nr_closed = None
                if nr_cur:
                    frappe.db.set_value("Work Task Rate", nr_cur[0].name, "valid_to",
                                        frappe.utils.add_days(nr_from, -1))
                    nr_closed = nr_cur[0].name
                nr_ti = frappe.db.get_value("Task", nr_task,
                    ["custom_uom", "custom_daily_target"], as_dict=True)
                nr_doc = frappe.new_doc("Work Task Rate")
                nr_doc.task = nr_task
                nr_doc.valid_from = nr_from
                if nr_cur:
                    nr_doc.valid_to = nr_cur[0].valid_to if nr_cur[0].valid_to else None
                elif nr_next:
                    nr_doc.valid_to = frappe.utils.add_days(nr_next[0].valid_from, -1)
                else:
                    nr_doc.valid_to = None
                nr_doc.rate = nr_rate
                nr_doc.uom = nr_ti.custom_uom if nr_ti else None
                nr_doc.daily_target = frappe.utils.flt(nr_ti.custom_daily_target, 6) if nr_ti else 0
                nr_doc.derived = 0
                nr_doc.source = "Rates tab — new rate"
                nr_doc.flags.ignore_permissions = True
                nr_doc.insert(ignore_permissions=True)
                # Only mirror onto the Task master when the period just written is
                # the one actually in force today -- a historical insert that ends
                # before today, or a future-dated one, must not overwrite it.
                nr_today = frappe.utils.today()
                if (str(nr_doc.valid_from) <= str(nr_today) and
                        (not nr_doc.valid_to or str(nr_doc.valid_to) >= str(nr_today))):
                    frappe.db.set_value("Task", nr_task, "custom_rate", nr_rate)
                frappe.db.commit()
                out["closed"] = nr_closed
                out["created"] = nr_doc.name

    # ==================================================================
    # CORRECT PREVIEW — the impact list a correction has to pass first
    #
    # A rate card is not an edit: the old figure stays true for the days it
    # applied to (new_rate handles that). A correction is different — the number
    # was simply wrong, so everything priced from that period is wrong too,
    # whatever state it has reached. This computes and reports what amending the
    # period IN PLACE would touch. It writes nothing; Task 6 applies it.
    # ==================================================================
    elif action == "correct_preview":
        cp_period = frappe.form_dict.get("period")
        cp_rate = frappe.utils.flt(frappe.form_dict.get("rate"), 6)
        cp_p = frappe.db.get_value("Work Task Rate", cp_period,
            ["name", "task", "rate", "valid_from", "valid_to"], as_dict=True)
        if not CAN_RATE:
            out["error"] = ("Only the general manager, the HR head or a System Manager "
                            "can change a rate.")
        elif not cp_p:
            out["error"] = "no such rate period: " + str(cp_period)
        elif cp_rate <= 0:
            out["error"] = "rate must be greater than zero"
        else:
            cp_to = cp_p.valid_to or "2999-12-31"
            cp_args = {"t": cp_p.task, "f": str(cp_p.valid_from), "e": str(cp_to)}
            out["period"] = cp_p.name
            out["task"] = cp_p.task
            out["old_rate"] = frappe.utils.flt(cp_p.rate, 6)
            out["new_rate"] = cp_rate
            out["valid_from"] = str(cp_p.valid_from)
            out["valid_to"] = str(cp_p.valid_to) if cp_p.valid_to else None

            # master plan lines whose budget period starts inside the corrected window
            out["master_plans"] = frappe.db.sql("""
                SELECT a.name row, a.parent plan, a.task, a.work_qty qty, a.cost old_cost,
                       mp.farm, mp.workflow_state state
                FROM `tabWork Management Master Plan Activity` a
                INNER JOIN `tabWork Management Master Plan` mp ON mp.name = a.parent
                WHERE a.task = %(t)s AND IFNULL(mp.workflow_state,'') != 'Rejected'
                  AND mp.period_from <= %(e)s AND mp.period_to >= %(f)s
                ORDER BY mp.period_from DESC
            """, cp_args, as_dict=True)
            for cm in out["master_plans"]:
                cm["new_cost"] = frappe.utils.flt(frappe.utils.flt(cm.qty) * cp_rate, 2)

            # planner requests overlapping the window
            cp_pl = frappe.db.sql("""
                SELECT COUNT(*) n, COALESCE(SUM(total_cost),0) old_total,
                       COALESCE(SUM(quantity),0) qty
                FROM `tabWork Management Planner`
                WHERE task = %(t)s AND IFNULL(workflow_state,'') != 'Rejected'
                  AND from_date <= %(e)s AND to_date >= %(f)s
            """, cp_args, as_dict=True)[0]
            out["planners"] = {"rows": frappe.utils.cint(cp_pl.n),
                               "old_total": frappe.utils.flt(cp_pl.old_total, 2),
                               "new_total": frappe.utils.flt(frappe.utils.flt(cp_pl.qty) * cp_rate, 2)}

            # confirmed day-rows in the window that are NOT already paid
            cp_ac = frappe.db.sql("""
                SELECT COUNT(*) n, COALESCE(SUM(we.amount),0) old_total,
                       COALESCE(SUM(we.actual_quantity),0) qty
                FROM `tabWork Actuals Employee` we
                INNER JOIN `tabWork Management Actuals` ac ON we.parent = ac.name
                LEFT JOIN `tabWork Management Payment` p ON p.name = we.payment_ref
                WHERE ac.task = %(t)s AND we.work_date >= %(f)s AND we.work_date <= %(e)s
                  AND IFNULL(we.paid,0) = 0
                  AND (we.payment_ref IS NULL OR IFNULL(we.payment_ref,'') = ''
                       OR p.name IS NULL OR IFNULL(p.workflow_state,'') = 'Cancelled')
            """, cp_args, as_dict=True)[0]
            out["actuals"] = {"rows": frappe.utils.cint(cp_ac.n),
                              "old_total": frappe.utils.flt(cp_ac.old_total, 2),
                              "new_total": frappe.utils.flt(frappe.utils.flt(cp_ac.qty) * cp_rate, 2)}

            # and the ones that are untouchable, so they are visible rather than absent
            cp_lk = frappe.db.sql("""
                SELECT COUNT(*) n, COALESCE(SUM(we.amount),0) total
                FROM `tabWork Actuals Employee` we
                INNER JOIN `tabWork Management Actuals` ac ON we.parent = ac.name
                LEFT JOIN `tabWork Management Payment` p ON p.name = we.payment_ref
                WHERE ac.task = %(t)s AND we.work_date >= %(f)s AND we.work_date <= %(e)s
                  AND (IFNULL(we.paid,0) = 1
                       OR (IFNULL(we.payment_ref,'') != '' AND p.name IS NOT NULL
                           AND IFNULL(p.workflow_state,'') != 'Cancelled'))
            """, cp_args, as_dict=True)[0]
            out["locked"] = {"rows": frappe.utils.cint(cp_lk.n),
                             "total": frappe.utils.flt(cp_lk.total, 2)}

    # ==================================================================
    # CORRECT APPLY — do exactly what correct_preview promised, and record it
    #
    # Only the master plan lines that were ticked, plus planner requests and
    # actuals rows if their groups were ticked, then the rate period itself.
    # Paid actuals are excluded by the SAME predicate correct_preview used for
    # its changeable-rows query, so apply can never re-price what the preview
    # said was untouchable. Every row is logged on a Work Rate Recalc Run so
    # wm_rates' "reverse" action can undo it in one step.
    # ==================================================================
    elif action == "correct_apply":
        ca_period = frappe.form_dict.get("period")
        ca_rate = frappe.utils.flt(frappe.form_dict.get("rate"), 6)
        ca_rows = json.loads(frappe.form_dict.get("plan_rows") or "[]")
        ca_do_pl = frappe.utils.cint(frappe.form_dict.get("do_planners"))
        ca_do_ac = frappe.utils.cint(frappe.form_dict.get("do_actuals"))
        ca_p = frappe.db.get_value("Work Task Rate", ca_period,
            ["name", "task", "rate", "valid_from", "valid_to"], as_dict=True)
        if not CAN_RATE:
            out["error"] = ("Only the general manager, the HR head or a System Manager "
                            "can change a rate.")
        elif not ca_p:
            out["error"] = "no such rate period: " + str(ca_period)
        elif ca_rate <= 0:
            out["error"] = "rate must be greater than zero"
        else:
            ca_to = ca_p.valid_to or "2999-12-31"
            ca_args = {"t": ca_p.task, "f": str(ca_p.valid_from), "e": str(ca_to)}
            ca_run = frappe.new_doc("Work Rate Recalc Run")
            ca_run.status = "Applied"
            ca_run.from_date = ca_p.valid_from
            ca_run.to_date = ca_p.valid_to
            ca_run.dry_run = 0
            ca_run.executed_by = frappe.session.user
            ca_run.executed_on = frappe.utils.now()
            ca_old = 0
            ca_new = 0
            ca_n = 0
            ca_skipped_rows = 0

            for ca_r in ca_rows:
                # A row is only priced here if it still qualifies under the SAME
                # state-and-window filter correct_preview used to offer it: not on
                # a Rejected plan, and the plan's budget period overlaps the
                # corrected window. Ticking a row correct_preview never offered
                # must not silently re-price it.
                ca_qargs = {"t": ca_p.task, "f": ca_args["f"], "e": ca_args["e"], "r": ca_r}
                ca_a_rows = frappe.db.sql("""
                    SELECT a.name, a.parent, a.task, a.work_qty, a.cost
                    FROM `tabWork Management Master Plan Activity` a
                    INNER JOIN `tabWork Management Master Plan` mp ON mp.name = a.parent
                    WHERE a.name = %(r)s AND a.task = %(t)s
                      AND IFNULL(mp.workflow_state,'') != 'Rejected'
                      AND mp.period_from <= %(e)s AND mp.period_to >= %(f)s
                """, ca_qargs, as_dict=True)
                if not ca_a_rows:
                    ca_skipped_rows = ca_skipped_rows + 1
                    continue
                ca_a = ca_a_rows[0]
                ca_nc = frappe.utils.flt(frappe.utils.flt(ca_a.work_qty) * ca_rate, 2)
                ln = ca_run.append("lines", {})
                ln.ref_doctype = "Work Management Master Plan Activity"
                ln.ref_name = ca_a.name
                ln.ref_parent = ca_a.parent
                ln.task = ca_a.task
                ln.old_rate = frappe.utils.flt(ca_p.rate, 6)
                ln.new_rate = ca_rate
                ln.old_amount = frappe.utils.flt(ca_a.cost)
                ln.new_amount = ca_nc
                frappe.db.set_value("Work Management Master Plan Activity", ca_a.name,
                                    {"rate": ca_rate, "cost": ca_nc})
                ca_old = ca_old + frappe.utils.flt(ca_a.cost)
                ca_new = ca_new + ca_nc
                ca_n = ca_n + 1

            if ca_do_pl:
                for ca_pl in frappe.db.sql("""
                    SELECT name, quantity, total_cost FROM `tabWork Management Planner`
                    WHERE task = %(t)s AND IFNULL(workflow_state,'') != 'Rejected'
                      AND from_date <= %(e)s AND to_date >= %(f)s
                """, ca_args, as_dict=True):
                    ca_nc = frappe.utils.flt(frappe.utils.flt(ca_pl.quantity) * ca_rate, 2)
                    ln = ca_run.append("lines", {})
                    ln.ref_doctype = "Work Management Planner"
                    ln.ref_name = ca_pl.name
                    ln.task = ca_p.task
                    ln.old_rate = frappe.utils.flt(ca_p.rate, 6)
                    ln.new_rate = ca_rate
                    ln.old_amount = frappe.utils.flt(ca_pl.total_cost)
                    ln.new_amount = ca_nc
                    frappe.db.set_value("Work Management Planner", ca_pl.name,
                                        {"rate": ca_rate, "total_cost": ca_nc})
                    ca_old = ca_old + frappe.utils.flt(ca_pl.total_cost)
                    ca_new = ca_new + ca_nc
                    ca_n = ca_n + 1

            ca_ac_parents = {}
            if ca_do_ac:
                for ca_we in frappe.db.sql("""
                    SELECT we.name, we.parent, we.employee, we.work_date,
                           we.actual_quantity qty, we.amount
                    FROM `tabWork Actuals Employee` we
                    INNER JOIN `tabWork Management Actuals` ac ON we.parent = ac.name
                    LEFT JOIN `tabWork Management Payment` p ON p.name = we.payment_ref
                    WHERE ac.task = %(t)s AND we.work_date >= %(f)s AND we.work_date <= %(e)s
                      AND IFNULL(we.paid,0) = 0
                      AND (we.payment_ref IS NULL OR IFNULL(we.payment_ref,'') = ''
                           OR p.name IS NULL OR IFNULL(p.workflow_state,'') = 'Cancelled')
                """, ca_args, as_dict=True):
                    ca_na = frappe.utils.flt(frappe.utils.flt(ca_we.qty) * ca_rate, 2)
                    ln = ca_run.append("lines", {})
                    ln.ref_doctype = "Work Actuals Employee"
                    ln.ref_name = ca_we.name
                    ln.ref_parent = ca_we.parent
                    ln.task = ca_p.task
                    ln.employee = ca_we.employee
                    ln.work_date = ca_we.work_date
                    ln.old_rate = frappe.utils.flt(ca_p.rate, 6)
                    ln.new_rate = ca_rate
                    ln.old_amount = frappe.utils.flt(ca_we.amount)
                    ln.new_amount = ca_na
                    frappe.db.set_value("Work Actuals Employee", ca_we.name, "amount", ca_na)
                    ca_ac_parents[ca_we.parent] = 1
                    ca_old = ca_old + frappe.utils.flt(ca_we.amount)
                    ca_new = ca_new + ca_na
                    ca_n = ca_n + 1

                # re-sum every parent Actuals doc touched, same as reverse already
                # does -- otherwise total_payment keeps the pre-correction sum while
                # its children hold the corrected one.
                for ca_pname in ca_ac_parents:
                    ca_tot = frappe.db.sql("""
                        SELECT COALESCE(SUM(amount),0) p FROM `tabWork Actuals Employee` WHERE parent = %s
                    """, (ca_pname,), as_dict=True)
                    if ca_tot:
                        frappe.db.set_value("Work Management Actuals", ca_pname, "total_payment",
                                            frappe.utils.flt(ca_tot[0].p), update_modified=False)

            # the period itself, and the Task master when this period is the one in force
            # -- recorded as its own line (no amount: a rate period isn't money) so
            # reverse can put the period back, not just the rows priced from it.
            ln = ca_run.append("lines", {})
            ln.ref_doctype = "Work Task Rate"
            ln.ref_name = ca_p.name
            ln.task = ca_p.task
            ln.old_rate = frappe.utils.flt(ca_p.rate, 6)
            ln.new_rate = ca_rate
            ln.old_amount = 0
            ln.new_amount = 0

            frappe.db.set_value("Work Task Rate", ca_p.name, "rate", ca_rate)
            if str(ca_p.valid_from) <= str(frappe.utils.today()) and \
               (not ca_p.valid_to or str(ca_p.valid_to) >= str(frappe.utils.today())):
                frappe.db.set_value("Task", ca_p.task, "custom_rate", ca_rate)

            ca_run.rows_changed = ca_n
            ca_run.rows_skipped = ca_skipped_rows
            ca_run.old_total = ca_old
            ca_run.new_total = ca_new
            ca_run.delta = ca_new - ca_old
            ca_run.summary = ("Corrected " + str(ca_p.task) + " from " +
                              str(frappe.utils.flt(ca_p.rate, 6)) + " to " + str(ca_rate) +
                              " for " + str(ca_p.valid_from) + " to " +
                              str(ca_p.valid_to or "open"))
            ca_run.flags.ignore_permissions = True
            ca_run.insert(ignore_permissions=True)
            frappe.db.commit()
            out["run"] = ca_run.name
            out["changed"] = ca_n
            out["delta"] = ca_run.delta
            out["skipped_plan_rows"] = ca_skipped_rows
            out["parents_resummed"] = len(ca_ac_parents)

    # ==================================================================
    # UNIT CHANGE PREVIEW — what changing a task's unit would mean
    #
    # Changing the unit changes what a quantity MEANS. Nothing may be converted
    # automatically, because only a person knows that a Day is eight Hours here.
    # Writes nothing.
    # ==================================================================
    elif action == "unit_change_preview":
        uc_task = frappe.form_dict.get("task")
        uc_uom = frappe.form_dict.get("uom")
        uc_tgt = frappe.utils.flt(frappe.form_dict.get("daily_target"), 6)
        uc_t = frappe.db.get_value("Task", uc_task,
            ["custom_uom", "custom_daily_target", "custom_rate"], as_dict=True)
        if not CAN_RATE:
            out["error"] = ("Only the general manager, the HR head or a System Manager "
                            "can change a rate.")
        elif not uc_t:
            out["error"] = "no such task: " + str(uc_task)
        elif not uc_uom or uc_tgt <= 0:
            out["error"] = "uom and a daily target greater than zero are required"
        else:
            uc_basis = frappe.utils.flt(uc_t.custom_rate) * frappe.utils.flt(uc_t.custom_daily_target)
            out["task"] = uc_task
            out["old_uom"] = uc_t.custom_uom
            out["new_uom"] = uc_uom
            out["old_target"] = frappe.utils.flt(uc_t.custom_daily_target, 6)
            out["new_target"] = uc_tgt
            out["daily_basis"] = frappe.utils.flt(uc_basis, 6)
            out["derived_rate"] = frappe.utils.flt(uc_basis / uc_tgt, 6) if uc_tgt else 0
            out["affected"] = {
                "master_plan_lines": frappe.db.sql("""
                    SELECT COUNT(*) n FROM `tabWork Management Master Plan Activity` a
                    INNER JOIN `tabWork Management Master Plan` mp ON mp.name = a.parent
                    WHERE a.task = %(t)s AND mp.workflow_state != 'Rejected'
                """, {"t": uc_task}, as_dict=True)[0].n,
                "planners": frappe.db.sql("""
                    SELECT COUNT(*) n FROM `tabWork Management Planner`
                    WHERE task = %(t)s AND IFNULL(workflow_state,'') != 'Rejected'
                """, {"t": uc_task}, as_dict=True)[0].n,
                "actuals": frappe.db.sql("""
                    SELECT COUNT(*) n FROM `tabWork Management Actuals` WHERE task = %(t)s
                """, {"t": uc_task}, as_dict=True)[0].n}

    # ==================================================================
    # UNIT CHANGE APPLY — open a new rate period in the new unit
    #
    # Opens a new rate period in the new unit from today. Quantities are converted
    # only when a factor is given, and never guessed.
    # ==================================================================
    elif action == "unit_change_apply":
        ua_task = frappe.form_dict.get("task")
        ua_uom = frappe.form_dict.get("uom")
        ua_tgt = frappe.utils.flt(frappe.form_dict.get("daily_target"), 6)
        ua_factor = frappe.utils.flt(frappe.form_dict.get("factor"))
        ua_t = frappe.db.get_value("Task", ua_task,
            ["custom_uom", "custom_daily_target", "custom_rate"], as_dict=True)
        if not CAN_RATE:
            out["error"] = ("Only the general manager, the HR head or a System Manager "
                            "can change a rate.")
        elif not ua_t:
            out["error"] = "no such task: " + str(ua_task)
        elif not ua_uom or ua_tgt <= 0:
            out["error"] = "uom and a daily target greater than zero are required"
        else:
            ua_basis = frappe.utils.flt(ua_t.custom_rate) * frappe.utils.flt(ua_t.custom_daily_target)
            ua_rate = frappe.utils.flt(ua_basis / ua_tgt, 6)
            ua_today = frappe.utils.today()
            ua_cur = frappe.db.sql("""
                SELECT name, valid_from, valid_to FROM `tabWork Task Rate`
                WHERE task = %(t)s AND valid_from <= %(d)s
                  AND (valid_to IS NULL OR valid_to >= %(d)s)
                ORDER BY valid_from DESC LIMIT 1
            """, {"t": ua_task, "d": ua_today}, as_dict=True)
            ua_notes = ("Unit changed from " + str(ua_t.custom_uom) + " at " +
                        str(frappe.utils.flt(ua_t.custom_daily_target, 6)) + "/day to " +
                        str(ua_uom) + " at " + str(ua_tgt) + "/day")
            if ua_cur and str(ua_cur[0].valid_from) == str(ua_today):
                # the period in force already STARTS today -- nothing has ever been
                # priced against it, so closing it at yesterday would put valid_to
                # before valid_from (unreachable forever, and a gap over yesterday).
                # Amend it in place instead; there is no history to preserve.
                frappe.db.set_value("Work Task Rate", ua_cur[0].name, {
                    "uom": ua_uom, "daily_target": ua_tgt, "rate": ua_rate,
                    "daily_wage_basis": frappe.utils.flt(ua_basis, 6),
                    "derived": 1, "notes": ua_notes})
                ua_created = ua_cur[0].name
            else:
                if ua_cur:
                    frappe.db.set_value("Work Task Rate", ua_cur[0].name, "valid_to",
                                        frappe.utils.add_days(ua_today, -1))
                ua_doc = frappe.new_doc("Work Task Rate")
                ua_doc.task = ua_task
                ua_doc.valid_from = ua_today
                ua_doc.valid_to = None
                ua_doc.rate = ua_rate
                ua_doc.uom = ua_uom
                ua_doc.daily_target = ua_tgt
                ua_doc.daily_wage_basis = frappe.utils.flt(ua_basis, 6)
                ua_doc.derived = 1
                ua_doc.source = "Rates tab — unit change"
                ua_doc.notes = ua_notes
                ua_doc.flags.ignore_permissions = True
                ua_doc.insert(ignore_permissions=True)
                ua_created = ua_doc.name
            frappe.db.set_value("Task", ua_task,
                {"custom_uom": ua_uom, "custom_daily_target": ua_tgt, "custom_rate": ua_rate})
            ua_conv = 0
            if ua_factor > 0:
                for ua_a in frappe.db.sql("""
                    SELECT a.name, a.work_qty FROM `tabWork Management Master Plan Activity` a
                    INNER JOIN `tabWork Management Master Plan` mp ON mp.name = a.parent
                    WHERE a.task = %(t)s AND mp.workflow_state IN ('Draft','Rejected')
                """, {"t": ua_task}, as_dict=True):
                    ua_q = frappe.utils.flt(ua_a.work_qty) * ua_factor
                    frappe.db.set_value("Work Management Master Plan Activity", ua_a.name,
                        {"work_qty": ua_q, "uom": ua_uom,
                         "cost": frappe.utils.flt(ua_q * ua_rate, 2), "rate": ua_rate})
                    ua_conv = ua_conv + 1
            frappe.db.commit()
            out["created"] = ua_created
            out["rate"] = ua_rate
            out["converted"] = ua_conv

    else:
        out["error"] = "unknown action: " + str(action)

    return out
