# Ported from Kaitet live Server Script "wm_rates" (API) — logic unchanged.
# Farms / projects / company / approver roles now come from Work Management Settings
# (falls back to the original Kaitet defaults) — see upande_work_management/api/config.py.
# REGENERATED by kaitet-work-management/port_app.py — edit the mirror script, not this file.

import frappe

from upande_work_management.api.config import get_config


@frappe.whitelist()
def wm_rates(**kwargs):
    _cfg = get_config()
    FARM_PROJECT = _cfg["farm_project"]
    DEFAULT_COMPANY = _cfg["default_company"]
    FARMS = _cfg["farms"]
    BLOCK_EXCLUDE = _cfg["block_exclude"]
    FARM_APPROVER_ROLE = _cfg["farm_approver_role"]

    # ==================================================================
    # SERVER SCRIPT — "WM Rates" (API, api_method=wm_rates)
    # Effective-dated task rates + wage recalculation.
    #
    # Rate history lives in "Work Task Rate": one row per task per period,
    # never overlapping, at most one left open (valid_to empty = active today).
    # Task.custom_rate / custom_uom / custom_daily_target are MIRRORED from the
    # active period, so the planner (wm_planner) keeps reading Task exactly as
    # it always has.
    #
    # On the live site these are CUSTOM doctypes and therefore have no Python
    # controller, so every invariant (close-previous, no-overlap, mirror-to-Task)
    # is enforced here. The packaged app enforces the same rules in
    # work_task_rate.py — keep the two in step.
    #
    # No def/return allowed in the sandbox, so everything is inline.
    # ==================================================================

    # Daily wage tiers that legitimately existed before the 2026-07-21 rate card.
    # 340 is the general wage; 350 is a distinct tier covering packhouse, greenhouse,
    # QC and reliever work. Both rise to 387, so both count as wage-derived — a task
    # is measured against whichever tier it sits closest to.
    LEGACY_DAILY_WAGE = 340.0
    KNOWN_DAILY_WAGES = [340.0, 350.0]

    # Within 1% of the wage -> wage-derived outright.
    # Within 10% -> borderline, needs a human decision and is NEVER auto-applied.
    # The old 1% band silently excluded Planting grass (4.6 x 75 = 345/day) which
    # really is 340-derived: the true rate is 340/75 = 4.5333 and someone rounded up.
    # Bands are inclusive; the epsilon absorbs float error at the exact edge
    # (340 * 1.10 evaluates to 374.00000000000006).
    EXACT_BAND = 0.01
    REVIEW_BAND = 0.10
    BAND_EPSILON = 0.000001

    # Rows revalued per call. Repeat until "remaining" comes back 0.
    CHUNK = 800

    action = frappe.form_dict.get("action") or "meta"
    out = {}

    # ==================================================================
    # META — what the Settings screen shows before you do anything
    # ==================================================================
    if action == "meta":
        today = frappe.utils.today()
        out["today"] = today
        out["legacy_daily_wage"] = LEGACY_DAILY_WAGE
        out["tasks_with_rate"] = frappe.db.count("Task", {"custom_rate": [">", 0]})
        out["periods"] = frappe.db.count("Work Task Rate")
        out["tasks_covered"] = len(frappe.db.sql_list("SELECT DISTINCT task FROM `tabWork Task Rate`"))
        wages = frappe.db.sql("""
            SELECT daily_wage_basis wage, COUNT(*) n
            FROM `tabWork Task Rate`
            WHERE valid_from <= %s AND (valid_to IS NULL OR valid_to >= %s)
              AND IFNULL(daily_wage_basis,0) > 0
            GROUP BY daily_wage_basis ORDER BY n DESC
        """, (today, today), as_dict=True)
        out["active_wages"] = wages
        out["current_daily_wage"] = frappe.utils.flt(wages[0].wage) if wages else None
        out["borderline_pending"] = frappe.db.count(
            "Work Task Rate", {"derived": 0, "notes": ["like", "Borderline:%"]}
        )
        last = frappe.db.get_all("Work Rate Recalc Run",
            fields=["name", "status", "from_date", "dry_run", "rows_changed", "delta",
                    "executed_by", "executed_on"],
            order_by="creation desc", limit=1)
        out["last_run"] = last[0] if last else None

    # ==================================================================
    # BACKFILL — give every rated Task one open period holding today's values
    # ==================================================================
    elif action == "backfill":
        bf_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        bf_wage = frappe.utils.flt(frappe.form_dict.get("wage") or 0)
        bf_tiers = [bf_wage] if bf_wage else KNOWN_DAILY_WAGES
        bf_epoch = frappe.form_dict.get("epoch")
        if not bf_epoch:
            # history has to start no later than the earliest plan, or the recalc
            # would meet work it cannot price and refuse to run
            earliest = frappe.db.sql("""
                SELECT MIN(from_date) d FROM `tabWork Management Planner` WHERE from_date IS NOT NULL
            """, as_dict=True)
            bf_epoch = str(earliest[0].d) if earliest and earliest[0].d else frappe.utils.today()

        bf_tasks = frappe.db.sql("""
            SELECT name, custom_rate rate, custom_uom uom, custom_daily_target tgt
            FROM `tabTask` WHERE IFNULL(custom_rate,0) > 0
        """, as_dict=True)
        bf_have = {}
        for t in frappe.db.sql_list("SELECT DISTINCT task FROM `tabWork Task Rate`"):
            bf_have[t] = 1

        bf_created = 0
        bf_skipped = 0
        bf_counts = {"derived": 0, "borderline": 0, "not_derived": 0, "unknown": 0}
        for t in bf_tasks:
            if bf_have.get(t.name):
                bf_skipped = bf_skipped + 1
                continue
            r = frappe.utils.flt(t.rate)
            g = frappe.utils.flt(t.tgt)
            if not r or not g:
                verdict = "unknown"
                implied = 0
            else:
                implied = r * g
                matched = bf_tiers[0]
                for w in bf_tiers:
                    if abs(implied - w) < abs(implied - matched):
                        matched = w
                drift = abs(implied - matched)
                if drift <= matched * EXACT_BAND + BAND_EPSILON:
                    verdict = "derived"
                elif drift <= matched * REVIEW_BAND + BAND_EPSILON:
                    verdict = "borderline"
                else:
                    verdict = "not_derived"
            bf_counts[verdict] = bf_counts[verdict] + 1
            bf_created = bf_created + 1
            if bf_dry:
                continue

            note = None
            if verdict == "borderline":
                note = ("Borderline: implied daily wage " + str(round(implied, 2)) +
                        " against nearest tier " + str(matched) + ". Confirm whether this "
                        "rate is wage-derived before recalculating.")
            elif verdict == "not_derived":
                note = ("Not wage-derived: implied daily wage " + str(round(implied, 2)) +
                        ". Excluded from wage recalculations.")
            elif verdict == "unknown":
                note = "No usable rate or daily target on the Task."

            d = frappe.new_doc("Work Task Rate")
            d.task = t.name
            d.valid_from = bf_epoch
            # legacy rate kept EXACTLY as stored, rounding and all — this is what
            # was actually used to pay people; rewriting it would falsify history
            d.rate = r
            d.uom = t.uom
            d.daily_target = g
            d.daily_wage_basis = matched if verdict == "derived" else None
            d.derived = 1 if verdict == "derived" else 0
            d.source = "backfill from Task master"
            d.notes = note
            d.flags.ignore_permissions = True
            d.insert(ignore_permissions=True)
            if bf_created % 200 == 0:
                frappe.db.commit()

        if not bf_dry:
            frappe.db.commit()
        out["epoch"] = str(bf_epoch)
        out["dry_run"] = bf_dry
        out["tasks_considered"] = len(bf_tasks)
        out["periods_created"] = bf_created
        out["already_covered"] = bf_skipped
        out["classification"] = bf_counts
        out["tiers"] = bf_tiers

    # ==================================================================
    # BORDERLINE — tasks whose classification a human has to settle
    # ==================================================================
    elif action == "borderline":
        bl = frappe.db.sql("""
            SELECT wtr.name, wtr.task, wtr.rate, wtr.daily_target, wtr.uom,
                   wtr.valid_from, wtr.valid_to, wtr.notes
            FROM `tabWork Task Rate` wtr
            WHERE IFNULL(wtr.derived,0) = 0 AND IFNULL(wtr.notes,'') LIKE 'Borderline:%'
            ORDER BY wtr.task
        """, as_dict=True)
        for b in bl:
            b["implied_daily_wage"] = frappe.utils.flt(
                frappe.utils.flt(b.rate) * frappe.utils.flt(b.daily_target), 2)
            b["rows_since_change"] = frappe.db.sql("""
                SELECT COUNT(*) n FROM `tabWork Actuals Employee` we
                INNER JOIN `tabWork Management Actuals` ac ON we.parent = ac.name
                WHERE ac.task = %s AND IFNULL(we.paid,0) = 0 AND IFNULL(we.amount,0) > 0
            """, (b.task,), as_dict=True)[0].n
        out["borderline"] = bl

    elif action == "classify":
        # Record a decision on borderline periods: derived 1/0, once and for all.
        # Accepts one name, or a CSV of names so a whole review round settles in a
        # single call. wage="implied" records each period's own rate x daily_target
        # as its basis, which is the honest answer for a task that sat on its own
        # odd wage (345, 360, 320) rather than a shared tier.
        c_raw = frappe.form_dict.get("names") or frappe.form_dict.get("name") or ""
        c_derived = frappe.utils.cint(frappe.form_dict.get("derived"))
        c_wage_in = frappe.form_dict.get("wage")
        c_names = []
        for c in str(c_raw).split(","):
            cv = c.strip()
            if cv and cv not in c_names:
                c_names.append(cv)
        if not c_names:
            out["error"] = "name or names is required"
        else:
            c_done = []
            c_missing = []
            for cn in c_names:
                row = frappe.db.get_value("Work Task Rate", cn,
                    ["name", "task", "rate", "daily_target"], as_dict=True)
                if not row:
                    c_missing.append(cn)
                    continue
                if not c_derived:
                    c_basis = None
                elif str(c_wage_in or "").lower() == "implied":
                    c_basis = frappe.utils.flt(
                        frappe.utils.flt(row.rate) * frappe.utils.flt(row.daily_target), 6)
                else:
                    c_basis = frappe.utils.flt(c_wage_in or LEGACY_DAILY_WAGE)
                frappe.db.set_value("Work Task Rate", cn, {
                    "derived": 1 if c_derived else 0,
                    "daily_wage_basis": c_basis,
                    "notes": ("Confirmed wage-derived (basis " + str(c_basis) + ") by "
                              if c_derived else "Confirmed NOT wage-derived by ") +
                             frappe.session.user + " on " + frappe.utils.today(),
                })
                c_done.append({"name": cn, "task": row.task, "basis": c_basis})
            frappe.db.commit()
            out["classified"] = c_done
            out["missing"] = c_missing
            out["derived"] = 1 if c_derived else 0

    # ==================================================================
    # APPLY WAGE — write the new wage's periods from an effective date
    # Pure uplift: rate = new_wage / existing daily_target, unit and target
    # carried over unchanged. Target/UOM revisions are a separate, forward-only
    # change and are deliberately NOT written here.
    # ==================================================================
    elif action == "apply_wage":
        aw_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        aw_wage = frappe.utils.flt(frappe.form_dict.get("wage") or 0)
        aw_from = frappe.form_dict.get("effective_from")
        aw_source = frappe.form_dict.get("source") or ("Rate card " + str(aw_from))
        if not aw_wage or not aw_from:
            out["error"] = "wage and effective_from are required"
        else:
            aw_day_before = frappe.utils.add_days(aw_from, -1)
            # every task whose period in force the day before is wage-derived
            aw_rows = frappe.db.sql("""
                SELECT wtr.name period, wtr.task, wtr.rate, wtr.uom, wtr.daily_target,
                       wtr.daily_wage_basis, wtr.valid_from, wtr.valid_to
                FROM `tabWork Task Rate` wtr
                WHERE wtr.derived = 1
                  AND wtr.valid_from <= %(d)s
                  AND (wtr.valid_to IS NULL OR wtr.valid_to >= %(d)s)
            """, {"d": aw_day_before}, as_dict=True)

            aw_existing = {}
            for e in frappe.db.sql("""
                SELECT task FROM `tabWork Task Rate` WHERE valid_from = %s
            """, (aw_from,), as_dict=True):
                aw_existing[e.task] = 1

            aw_made = 0
            aw_skipped = []
            aw_preview = []
            for r in aw_rows:
                if aw_existing.get(r.task):
                    aw_skipped.append({"task": r.task, "why": "a period already starts on " + str(aw_from)})
                    continue
                tgt = frappe.utils.flt(r.daily_target)
                if not tgt:
                    aw_skipped.append({"task": r.task, "why": "no daily target"})
                    continue
                new_rate = aw_wage / tgt
                aw_preview.append({
                    "task": r.task, "uom": r.uom, "daily_target": tgt,
                    "old_rate": frappe.utils.flt(r.rate, 6),
                    "new_rate": frappe.utils.flt(new_rate, 6),
                })
                aw_made = aw_made + 1
                if aw_dry:
                    continue

                d = frappe.new_doc("Work Task Rate")
                d.task = r.task
                d.valid_from = aw_from
                d.rate = new_rate
                d.uom = r.uom
                d.daily_target = tgt
                d.daily_wage_basis = aw_wage
                d.derived = 1
                d.source = aw_source
                d.flags.ignore_permissions = True
                d.insert(ignore_permissions=True)
                # CUSTOM doctype on live = no controller, so close the superseded
                # period and mirror onto Task right here
                frappe.db.sql("""
                    UPDATE `tabWork Task Rate` SET valid_to = %(prev_end)s
                    WHERE task = %(task)s AND name != %(me)s AND valid_to IS NULL
                      AND valid_from < %(vfrom)s
                """, {"prev_end": aw_day_before, "task": r.task, "me": d.name, "vfrom": aw_from})
                if aw_made % 100 == 0:
                    frappe.db.commit()

            if not aw_dry:
                # mirror whichever period is active TODAY onto each Task
                for r in aw_rows:
                    act = frappe.db.sql("""
                        SELECT rate, uom, daily_target FROM `tabWork Task Rate`
                        WHERE task = %(t)s AND valid_from <= %(today)s
                          AND (valid_to IS NULL OR valid_to >= %(today)s)
                        ORDER BY valid_from DESC LIMIT 1
                    """, {"t": r.task, "today": frappe.utils.today()}, as_dict=True)
                    if act:
                        frappe.db.set_value("Task", r.task, {
                            "custom_rate": frappe.utils.flt(act[0].rate),
                            "custom_uom": act[0].uom,
                            "custom_daily_target": frappe.utils.flt(act[0].daily_target),
                        })
                frappe.db.commit()

            out["dry_run"] = aw_dry
            out["wage"] = aw_wage
            out["effective_from"] = aw_from
            out["periods_written"] = aw_made
            out["skipped"] = aw_skipped
            out["preview"] = aw_preview[:400]

    # ==================================================================
    # RECALC — revalue unpaid day-rows at their period's rate
    # dry_run=1 (default) reports and changes nothing.
    # ==================================================================
    elif action == "recalc":
        rc_dry = frappe.utils.cint(frappe.form_dict.get("dry_run") or 1)
        rc_from = frappe.form_dict.get("from_date")
        rc_to = frappe.form_dict.get("to_date")
        rc_farm = frappe.form_dict.get("farm")
        rc_run = frappe.form_dict.get("run")
        if not rc_from:
            out["error"] = "from_date is required"
        else:
            rc_conds = "we.work_date >= %(from_date)s AND IFNULL(we.paid,0) = 0 AND IFNULL(we.amount,0) > 0"
            rc_params = {"from_date": rc_from}
            if rc_to:
                rc_conds = rc_conds + " AND we.work_date <= %(to_date)s"
                rc_params["to_date"] = rc_to
            if rc_farm:
                rc_conds = rc_conds + " AND ac.farm = %(farm)s"
                rc_params["farm"] = rc_farm

            # --- GUARD: a task whose unit or daily target changed at the boundary
            # cannot have old rows revalued. A quantity recorded as "1 day" is not
            # the same measurement as "1 hour"; Garderner (340/Day/1) re-specified
            # as 10 Hrs @ 38.70 would pay 38.70 instead of 387. Not overridable.
            rc_prev_day = frappe.utils.add_days(rc_from, -1)
            rc_blocked = {}
            for g in frappe.db.sql("""
                SELECT cur.task task, cur.uom cur_uom, cur.daily_target cur_tgt,
                       prv.uom prv_uom, prv.daily_target prv_tgt
                FROM `tabWork Task Rate` cur
                INNER JOIN `tabWork Task Rate` prv ON prv.task = cur.task
                WHERE cur.valid_from <= %(d)s AND (cur.valid_to IS NULL OR cur.valid_to >= %(d)s)
                  AND prv.valid_from <= %(p)s AND (prv.valid_to IS NULL OR prv.valid_to >= %(p)s)
            """, {"d": rc_from, "p": rc_prev_day}, as_dict=True):
                same_uom = (g.cur_uom or "") == (g.prv_uom or "")
                same_tgt = abs(frappe.utils.flt(g.cur_tgt) - frappe.utils.flt(g.prv_tgt)) < 0.000001
                if not same_uom or not same_tgt:
                    rc_blocked[g.task] = ("unit or daily target changed at " + str(rc_from) +
                                          " (" + str(g.prv_tgt) + " " + str(g.prv_uom or "") +
                                          " -> " + str(g.cur_tgt) + " " + str(g.cur_uom or "") +
                                          ") - recorded quantities are not comparable")

            rc_rows = frappe.db.sql("""
                SELECT we.name rowname, we.parent actuals, we.employee, we.employee_name,
                       we.work_date, we.actual_quantity qty, we.amount, we.payment_ref,
                       ac.task task, ac.farm farm,
                       wtr.name period, wtr.rate new_rate, wtr.derived derived
                FROM `tabWork Actuals Employee` we
                INNER JOIN `tabWork Management Actuals` ac ON we.parent = ac.name
                LEFT JOIN `tabWork Task Rate` wtr
                       ON wtr.task = ac.task
                      AND wtr.valid_from <= we.work_date
                      AND (wtr.valid_to IS NULL OR wtr.valid_to >= we.work_date)
                WHERE """ + rc_conds + """
                ORDER BY we.work_date, we.name
            """, rc_params, as_dict=True)

            rc_todo = []
            rc_skips = {}
            rc_by_task = {}
            rc_old_total = 0
            rc_new_total = 0
            for r in rc_rows:
                why = None
                if not r.period:
                    why = "no rate period covering " + str(r.work_date)
                elif not frappe.utils.cint(r.derived):
                    why = "not wage-derived"
                elif rc_blocked.get(r.task):
                    why = rc_blocked.get(r.task)
                if why:
                    key = str(r.task) + " :: " + why
                    if key not in rc_skips:
                        rc_skips[key] = {"task": r.task, "why": why, "rows": 0, "amount": 0}
                    rc_skips[key]["rows"] = rc_skips[key]["rows"] + 1
                    rc_skips[key]["amount"] = rc_skips[key]["amount"] + frappe.utils.flt(r.amount)
                    continue

                old_amt = frappe.utils.flt(r.amount)
                new_amt = frappe.utils.flt(frappe.utils.flt(r.qty) * frappe.utils.flt(r.new_rate), 2)
                if abs(new_amt - old_amt) <= 0.005:
                    continue
                rc_todo.append(r)
                rc_old_total = rc_old_total + old_amt
                rc_new_total = rc_new_total + new_amt
                if r.task not in rc_by_task:
                    rc_by_task[r.task] = {"task": r.task, "rows": 0, "old": 0, "new": 0}
                rc_by_task[r.task]["rows"] = rc_by_task[r.task]["rows"] + 1
                rc_by_task[r.task]["old"] = rc_by_task[r.task]["old"] + old_amt
                rc_by_task[r.task]["new"] = rc_by_task[r.task]["new"] + new_amt

            out["dry_run"] = rc_dry
            out["from_date"] = rc_from
            out["rows_examined"] = len(rc_rows)
            out["rows_to_change"] = len(rc_todo)
            out["old_total"] = frappe.utils.flt(rc_old_total, 2)
            out["new_total"] = frappe.utils.flt(rc_new_total, 2)
            out["delta"] = frappe.utils.flt(rc_new_total - rc_old_total, 2)
            out["by_task"] = sorted(rc_by_task.values(), key=lambda x: -x["new"])
            out["skipped"] = sorted(rc_skips.values(), key=lambda x: -x["rows"])
            out["pending_accounts_rows"] = len([r for r in rc_todo if r.payment_ref])

            if not rc_dry and rc_todo:
                # ---- run log: created once, appended to on every chunk
                if rc_run and frappe.db.exists("Work Rate Recalc Run", rc_run):
                    run = frappe.get_doc("Work Rate Recalc Run", rc_run)
                else:
                    run = frappe.new_doc("Work Rate Recalc Run")
                    run.from_date = rc_from
                    run.to_date = rc_to
                    run.farm = rc_farm
                    run.dry_run = 0
                    run.status = "Applied"
                    run.executed_by = frappe.session.user
                    run.executed_on = frappe.utils.now()
                    run.flags.ignore_permissions = True
                    run.insert(ignore_permissions=True)

                batch = rc_todo[:CHUNK]
                rc_parents = {}
                rc_payments = {}
                for r in batch:
                    new_amt = frappe.utils.flt(frappe.utils.flt(r.qty) * frappe.utils.flt(r.new_rate), 2)
                    old_amt = frappe.utils.flt(r.amount)
                    frappe.db.set_value("Work Actuals Employee", r.rowname, "amount",
                                        new_amt, update_modified=False)
                    rc_parents[r.actuals] = 1
                    if r.payment_ref:
                        rc_payments[r.payment_ref] = 1
                    ln = run.append("lines", {})
                    ln.ref_doctype = "Work Actuals Employee"
                    ln.ref_name = r.rowname
                    ln.ref_parent = r.actuals
                    ln.task = r.task
                    ln.employee = r.employee
                    ln.work_date = r.work_date
                    ln.old_amount = old_amt
                    ln.new_amount = new_amt
                    ln.new_rate = frappe.utils.flt(r.new_rate, 6)
                    ln.old_rate = frappe.utils.flt(old_amt / frappe.utils.flt(r.qty), 6) if frappe.utils.flt(r.qty) else 0

                # re-sum every touched actuals document
                for pname in rc_parents:
                    tot = frappe.db.sql("""
                        SELECT COALESCE(SUM(amount),0) p FROM `tabWork Actuals Employee` WHERE parent = %s
                    """, (pname,), as_dict=True)
                    if tot:
                        frappe.db.set_value("Work Management Actuals", pname, "total_payment",
                                            frappe.utils.flt(tot[0].p), update_modified=False)

                # ---- payment documents already sent to accounts: rewritten IN PLACE.
                # Each one gets a comment so an edit to a document already handed over
                # is auditable rather than silent.
                for pay in rc_payments:
                    pay_lines = frappe.db.sql("""
                        SELECT name, actuals, employee, amount, qty FROM `tabWork Payment Line`
                        WHERE parent = %s
                    """, (pay,), as_dict=True)
                    grand = 0
                    for pl in pay_lines:
                        s = frappe.db.sql("""
                            SELECT COALESCE(SUM(amount),0) a, COALESCE(SUM(actual_quantity),0) q
                            FROM `tabWork Actuals Employee`
                            WHERE parent = %s AND employee = %s AND payment_ref = %s
                        """, (pl.actuals, pl.employee, pay), as_dict=True)
                        new_line_amt = frappe.utils.flt(s[0].a, 2) if s else frappe.utils.flt(pl.amount)
                        new_line_qty = frappe.utils.flt(s[0].q) if s else frappe.utils.flt(pl.qty)
                        if abs(new_line_amt - frappe.utils.flt(pl.amount)) > 0.005:
                            frappe.db.set_value("Work Payment Line", pl.name, "amount",
                                                new_line_amt, update_modified=False)
                            if new_line_qty:
                                frappe.db.set_value("Work Payment Line", pl.name, "rate",
                                                    frappe.utils.flt(new_line_amt / new_line_qty, 6),
                                                    update_modified=False)
                            ln = run.append("lines", {})
                            ln.ref_doctype = "Work Payment Line"
                            ln.ref_name = pl.name
                            ln.ref_parent = pay
                            ln.employee = pl.employee
                            ln.old_amount = frappe.utils.flt(pl.amount)
                            ln.new_amount = new_line_amt
                        grand = grand + new_line_amt
                    old_grand = frappe.utils.flt(frappe.db.get_value("Work Management Payment", pay, "grand_total"))
                    if abs(grand - old_grand) > 0.005:
                        frappe.db.set_value("Work Management Payment", pay, "grand_total",
                                            frappe.utils.flt(grand, 2), update_modified=False)
                        frappe.get_doc({
                            "doctype": "Comment",
                            "comment_type": "Info",
                            "reference_doctype": "Work Management Payment",
                            "reference_name": pay,
                            "content": ("Revalued by rate recalculation " + run.name + ": " +
                                        str(frappe.utils.flt(old_grand, 2)) + " -> " +
                                        str(frappe.utils.flt(grand, 2)) + " (work from " +
                                        str(rc_from) + "). Still pending accounts."),
                        }).insert(ignore_permissions=True)

                run.rows_changed = frappe.utils.cint(run.rows_changed) + len(batch)
                run.old_total = frappe.utils.flt(run.old_total) + sum(
                    [frappe.utils.flt(x.amount) for x in batch])
                run.new_total = frappe.utils.flt(run.new_total) + sum(
                    [frappe.utils.flt(frappe.utils.flt(x.qty) * frappe.utils.flt(x.new_rate), 2) for x in batch])
                run.delta = frappe.utils.flt(run.new_total) - frappe.utils.flt(run.old_total)
                run.rows_skipped = sum([s["rows"] for s in rc_skips.values()])
                run.payments_updated = frappe.utils.cint(run.payments_updated) + len(rc_payments)
                run.summary = frappe.as_json({
                    "by_task": out["by_task"], "skipped": out["skipped"]})
                run.flags.ignore_permissions = True
                run.save(ignore_permissions=True)
                frappe.db.commit()

                out["run"] = run.name
                out["applied_now"] = len(batch)
                out["parents_resummed"] = len(rc_parents)
                out["payments_updated"] = len(rc_payments)
                out["remaining"] = len(rc_todo) - len(batch)

    # ==================================================================
    # REVERSE — put every row a run touched back to its old value
    # ==================================================================
    elif action == "reverse":
        rv_run = frappe.form_dict.get("run")
        if not rv_run:
            out["error"] = "run is required"
        elif not frappe.db.exists("Work Rate Recalc Run", rv_run):
            out["error"] = "no such run: " + str(rv_run)
        else:
            rv = frappe.get_doc("Work Rate Recalc Run", rv_run)
            if rv.status == "Reversed":
                out["error"] = "run " + rv_run + " has already been reversed"
            else:
                rv_parents = {}
                rv_pays = {}
                rv_n = 0
                for ln in rv.lines:
                    if ln.ref_doctype == "Work Actuals Employee":
                        if frappe.db.exists("Work Actuals Employee", ln.ref_name):
                            frappe.db.set_value("Work Actuals Employee", ln.ref_name, "amount",
                                                frappe.utils.flt(ln.old_amount), update_modified=False)
                            rv_parents[ln.ref_parent] = 1
                            rv_n = rv_n + 1
                    elif ln.ref_doctype == "Work Payment Line":
                        if frappe.db.exists("Work Payment Line", ln.ref_name):
                            frappe.db.set_value("Work Payment Line", ln.ref_name, "amount",
                                                frappe.utils.flt(ln.old_amount), update_modified=False)
                            rv_pays[ln.ref_parent] = 1
                            rv_n = rv_n + 1
                for pname in rv_parents:
                    tot = frappe.db.sql("""
                        SELECT COALESCE(SUM(amount),0) p FROM `tabWork Actuals Employee` WHERE parent = %s
                    """, (pname,), as_dict=True)
                    if tot:
                        frappe.db.set_value("Work Management Actuals", pname, "total_payment",
                                            frappe.utils.flt(tot[0].p), update_modified=False)
                for pay in rv_pays:
                    tot = frappe.db.sql("""
                        SELECT COALESCE(SUM(amount),0) a FROM `tabWork Payment Line` WHERE parent = %s
                    """, (pay,), as_dict=True)
                    if tot:
                        frappe.db.set_value("Work Management Payment", pay, "grand_total",
                                            frappe.utils.flt(tot[0].a, 2), update_modified=False)
                frappe.db.set_value("Work Rate Recalc Run", rv_run, {
                    "status": "Reversed",
                    "reversed_by": frappe.session.user,
                    "reversed_on": frappe.utils.now(),
                })
                frappe.db.commit()
                out["run"] = rv_run
                out["rows_reverted"] = rv_n
                out["parents_resummed"] = len(rv_parents)
                out["payments_resummed"] = len(rv_pays)

    # ==================================================================
    # PERIODS — rate history for one task
    # ==================================================================
    elif action == "periods":
        p_task = frappe.form_dict.get("task")
        if not p_task:
            out["error"] = "task is required"
        else:
            out["task"] = p_task
            out["periods"] = frappe.db.sql("""
                SELECT name, valid_from, valid_to, rate, uom, daily_target,
                       daily_wage_basis, derived, source, source_activity, notes
                FROM `tabWork Task Rate` WHERE task = %s ORDER BY valid_from DESC
            """, (p_task,), as_dict=True)
            out["task_master"] = frappe.db.get_value(
                "Task", p_task, ["custom_rate", "custom_uom", "custom_daily_target"], as_dict=True)

    else:
        out["error"] = "unknown action: " + str(action)

    return out
