# Ported from the upstream mirror's Server Script "wm_payroll_drift" (API) — logic unchanged.
# Farms / projects / company / approver roles now come from Work Management Settings
# and the Work Management Farm doctype — see work_management/api/config.py.
# REGENERATED by the mirror's port_app.py — edit the mirror script, not this file.

import json

import frappe

from work_management.api.config import get_config


@frappe.whitelist()
def wm_payroll_drift(**kwargs):
    _cfg = get_config()
    FARM_PROJECT = _cfg["farm_project"]
    DEFAULT_COMPANY = _cfg["default_company"]
    FARMS = _cfg["farms"]
    BLOCK_EXCLUDE = _cfg["block_exclude"]
    FARM_APPROVER_ROLE = _cfg["farm_approver_role"]
    HR_HEAD_ROLES = _cfg["hr_head_roles"]

    # Rows whose stored payroll flag no longer matches the rule.
    #
    # count_in_payroll and amount are decided once, when an actuals row is written,
    # and never revisited. Change an employee's classification, or edit the three
    # task-worker lists in Work Management Settings, and every row already recorded
    # keeps the old answer -- at zero, with nothing reporting it. That is how one
    # sprayer went a month unpaid for four days' work, and how 1,047 non-permanent
    # rows came to be stranded across July and August.
    #
    # This re-answers the question for rows already written and reports the ones
    # that disagree, in both directions: work recorded but unpayable, and work
    # marked payable whose employee no longer qualifies.
    #
    # ?action=summary            counts by date and by reason
    # ?action=rows&limit=500     the rows themselves
    # &from_date=&to_date=       window (defaults to the last 60 days)
    # &employee=                 one person

    action = frappe.form_dict.get("action") or "summary"
    out = {}

    d_from = frappe.form_dict.get("from_date") or frappe.utils.add_days(frappe.utils.today(), -60)
    d_to = frappe.form_dict.get("to_date") or frappe.utils.today()
    one_emp = frappe.form_dict.get("employee")

    # ---- the rule, read exactly as wm_actuals reads it -------------------------
    # Same separators and the same character whitelist. If this disagreed, the rows
    # it flagged would disagree with the rows the entry screen writes.
    DRIFT_LISTS = [
        ("employment_type", "Work Management Payable Employment Type", "employment_type", "tw_employment_types"),
        ("designation", "Work Management Payable Designation", "designation", "tw_designations"),
        ("custom_category", "Work Management Payable Category", "category", "tw_categories"),
    ]
    RULE = {}
    for dr_col, dr_child, dr_cfield, dr_box in DRIFT_LISTS:
        dr_vals = []
        # Pickers first, the old typed boxes second -- the same order the entry
        # screen reads them in. If these two disagreed, the detector would report
        # drift that the screen does not see, or miss drift that it does.
        if frappe.db.exists("DocType", dr_child):
            for dr_r in frappe.get_all(dr_child,
                    filters={"parenttype": "Work Management Settings"}, fields=[dr_cfield]):
                dr_p = str(dr_r.get(dr_cfield) or "").strip()
                if dr_p:
                    dr_vals.append(dr_p)
        if not dr_vals:
            dr_raw = frappe.db.get_single_value("Work Management Settings", dr_box)
            for dr_v in str(dr_raw or "").replace("\r", "\n").replace("\n", ",").split(","):
                dr_c = dr_v.strip()
                dr_ok = 1
                for dr_ch in dr_c:
                    if not (dr_ch.isalnum() or dr_ch in " -_/&().'"):
                        dr_ok = 0
                if dr_c and dr_ok:
                    dr_vals.append(dr_c)
        RULE[dr_col] = dr_vals
    out["rule"] = RULE

    # ---- the rows in the window ------------------------------------------------
    dconds = "we.work_date BETWEEN %(f)s AND %(t)s"
    dparams = {"f": d_from, "t": d_to}
    if one_emp:
        dconds = dconds + " AND we.employee = %(e)s"
        dparams["e"] = one_emp

    # Only the Employee columns THIS site actually has. Selecting one it has not got
    # is not a blank value, it is (1054, "Unknown column ...") and no drift report at all.
    # A column left out here reads back as None, which is exactly what the
    # qualification test already does with a blank one. frappe.db.has_column is not
    # in the sandbox's globals, but the meta is, and it knows custom fields too.
    D_META = frappe.get_meta("Employee")
    D_PICK = []
    for d_mc in ("employment_type", "designation", "custom_category"):
        if D_META.get_field(d_mc):
            D_PICK.append("e." + d_mc)
    D_COLS = ", ".join(D_PICK)

    drows = frappe.db.sql("""
        SELECT we.name, we.parent, we.employee, we.employee_name, we.work_date,
               we.actual_quantity, we.amount, IFNULL(we.count_in_payroll,0) stored,
               ac.rate, ac.task, ac.farm, ac.workflow_state, IFNULL(ac.paid,0) doc_paid""" + \
               (", " + D_COLS if D_COLS else "") + """
        FROM `tabWork Actuals Employee` we
        INNER JOIN `tabWork Management Actuals` ac ON we.parent = ac.name
        LEFT JOIN `tabEmployee` e ON e.name = we.employee
        WHERE """ + dconds + """
        ORDER BY we.work_date
    """, dparams, as_dict=True)

    drift = []
    for dr in drows:
        if not dr.employment_type and not dr.designation and not dr.custom_category:
            continue  # employee gone or blank: a different problem, not guessed at
        expected = 0
        for dcol in ("employment_type", "designation", "custom_category"):
            if RULE.get(dcol) and (dr.get(dcol) or "") in RULE[dcol]:
                expected = 1
        if expected == frappe.utils.cint(dr.stored):
            continue
        drift.append({
            "row": dr.name, "doc": dr.parent, "employee": dr.employee,
            "employee_name": dr.employee_name, "work_date": str(dr.work_date),
            "quantity": frappe.utils.flt(dr.actual_quantity),
            "amount": frappe.utils.flt(dr.amount),
            "rate": frappe.utils.flt(dr.rate), "task": dr.task, "farm": dr.farm,
            "state": dr.workflow_state, "doc_paid": frappe.utils.cint(dr.doc_paid),
            "stored": frappe.utils.cint(dr.stored), "expected": expected,
            "employment_type": dr.employment_type, "designation": dr.designation,
            "category": dr.custom_category,
            "value": round(frappe.utils.flt(dr.actual_quantity) * frappe.utils.flt(dr.rate), 2)
                if expected else 0,
        })

    out["window"] = {"from_date": str(d_from), "to_date": str(d_to)}
    out["scanned"] = len(drows)

    unpaid = [x for x in drift if x["expected"] == 1]
    overpaid = [x for x in drift if x["expected"] == 0]
    by_date = {}
    for x in unpaid:
        by_date[x["work_date"]] = by_date.get(x["work_date"], 0) + 1

    out["totals"] = {
        "drift_rows": len(drift),
        "recorded_but_unpayable": len(unpaid),
        "value_withheld": round(sum(x["value"] for x in unpaid), 2),
        "people_affected": len(set([x["employee"] for x in unpaid])),
        "documents_affected": len(set([x["doc"] for x in unpaid])),
        "documents_already_paid": len(set([x["doc"] for x in unpaid if x["doc_paid"]])),
        "marked_payable_but_no_longer_qualifies": len(overpaid),
    }
    out["by_date"] = by_date

    if action == "rows":
        dlimit = frappe.utils.cint(frappe.form_dict.get("limit") or 500)
        out["rows"] = drift[:dlimit]
        out["truncated"] = 1 if len(drift) > dlimit else 0

    return out
